import assert from 'node:assert/strict';
import test from 'node:test';
import {ProjectTaskWorkspacePage} from '../src/pages/project-task-workspace.page.ts';
import {createServicePageHarness,serviceText} from './service-page-react-harness.mjs';
const records={forge_project:[{id:'project-a',name:'授权项目',code:'P-A',manager_id:'actor-a',planned_start_on:'2026-10-01',planned_end_on:'2026-10-20'}],forge_project_plan:[{id:'plan-a',name:'正式计划',project_id:'project-a',status:'active'}],forge_project_member:[{id:'member-a',name:'原项目经理',project_id:'project-a',user_id:'actor-a',active:true}],forge_business_setting_option:[{id:'type-a',name:'交付任务',scope:'project',setting_type:'task_type',enabled:true}],forge_project_work_item:[{id:'task-a',name:'既有任务',item_type:'task',task_type:'type-a',project_id:'project-a',plan_id:'plan-a',owner_id:'actor-a',owner_position_assignment_id:'position-a',priority:'medium',planned_start_on:'2026-10-01',planned_end_on:'2026-10-20',estimated_hours:8,status:'pending'}]};
function nodes(value,predicate,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return[];seen.add(value);return[...(predicate(value)?[value]:[]),...Object.values(value).flatMap(item=>Array.isArray(item)?item.flatMap(child=>nodes(child,predicate,seen)):nodes(item,predicate,seen))]}
const button=(tree,label)=>nodes(tree,n=>n.type==='button'&&serviceText(n).trim()===label)[0];const field=(tree,label)=>nodes(tree,n=>n.props?.['aria-label']===label)[0];const draft=tree=>nodes(tree,n=>n.type==='ForgeDialog'&&n.props.open&&['新建任务','编辑任务'].includes(n.props.title))[0];
async function fixture(onAction=()=>({assignments:[{id:'position-a',active:true,appointed:true,projectTaskCapable:true}],default_assignment_id:'position-a',project_task_capable:true})){const h=createServicePageHarness(ProjectTaskWorkspacePage,{records,permissions:['forge_project_manager'],globals:{ExportConfigurationDialog:function ExportConfigurationDialog(){},window:{location:{search:''}}},onAction});await h.flushEffects();return h}

test('create default role data does not cause a false discard prompt, while title edits do',async()=>{const h=await fixture();button(h.render(),'新建任务').props.onClick();await h.settle();assert.equal(draft(h.render()).props.confirmOnDiscard,false);field(h.render(),'任务标题').props.onChange({target:{value:'中文新建内容保留'}});assert.equal(draft(h.render()).props.confirmOnDiscard,true);assert.equal(field(h.render(),'任务标题').props.value,'中文新建内容保留')});

test('edit comparisons use the displayed draft values, normalize numeric values and preserve state until guarded cancellation',async()=>{const h=await fixture();button(h.render(),'编辑').props.onClick();await h.settle();assert.equal(draft(h.render()).props.confirmOnDiscard,false);field(h.render(),'任务标题').props.onChange({target:{value:'中文编辑内容保留'}});assert.equal(draft(h.render()).props.confirmOnDiscard,true);field(h.render(),'任务标题').props.onChange({target:{value:'既有任务'}});assert.equal(draft(h.render()).props.confirmOnDiscard,false);draft(h.render()).props.onCancel();assert.equal(draft(h.render()),undefined);assert.equal(h.calls.filter(call=>call.path.startsWith('/actions/')).every(call=>call.path.includes('position_assignments_read')),true)});

test('a late role response from a discarded draft cannot change the next draft or its baseline',async()=>{let release,roleReads=0;const h=await fixture(()=>++roleReads===1?new Promise(resolve=>{release=resolve}):({assignments:[],default_assignment_id:'',project_task_capable:true}));button(h.render(),'新建任务').props.onClick();assert.equal(draft(h.render()).props.confirmOnDiscard,false);draft(h.render()).props.onCancel();button(h.render(),'新建任务').props.onClick();release({assignments:[{id:'old-position',active:true,appointed:true,projectTaskCapable:true}],default_assignment_id:'old-position',project_task_capable:true});await h.settle();assert.equal(field(h.render(),'负责人项目岗位').props.value,'');assert.equal(draft(h.render()).props.confirmOnDiscard,false)});
