import assert from 'node:assert/strict';
import test from 'node:test';
const {ProjectCenterPage}=await import(process.env.FORGE_PROJECT_CENTER_FIXTURE_PAGE||'../src/pages/project-center.page.ts');
import {createServicePageHarness,serviceText} from './service-page-react-harness.mjs';

const actor='service-page-actor',project={id:'project-a',name:'授权项目',code:'PRJ-A',organization_id:'org-a',owner_id:actor,manager_id:actor,status:'in_progress',planned_start_on:'2026-10-01',planned_end_on:'2026-10-20',progress:0};
function nodes(value,predicate,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return[];seen.add(value);return[...(predicate(value)?[value]:[]),...Object.values(value).flatMap(item=>Array.isArray(item)?item.flatMap(child=>nodes(child,predicate,seen)):nodes(item,predicate,seen))]}
const button=(tree,text)=>nodes(tree,n=>n.type==='button'&&serviceText(n).trim()===text)[0];
const includesButton=(tree,text)=>nodes(tree,n=>n.type==='button'&&serviceText(n).includes(text))[0];
const field=(tree,label)=>nodes(tree,n=>n.props?.label===label)[0];
const dialog=tree=>nodes(tree,n=>n.type==='ForgeDialog'&&n.props.open)[0];
async function fixture(search='',onAction=()=>({}),onWrite,moduleGrant={allowRead:true,allowCreate:true,allowEdit:true},moduleReadStatus=200){
 const records={forge_project:[project],forge_customer:[{id:'customer-a',name:'合成客户'}],forge_project_type:[{id:'type-a',name:'正式项目类型',active:true}],sys_user:[{id:actor,name:'原项目经理'}],forge_sales_order:[{id:'order-a',name:'已批准订单',customer_id:'customer-a',contract_id:'contract-a',status:'active',approval_outcome:'approved'}],forge_project_member:[{id:'member-a',project_id:project.id,user_id:actor,active:true}],forge_project_plan_template:[{id:'template-a',name:'合成系统模板',organization_id:'org-a',category:'system',status:'active',structure_json:JSON.stringify([{source_id:'task-a',item_type:'task',owner_id:actor,name:'模板任务'}])}]};
 const transport=async(url,options={})=>{const u=new URL(url),route=u.pathname.replace('/api/v1','');if(route.startsWith('/data/')&&(options.method||'GET')!=='GET')return onWrite?onWrite({url,options}):{ok:true,status:200,headers:new Headers(),json:async()=>({})};let payload,status=200;if(route==='/auth/get-session')payload={user:{id:actor}};else if(route==='/auth/me/permissions')payload={systemPermissions:['forge_project_operator','forge_project_manager'],objects:moduleGrant?{forge_project_module_preference:moduleGrant}:{}};else if(route==='/workbench/business-actions/context')payload={version:'1',actions:[{capabilityId:'forge:action:forge_customer.customer_create_project',parameters:[['approved_order_id',[['order-a','已批准订单']]],['type_id',[['type-a','正式项目类型']]],['manager_id',[[actor,'原项目经理']]]].map(([name,options])=>({name,enum:options.map(x=>x[0]),enumLabels:options.map(([value,label])=>({value,label}))}))}]};else if(route.startsWith('/actions/'))payload=await onAction({path:route,method:options.method,body:JSON.parse(options.body||'{}')});else if(route.startsWith('/data/forge_project_module_preference')&&moduleReadStatus!==200){status=moduleReadStatus;payload={error:'module read denied'}}else{const rows=records[route.split('/').at(-1)]||[];payload={records:rows,total:rows.length}}return{ok:status<400,status,headers:new Headers(),json:async()=>payload}};
 const h=createServicePageHarness(ProjectCenterPage,{records,permissions:['forge_project_operator','forge_project_manager'],globals:{__name:value=>value,Switch:function Switch(){},window:{location:{search,href:'http://service-page.test/'+search},history:{pushState(){}},addEventListener(){},removeEventListener(){}}},onAction,transport});await h.flushEffects();return h;
}

test('new project protects only editable changes and provides a return path from confirmation',async()=>{const h=await fixture();button(h.render(),'新建项目').props.onClick();assert.equal(dialog(h.render()).props.confirmOnDiscard,false);field(h.render(),'项目名称').props.onChange('中文项目输入保留');assert.equal(dialog(h.render()).props.confirmOnDiscard,true);for(const [label,value] of [['关联客户','customer-a'],['已批准销售订单','order-a'],['项目类型','type-a'],['项目负责人',actor],['计划开始日期','2026-10-01'],['计划结束日期','2026-10-20']])field(h.render(),label).props.onChange(value);await h.settle();dialog(h.render()).props.onConfirm();assert.equal(dialog(h.render()).props.secondaryLabel,'返回修改');dialog(h.render()).props.onSecondary();assert.equal(field(h.render(),'项目名称').props.value,'中文项目输入保留');assert.equal(dialog(h.render()).props.confirmLabel,'下一步');assert.equal(h.calls.some(c=>c.path.startsWith('/actions/')),false)});

test('manual plan defaults are pristine and confirmation returns to the same stage and deliverable',async()=>{const h=await fixture('?project=project-a&tab=plan');includesButton(h.render(),'手动创建').props.onClick();assert.equal(dialog(h.render()).props.confirmOnDiscard,false);field(h.render(),'首个阶段名称').props.onChange('正式阶段');field(h.render(),'计划产出物').props.onChange('中文交付说明保留');assert.equal(dialog(h.render()).props.confirmOnDiscard,true);dialog(h.render()).props.onConfirm();assert.equal(dialog(h.render()).props.secondaryLabel,'返回修改');dialog(h.render()).props.onSecondary();assert.equal(field(h.render(),'计划产出物').props.value,'中文交付说明保留');assert.equal(dialog(h.render()).props.confirmLabel,'创建计划')});

test('module settings use named controlled switches, preserve cancellation and reset to the opened values',async()=>{const h=await fixture('?project=project-a');includesButton(h.render(),'功能开关').props.onClick();assert.equal(dialog(h.render()).props.confirmOnDiscard,false);const switches=nodes(h.render(),n=>n.type==='Switch');assert.equal(switches.length,11);assert.ok(switches.every(x=>typeof x.props['aria-label']==='string'));switches.find(x=>x.props['aria-label']==='计划进度').props.onCheckedChange(false);assert.equal(dialog(h.render()).props.confirmOnDiscard,true);button(h.render(),'重置更改').props.onClick();assert.equal(dialog(h.render()).props.confirmOnDiscard,false);assert.equal(nodes(h.render(),n=>n.type==='Switch').find(x=>x.props['aria-label']==='计划进度').props.checked,true);assert.ok(!serviceText(h.render()).includes('按当前登录用户保存'));assert.equal(h.calls.some(c=>c.method!=='GET'),false)});

test('a failed module save keeps changes and a busy dialog rejects duplicate handlers',{timeout:5000},async()=>{let release;const h=await fixture('?project=project-a',()=>({}),()=>new Promise(resolve=>{release=resolve}));includesButton(h.render(),'功能开关').props.onClick();button(h.render(),'全部关闭').props.onClick();const save=dialog(h.render()).props.onConfirm,saving=save();assert.equal(dialog(h.render()).props.busy,true);dialog(h.render()).props.onCancel();assert.ok(dialog(h.render()));await save();assert.ok(nodes(h.render(),n=>n.type==='Switch').every(x=>x.props.disabled));assert.equal(h.calls.filter(c=>c.method==='POST'&&c.path.includes('module_preference')).length,1);release({ok:false,status:403,headers:new Headers(),json:async()=>({error:'拒绝保存模块设置'})});await saving;await h.settle();assert.equal(dialog(h.render()).props.busy,false);assert.equal(dialog(h.render()).props.error,'拒绝保存模块设置');assert.ok(nodes(h.render(),n=>n.type==='Switch').every(x=>x.props.checked===false));assert.equal(dialog(h.render()).props.confirmOnDiscard,true)});

test('a late template role reply cannot overwrite the assignments of a replacement draft',async()=>{let release,count=0;const result=id=>({assignments:[{id,active:true,appointed:true,projectTaskCapable:true,positionLabel:'正式项目岗位'}],default_assignment_id:id});const h=await fixture('?project=project-a&tab=plan',()=>++count===1?new Promise(resolve=>{release=resolve}):result('new-assignment'));includesButton(h.render(),'套用系统模板').props.onClick();field(h.render(),'计划模板').props.onChange('template-a');assert.equal(dialog(h.render()).props.confirmOnDiscard,true);dialog(h.render()).props.onCancel();includesButton(h.render(),'套用系统模板').props.onClick();assert.equal(dialog(h.render()).props.confirmOnDiscard,false);field(h.render(),'计划模板').props.onChange('template-a');release(result('old-assignment'));await h.settle();assert.equal(field(h.render(),'项目岗位').props.value,'new-assignment');assert.equal(h.calls.filter(c=>c.method==='POST').every(c=>c.path.includes('position_assignments_read')),true)});

test('a module read denial never claims eleven enabled modules or offers editable settings',async()=>{const h=await fixture('?project=project-a',()=>({}),undefined,null,403);includesButton(h.render(),'功能开关').props.onClick();const d=dialog(h.render());assert.equal(d.props.title,'项目功能模块');assert.equal(d.props.confirmLabel,'关闭');assert.equal(d.props.confirmOnDiscard,false);assert.equal(nodes(h.render(),n=>n.type==='Switch').length,0);assert.ok(serviceText(h.render()).includes('无法确认当前启用项'));d.props.onConfirm();assert.equal(dialog(h.render()),undefined);assert.equal(h.calls.some(c=>c.method!=='GET'),false)});

test('read-only module grants show disabled shared switches and close without a write',async()=>{const h=await fixture('?project=project-a',()=>({}),undefined,{allowRead:true});includesButton(h.render(),'功能开关').props.onClick();const d=dialog(h.render());assert.equal(d.props.confirmLabel,'关闭');assert.ok(nodes(h.render(),n=>n.type==='Switch').every(x=>x.props.disabled));d.props.onConfirm();assert.equal(dialog(h.render()),undefined);assert.equal(h.calls.some(c=>c.method!=='GET'),false)});
