import { defineFlow } from '@objectstack/spec/automation';

export const SalesQuotationApprovalFlow = defineFlow({
  name: 'sales_quotation_approval',
  label: '销售报价审批',
  description: '报价提交后进入 ObjectStack 原生审批中心；审批结论只作用于提交时冻结的核价版本。',
  type: 'record_change',
  status: 'active',
  runAs: 'system',
  successMessage: '销售报价审批已完成',
  errorMessage: '销售报价审批未能继续，请检查销售报价审批岗配置',
  nodes: [
    {
      id: 'start',
      type: 'start',
      label: '报价已提交',
      config: {
        objectName: 'forge_quotation',
        triggerType: 'record-after-update',
        condition: "record.status == 'pending_approval' && previous.status == 'draft'",
      },
      position: { x: 80, y: 160 },
    },
    {
      id: 'quotation_review',
      type: 'approval',
      label: '销售报价审批',
      config: {
        approvers: [{ type: 'position', value: 'sales_quotation_reviewer', group: 'sales_quotation' }],
        behavior: 'per_group',
        lockRecord: true,
        onEmptyApprovers: 'fail',
        maxRevisions: 0,
      },
      position: { x: 330, y: 160 },
    },
    {
      id: 'approve_quote',
      type: 'update_record',
      label: '报价审批通过',
      config: { objectName: 'forge_quotation', filter: { id: '{record.id}' }, fields: { status: 'approved' } },
      position: { x: 600, y: 80 },
    },
    {
      id: 'notify_approved',
      type: 'notify',
      label: '通知报价负责人',
      config: {
        recipients: ['{record.responsible_id}'],
        title: '报价 {record.code} 已审批通过',
        message: '已审批版本可以登记客户发送凭证。',
        topic: 'sales.quotation.approved',
        severity: 'info',
        sourceObject: 'forge_quotation',
        sourceId: '{record.id}',
        actionUrl: '/_console/apps/com.inoforge.forge.sales/page_sales_quotations?id={record.id}',
      },
      position: { x: 850, y: 80 },
    },
    {
      id: 'reject_quote',
      type: 'update_record',
      label: '驳回报价',
      config: { objectName: 'forge_quotation', filter: { id: '{record.id}' }, fields: { status: 'rejected' } },
      position: { x: 600, y: 260 },
    },
    {
      id: 'notify_rejected',
      type: 'notify',
      label: '通知报价负责人驳回',
      config: {
        recipients: ['{record.responsible_id}'],
        title: '报价 {record.code} 未获审批',
        message: '请查看审批中心意见后调整报价并重新提交。',
        topic: 'sales.quotation.rejected',
        severity: 'warning',
        sourceObject: 'forge_quotation',
        sourceId: '{record.id}',
        actionUrl: '/_console/apps/com.inoforge.forge.sales/page_sales_quotations?id={record.id}',
      },
      position: { x: 850, y: 260 },
    },
    { id: 'approved_end', type: 'end', label: '审批通过', position: { x: 1100, y: 80 } },
    { id: 'rejected_end', type: 'end', label: '审批驳回', position: { x: 1100, y: 260 } },
  ],
  edges: [
    { id: 'submit_to_review', source: 'start', target: 'quotation_review' },
    { id: 'review_approved', source: 'quotation_review', target: 'approve_quote', label: 'approve' },
    { id: 'approved_to_notify', source: 'approve_quote', target: 'notify_approved' },
    { id: 'approved_to_end', source: 'notify_approved', target: 'approved_end' },
    { id: 'review_rejected', source: 'quotation_review', target: 'reject_quote', label: 'reject' },
    { id: 'rejected_to_notify', source: 'reject_quote', target: 'notify_rejected' },
    { id: 'rejected_to_end', source: 'notify_rejected', target: 'rejected_end' },
  ],
});
