import assert from 'node:assert/strict';
import test from 'node:test';
import {ProjectCenterPage} from '../src/pages/project-center.page.ts';
import {createServicePageHarness,serviceText} from './service-page-react-harness.mjs';

const project={id:'project-a',name:'授权项目资料',code:'PRJ-A',organization_id:'org-a',owner_id:'actor-a',manager_id:'actor-a',status:'in_progress',progress:0};
const response=(value,status=200)=>({ok:status<400,status,headers:new Headers(),json:async()=>value});
function nodes(value,predicate,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return[];seen.add(value);return[...(predicate(value)?[value]:[]),...Object.values(value).flatMap(item=>Array.isArray(item)?item.flatMap(child=>nodes(child,predicate,seen)):nodes(item,predicate,seen))]}
function fixture(failures={},search='?project=project-a'){const listeners={};const h=createServicePageHarness(ProjectCenterPage,{globals:{__name:value=>value,window:{location:{search,href:'http://service-page.test/'+search},history:{pushState(){}},addEventListener(name,handler){listeners[name]=handler},removeEventListener(name){delete listeners[name]}}},transport:async(url,options={})=>{const u=new URL(url),route=u.pathname.replace('/api/v1','');if(route==='/actions/forge_project/project_read_delivery_scope'){assert.equal(options.method,'POST');return failures.delivery_scope?response({error:'expired delivery read'},failures.delivery_scope):response({sources:[],lines:[],warnings:[]})}assert.equal(options.method||'GET','GET');if(route==='/auth/get-session')return response({user:{id:'actor-a'}});if(route==='/auth/me/permissions')return response({systemPermissions:['forge_project_operator','forge_project_manager']});const object=route.split('/').at(-1);if(failures[object])return response({error:'backend diagnostic'},failures[object]);return response({records:object==='forge_project'?[project]:[],total:object==='forge_project'?1:0})}});return Object.assign(h,{reloadProject:()=>listeners.popstate()})}

test('project auxiliary 401 stops the detail instead of rendering authorized data with an expired session',async()=>{const h=fixture({forge_project_work_item:401}),tree=await h.flushEffects();assert.ok(serviceText(tree).includes('登录已失效'));assert.ok(!serviceText(tree).includes('授权项目资料'));assert.ok(h.states.filter(x=>x&&Array.isArray(x.projects)).every(x=>x.projects.length===0))});

test('a project retry preserves the selected project ID and never sends the click event as a filter',async()=>{const failures={forge_project:403},h=fixture(failures);let tree=await h.flushEffects();delete failures.forge_project;const retry=nodes(tree,n=>n.type==='button'&&serviceText(n).trim()==='重试')[0];assert.ok(retry);retry.props.onClick({type:'click'});tree=await h.settle();assert.ok(serviceText(tree).includes('授权项目资料'));const projectCalls=h.calls.filter(c=>c.path==='/data/forge_project');assert.ok(projectCalls.length>=2);for(const call of projectCalls)assert.equal(JSON.parse(new URL(call.url,'http://service-page.test').searchParams.get('$filter')).id,'project-a')});

test('a later primary denial clears all previous project and related data',async()=>{const failures={},h=fixture(failures);await h.flushEffects();failures.forge_project=403;const state=h.states.find(x=>x&&Array.isArray(x.projects));assert.equal(state.projects.length,1);h.reloadProject();const tree=await h.settle();assert.ok(serviceText(tree).includes('没有查看项目中心的权限'));assert.equal(h.states.find(x=>x&&Array.isArray(x.projects)).projects.length,0)});

test('a delivery scope 401 invalidates the detail and cannot be overwritten by a concurrent main load',async()=>{const h=fixture({delivery_scope:401},'?project=project-a&tab=orders'),tree=await h.flushEffects();assert.ok(serviceText(tree).includes('登录已失效'));assert.ok(!serviceText(tree).includes('授权项目资料'));assert.equal(h.states.find(x=>x&&Array.isArray(x.projects)).projects.length,0)});

test('an auxiliary 403 remains a local restriction and preserves the current project',async()=>{const h=fixture({forge_project_work_item:403}),tree=await h.flushEffects();assert.ok(serviceText(tree).includes('授权项目资料'));assert.equal(h.states.find(x=>x&&Array.isArray(x.projects)).readFailures.find(x=>x.object==='forge_project_work_item').status,403);assert.ok(!serviceText(tree).includes('登录已失效'))});
