/** Shared transient UI messages; business and read states remain in their pages. */
export const forgeMessageUiCss = `
.fp-message-region{position:fixed;inset:auto;top:24px;left:50%;transform:translateX(-50%);display:none;flex-direction:column;align-items:center;gap:8px;width:min(520px,calc(100vw - 32px));margin:0;padding:0;border:0;background:transparent;overflow:visible;pointer-events:none;z-index:11000;outline:0}.fp-message-region:popover-open,.fp-message-region[data-open="true"]{display:flex}.fp-message-tip{display:flex;align-items:flex-start;gap:9px;max-width:100%;padding:11px 14px;border:1px solid #e6e9ef;border-radius:7px;background:#fff;color:#172b4d;font:inherit;font-size:12.5px;line-height:19px;box-shadow:0 4px 16px rgba(9,30,66,.14);pointer-events:auto;animation:fp-message-enter .15s ease-out}.fp-message-icon{display:flex;align-items:center;justify-content:center;flex:0 0 16px;margin-top:1px;color:#1769e0}.fp-message-icon svg{display:block;width:16px;height:16px;stroke-width:2}.fp-message-tip[data-tone="error"] .fp-message-icon{color:#de350b}.fp-message-tip[data-tone="warning"] .fp-message-icon{color:#ff991f}.fp-message-tip[data-tone="success"] .fp-message-icon{color:#00875a}.fp-message-content{min-width:0;flex:1;overflow-wrap:anywhere;white-space:normal}.fp-message-content>.fp-button{margin-left:10px;vertical-align:middle}.fp-message-close{display:inline-flex;align-items:center;justify-content:center;flex:0 0 18px;width:18px;height:18px;margin:1px 0 0 2px;padding:0;border:0;border-radius:3px;background:transparent;color:#6b778c;cursor:pointer}.fp-message-close svg{width:13px;height:13px}.fp-message-close:hover{background:#f4f5f7;color:#172b4d}.fp-message-close:focus-visible{outline:2px solid var(--fp-primary,#0755d8);outline-offset:2px}.dark .fp-message-tip{background:hsl(var(--popover));color:hsl(var(--popover-foreground));border-color:hsl(var(--border))}@keyframes fp-message-enter{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){.fp-message-tip{animation:none}}`;

export const forgeMessageUiRuntime = `
const FORGE_MESSAGE_CSS=${JSON.stringify(forgeMessageUiCss)};
if(typeof document!=='undefined'){let style=document.getElementById('forge-message-style');if(!style){style=document.createElement('style');style.id='forge-message-style';document.head.appendChild(style)}style.textContent=FORGE_MESSAGE_CSS}
function forgeMessageText(node){if(node===null||node===undefined||typeof node==='boolean')return'';if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(forgeMessageText).join(' ');return React.Children.toArray(node.props?.children).map(forgeMessageText).join(' ')}
function ForgeMessage({children,tone='info',onClose,duration,notificationKey}){return typeof PageMessage!=='undefined'?<PageMessage severity={tone} duration={duration} notificationKey={notificationKey} onClose={onClose}>{children}</PageMessage>:<ForgeFallbackMessage tone={tone} duration={duration} notificationKey={notificationKey} onClose={onClose}>{children}</ForgeFallbackMessage>}
const forgeMessageStoreSymbol=Symbol.for('forge.ui.transient-messages');
const forgeMessageStore=typeof window==='undefined'?{owners:new Map(),entries:new Map(),listeners:new Set(),revision:0}:(window[forgeMessageStoreSymbol]||(window[forgeMessageStoreSymbol]={owners:new Map(),entries:new Map(),listeners:new Set(),revision:0}));
function forgeMessagePublish(){forgeMessageStore.revision++;for(const listener of forgeMessageStore.listeners)listener()}
function forgeMessageSubscribe(listener){forgeMessageStore.listeners.add(listener);return()=>forgeMessageStore.listeners.delete(listener)}
function forgeMessageSnapshot(){return forgeMessageStore.revision}
function forgeMessageExpire(key){const entry=forgeMessageStore.entries.get(key);if(!entry)return;clearTimeout(entry.timer);forgeMessageStore.entries.delete(key);forgeMessagePublish()}
function forgeMessageSchedule(entry){clearTimeout(entry.timer);if(entry.remaining===Infinity||entry.paused)return;entry.deadline=Date.now()+entry.remaining;entry.timer=setTimeout(()=>forgeMessageExpire(entry.key),entry.remaining)}
function forgeMessagePause(key){const entry=forgeMessageStore.entries.get(key);if(!entry||entry.remaining===Infinity||entry.paused)return;entry.paused=true;clearTimeout(entry.timer);entry.remaining=Math.max(0,entry.deadline-Date.now())}
function forgeMessageResume(key){const entry=forgeMessageStore.entries.get(key);if(entry){entry.paused=false;forgeMessageSchedule(entry)}}
function forgeMessageDismiss(key){const entry=forgeMessageStore.entries.get(key);if(!entry)return;const owners=Array.from(entry.owners).map(id=>forgeMessageStore.owners.get(id)).filter(Boolean);forgeMessageExpire(key);for(const owner of owners)owner.content.current.onClose?.()}
function forgeMessageRegister(id,key,content,duration,marker){forgeMessageStore.owners.set(id,{key,content,marker});let entry=forgeMessageStore.entries.get(key);if(!entry){entry={key,owners:new Set(),remaining:duration,deadline:0,timer:null,paused:false};forgeMessageStore.entries.set(key,entry)}entry.owners.add(id);entry.remaining=duration;forgeMessageSchedule(entry);forgeMessagePublish()}
function forgeMessageUnregister(id){const owner=forgeMessageStore.owners.get(id);if(!owner)return;forgeMessageStore.owners.delete(id);const entry=forgeMessageStore.entries.get(owner.key);if(entry){entry.owners.delete(id);if(!entry.owners.size){clearTimeout(entry.timer);forgeMessageStore.entries.delete(owner.key)}}forgeMessagePublish()}
function forgeMessageHostOwner(){for(const entry of Array.from(forgeMessageStore.entries.values()).reverse()){for(const id of Array.from(entry.owners).reverse()){const owner=forgeMessageStore.owners.get(id),parent=owner?.marker.current?.parentElement;if(parent&&parent.getBoundingClientRect().width>0)return id}}return null}
function ForgeFallbackMessage({children,tone='info',onClose,duration,notificationKey}){
 const id=React.useId(),marker=React.useRef(null),content=React.useRef({children,tone,onClose});content.current={children,tone,onClose};const text=forgeMessageText(children).trim(),key=tone+':'+(notificationKey||text),lifetime=duration===0?Infinity:duration??(tone==='error'?6000:tone==='warning'?5000:tone==='success'?3000:4000);
 React.useSyncExternalStore(forgeMessageSubscribe,forgeMessageSnapshot,()=>0);
 React.useEffect(()=>{if(!text)return;forgeMessageRegister(id,key,content,lifetime,marker);return()=>forgeMessageUnregister(id)},[id,key,lifetime]);
 return <><span ref={marker} hidden aria-hidden="true" data-fp-message-source="true"/>{forgeMessageHostOwner()===id&&<ForgeMessageHost/>}</>
}
function ForgeMessageHost(){
 const popup=React.useRef(null),messages=Array.from(forgeMessageStore.entries.values()).slice(-3);
 React.useLayoutEffect(()=>{const panel=popup.current;if(!panel||!messages.length)return;const focused=document.activeElement;if(typeof panel.showPopover==='function'&&!panel.matches(':popover-open'))panel.showPopover();if(focused instanceof HTMLElement&&focused.isConnected&&document.activeElement!==focused)focused.focus({preventScroll:true});return()=>{if(typeof panel.hidePopover==='function'&&panel.matches(':popover-open'))panel.hidePopover()}},[messages.length>0]);
 if(!messages.length)return null;
 return <div ref={popup} className="fp-message-region" role="region" aria-label="消息提示" popover="manual" data-open="true">{messages.map(entry=>{const owner=Array.from(entry.owners).reverse().map(id=>forgeMessageStore.owners.get(id)).find(Boolean);if(!owner)return null;const {children,tone}=owner.content.current;return <div key={entry.key} className="fp-message-tip" data-tone={tone} role={tone==='error'?'alert':'status'} aria-live={tone==='error'?'assertive':'polite'} onMouseEnter={()=>forgeMessagePause(entry.key)} onMouseLeave={event=>{if(!event.currentTarget.contains(document.activeElement))forgeMessageResume(entry.key)}} onFocusCapture={()=>forgeMessagePause(entry.key)} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget)&&!event.currentTarget.matches(':hover'))forgeMessageResume(entry.key)}}><span className="fp-message-icon"><ForgeIcon name={tone==='error'?'circle-x':tone==='warning'?'triangle-alert':tone==='success'?'circle-check':'info'}/></span><div className="fp-message-content">{children}</div><ForgeButton type="button" className="fp-message-close" aria-label="关闭提示" onClick={()=>forgeMessageDismiss(entry.key)}><ForgeIcon name="close"/></ForgeButton></div>})}</div>
}
`;
