import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
.sales-contacts .fp-shell{width:min(1500px,100%);padding-top:20px}.sales-contacts .fp-table{min-width:1160px}.sales-contacts .fp-metrics{grid-template-columns:repeat(4,minmax(0,1fr))}
.sales-contacts .contact-cell{display:flex;align-items:center;gap:10px}.sales-contacts .contact-avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:var(--fp-soft);font-weight:700}
.sales-contacts .kp{display:inline-flex;margin-left:6px;padding:2px 6px;border-radius:999px;background:#fff1d6;color:#925d00;font-size:11px}.sales-contacts .channel{display:block;white-space:nowrap}
.sales-contacts.compact .fp-table th,.sales-contacts.compact .fp-table td{padding-top:7px;padding-bottom:7px}.sales-contacts .contact-filters{display:grid;grid-template-columns:minmax(280px,1.4fr) minmax(180px,.8fr) minmax(180px,.8fr) auto;gap:8px;align-items:center;padding:12px 16px}.sales-contacts .contact-filters>*{min-width:0}.sales-contacts .contact-filters .fp-input,.sales-contacts .contact-filters .fp-picker-trigger,.sales-contacts .contact-filters .fp-button{height:32px;min-height:32px}.sales-contacts .contact-filter-actions{display:flex;align-items:center;justify-content:flex-end;gap:8px;white-space:nowrap}.sales-contacts .transfer-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sales-contacts .transfer-actions .fp-button{justify-content:flex-start}
.sales-contacts .channel-row{display:grid;grid-template-columns:130px 1fr 1.4fr auto auto;gap:8px;align-items:end;margin-bottom:10px}.sales-contacts .channel-primary{color:var(--fp-warning);font-weight:650}
.sales-contacts .channel-row .fp-picker{min-width:0;width:100%}.sales-contacts .channel-row .fp-picker-trigger{width:100%}
.sales-contacts .fp-modal{width:min(900px,calc(100vw - 32px))}.sales-contacts .fp-modal-body{max-height:72vh;overflow:auto}.sales-contacts .form-section{margin-bottom:18px;padding:14px;border:1px solid var(--fp-line);border-radius:12px}.sales-contacts .form-title{font-weight:700;margin-bottom:12px}
@media(max-width:1200px){.sales-contacts .fp-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.sales-contacts .contact-filters{grid-template-columns:repeat(3,minmax(0,1fr))}.sales-contacts .contact-filters .fp-search{grid-column:1/-1}}
@media(max-width:760px){.sales-contacts .channel-row{grid-template-columns:1fr}.sales-contacts .fp-shell{padding-top:10px}.sales-contacts .contact-filters{grid-template-columns:1fr 1fr}.sales-contacts .contact-filters .fp-search,.sales-contacts .contact-filter-actions{grid-column:1/-1}.sales-contacts .contact-filter-actions{justify-content:flex-start}.sales-contacts .transfer-actions{grid-template-columns:1fr}}
@media(max-width:520px){.sales-contacts .fp-metrics,.sales-contacts .contact-filters{grid-template-columns:1fr}.sales-contacts .contact-filters .fp-search{grid-column:auto}}
`;

const source = `
const css=${JSON.stringify(css)},statusText={active:'在职',transferred:'已跳槽',resigned:'已离职',retired:'已退休',inactive:'停用'},channelText={mobile:'手机',telephone:'座机',email:'邮箱',wechat:'微信',dingtalk:'钉钉',qq:'QQ',linkedin:'LinkedIn',other:'其他'},channelOptions=Object.entries(channelText),weights=['价格','交期','质量','服务','品牌','付款条件'];
function App(){
 const adapter=useAdapter();
 const [state,setState]=React.useState({loading:true,contacts:[],channels:[],customers:[],users:[],error:''}),[tab,setTab]=React.useState('all'),[q,setQ]=React.useState(''),[job,setJob]=React.useState(''),[owner,setOwner]=React.useState('all'),[compact,setCompact]=React.useState(false),[page,setPage]=React.useState(1),[dialog,setDialog]=React.useState(null),[transferOpen,setTransferOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
 async function request(path,options={}){const headers={'Content-Type':'application/json',...(adapter?.getAuthHeaders?.()||{}),...(options.headers||{})},raw=String(adapter?.baseUrl||''),base=raw.endsWith('/')?raw.slice(0,-1):raw,transport=adapter?.fetchImpl||fetch,response=await transport(base+'/api/v1'+path,{credentials:'include',...options,headers}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error((typeof payload.error==='string'?payload.error:payload.error?.message)||(Array.isArray(payload.fields)&&payload.fields.length?payload.fields.map(f=>f.message||f.label).filter(Boolean).join('；'):'')||payload.message||'请求失败');return payload}
 const rows=p=>p?.records||p?.data?.records||p?.data||[],result=p=>p?.record||p?.data?.record||p?.data||p;
 async function find(name){try{return rows(await request('/data/'+name+'?$top=500'))}catch{return[]}}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const [contacts,channels,customers,users]=await Promise.all(['forge_contact','forge_contact_channel','forge_customer','sys_user'].map(find));setState({loading:false,contacts,channels,customers,users,error:''})}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}))}}
 React.useEffect(()=>{load()},[]);
 const customer=id=>state.customers.find(x=>x.id===id)?.name||'—',user=id=>{const r=state.users.find(x=>x.id===id);return r?.name||r?.display_name||r?.email||'—'},current=state.users.find(x=>String(x.name||'').includes('Dev'))||state.users[0]||{},channelsOf=id=>state.channels.filter(x=>x.contact_id===id),isKp=r=>['价格','交期','质量','服务','品牌','付款条件'].includes(r.decision_weight),status=r=>r.employment_status||'active';
 const counts={all:state.contacts.length,active:state.contacts.filter(x=>status(x)==='active').length,transferred:state.contacts.filter(x=>status(x)==='transferred').length,resigned:state.contacts.filter(x=>status(x)==='resigned').length,retired:state.contacts.filter(x=>status(x)==='retired').length,inactive:state.contacts.filter(x=>status(x)==='inactive').length},filtered=state.contacts.filter(r=>(tab==='all'||status(r)===tab)&&(owner==='all'||r.responsible_id===owner)&&(!job.trim()||[r.job_title,r.department].join(' ').toLowerCase().includes(job.trim().toLowerCase()))&&(!q.trim()||[r.name,customer(r.customer_id),r.job_title,r.department,...channelsOf(r.id).map(x=>x.value)].join(' ').toLowerCase().includes(q.trim().toLowerCase()))).sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))),pageCount=Math.max(1,Math.ceil(filtered.length/20)),safePage=Math.min(page,pageCount),visible=filtered.slice((safePage-1)*20,safePage*20);
 const blankChannels=()=>[{channel_type:'mobile',name:'工作手机',value:'',is_primary:true},{channel_type:'telephone',name:'办公座机',value:'',is_primary:false},{channel_type:'email',name:'工作邮箱',value:'',is_primary:false}];
 function openCreate(){setDialog({kind:'edit',id:'',name:'',gender:'',customer_id:state.customers[0]?.id||'',department:'',job_title:'',decision_weight:'价格',responsible_id:current.id||'',employment_status:'active',is_primary:false,remarks:'',channels:blankChannels(),error:''})}
 function openEdit(row){const cs=channelsOf(row.id);setDialog({kind:'edit',id:row.id,name:row.name||'',gender:row.gender||'',customer_id:row.customer_id||'',department:row.department||'',job_title:row.job_title||'',decision_weight:row.decision_weight||'价格',responsible_id:row.responsible_id||current.id||'',employment_status:status(row),is_primary:!!row.is_primary,remarks:row.remarks||'',channels:cs.length?cs.map(x=>({id:x.id,channel_type:x.channel_type,name:x.name,value:x.value,is_primary:!!x.is_primary})):blankChannels(),error:''})}
 function patch(key,value){setDialog(d=>({...d,[key]:value}))}function patchChannel(i,key,value){setDialog(d=>({...d,channels:d.channels.map((x,n)=>n===i?{...x,[key]:value,...(key==='is_primary'&&value?{}:{})}:key==='is_primary'&&value?{...x,is_primary:false}:x)}))}
 async function save(){if(!dialog.name.trim()||!dialog.customer_id||!dialog.responsible_id)return setDialog(d=>({...d,error:'请填写姓名，并选择所属客户和维护人'}));const entered=dialog.channels.filter(x=>x.value.trim());if(entered.some(x=>!x.name.trim()))return setDialog(d=>({...d,error:'已填写的联系方式必须填写标签'}));setBusy(true);try{const payload={name:dialog.name.trim(),gender:dialog.gender||null,customer_id:dialog.customer_id,department:dialog.department||null,job_title:dialog.job_title||null,decision_weight:dialog.decision_weight||null,responsible_id:dialog.responsible_id,employment_status:dialog.employment_status,is_primary:!!dialog.is_primary,remarks:dialog.remarks||null},saved=result(await request('/data/forge_contact'+(dialog.id?'/'+dialog.id:''),{method:dialog.id?'PATCH':'POST',body:JSON.stringify(payload)})),contactId=dialog.id||saved.id;if(!contactId)throw new Error('联系人保存后未返回记录ID');if(dialog.id)for(const old of channelsOf(dialog.id))await request('/data/forge_contact_channel/'+old.id,{method:'DELETE'});const normalized=entered.map((x,i)=>({...x,is_primary:entered.some(y=>y.is_primary)?!!x.is_primary:i===0}));for(const x of normalized)await request('/data/forge_contact_channel',{method:'POST',body:JSON.stringify({name:x.name.trim(),contact_id:contactId,channel_type:x.channel_type,value:x.value.trim(),is_primary:x.is_primary})});setDialog(null);setToast(dialog.id?'联系人修改已保存':'联系人已创建');setPage(1);await load()}catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}finally{setBusy(false)}}
 async function remove(){const row=dialog.row;setBusy(true);try{for(const x of channelsOf(row.id))await request('/data/forge_contact_channel/'+x.id,{method:'DELETE'});await request('/data/forge_contact/'+row.id,{method:'DELETE'});setDialog(null);setToast('联系人已删除');await load()}catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}finally{setBusy(false)}}
 function exportCsv(mode){const exportRows=mode==='page'?visible:filtered,headers=['联系人','性别','职位','部门','所属公司','任职状态','决策权重','联系方式','维护人'],quote=String.fromCharCode(34),newline=String.fromCharCode(10),csv=[headers,...exportRows.map(r=>[r.name,r.gender||'',r.job_title||'',r.department||'',customer(r.customer_id),statusText[status(r)]||status(r),r.decision_weight||'',channelsOf(r.id).map(x=>x.name+'：'+x.value).join('；'),user(r.responsible_id)])].map(line=>line.map(value=>quote+String(value??'').split(quote).join(quote+quote)+quote).join(',')).join(newline),url=URL.createObjectURL(new Blob([String.fromCharCode(65279)+csv],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download='联系人管理-'+new Date().toISOString().slice(0,10)+'.csv';anchor.click();URL.revokeObjectURL(url);setTransferOpen(false);setToast('已导出 '+exportRows.length+' 条联系人记录')}
 if(state.loading)return <div className="forge-product sales-contacts"><style>{css}</style><div className="fp-shell"><ForgeLoading label="正在加载联系人管理"/></div></div>;
 return <div className={'forge-product sales-contacts '+(compact?'compact':'')}><style>{css}</style><div className="fp-shell"><ForgePageHeader section="CRM客户管理 / 联系人管理" title="联系人管理" description="以人为中心管理客户联系人，持续跟踪任职变化和全部联系方式。" actions={<><button className="fp-button primary" onClick={openCreate}>＋ 新增联系人</button><button className="fp-button" onClick={()=>setTransferOpen(true)}>⇅ 导入/导出⌄</button></>}/>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<ForgeNotice tone="success" onClose={()=>setToast('')}>{toast}</ForgeNotice>}
 <div className="fp-metrics"><div className="fp-metric"><div className="fp-metric-label">联系人总数</div><div className="fp-metric-value">{counts.all}</div></div><div className="fp-metric"><div className="fp-metric-label">在职</div><div className="fp-metric-value">{counts.active}</div></div><div className="fp-metric"><div className="fp-metric-label">不在原公司</div><div className="fp-metric-value">{counts.transferred+counts.resigned+counts.retired}</div></div><div className="fp-metric"><div className="fp-metric-label">关键决策人 KP</div><div className="fp-metric-value">{state.contacts.filter(isKp).length}</div></div></div>
 <section className="fp-card"><div className="fp-tabs">{[['all','全部'],['active','在职'],['transferred','已跳槽'],['resigned','已离职'],['retired','已退休'],['inactive','停用']].map(([v,l])=><button key={v} className={'fp-tab '+(tab===v?'active':'')} onClick={()=>{setTab(v);setPage(1)}}>{l} {counts[v]}</button>)}</div><div className="contact-filters"><input className="fp-input fp-search" aria-label="搜索联系人" placeholder="搜索姓名、公司、电话、邮箱" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><input className="fp-input" aria-label="按职务筛选联系人" placeholder="筛选职务" value={job} onChange={e=>{setJob(e.target.value);setPage(1)}}/><ForgeSelectControl aria-label="维护人" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="all">全部维护人</option>{state.users.map(x=><option value={x.id} key={x.id}>{user(x.id)}</option>)}</ForgeSelectControl><div className="contact-filter-actions"><button className="fp-button" onClick={()=>{setQ('');setJob('');setOwner('all');setPage(1)}}>清空筛选</button><button className="fp-icon-button" aria-label="刷新联系人数据" title="刷新联系人数据" onClick={load}>↻</button><button className="fp-icon-button" aria-label={compact?'切换为标准行高':'切换为紧凑行高'} title={compact?'切换为标准行高':'切换为紧凑行高'} onClick={()=>setCompact(value=>!value)}>≡</button><ForgeListSettings/></div></div>
 <div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>联系人</th><th>性别</th><th>职位 / 部门</th><th>所属公司</th><th>任职状态</th><th>决策权重</th><th>联系方式</th><th>维护人</th><th>操作</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="contact-cell"><span className="contact-avatar">{String(r.name||'联').slice(0,1)}</span><div><strong>{r.name}</strong>{isKp(r)&&<span className="kp">KP</span>}{r.is_primary&&<div className="fp-secondary">主要联系人</div>}</div></div></td><td>{r.gender||'—'}</td><td>{r.job_title||'—'}<div className="fp-secondary">{r.department||'—'}</div></td><td>{customer(r.customer_id)}</td><td><ForgeStatus value={status(r)} label={statusText[status(r)]}/></td><td>{r.decision_weight||'—'}</td><td>{channelsOf(r.id).map(x=><span className="channel" key={x.id}>{x.is_primary?'★ ':''}{x.value}</span>)}{!channelsOf(r.id).length&&'—'}</td><td>{user(r.responsible_id)}</td><td><div className="fp-toolbar"><button className="fp-button small" onClick={()=>openEdit(r)}>编辑</button><button className="fp-button small danger" onClick={()=>setDialog({kind:'delete',row:r,error:''})}>删除</button></div></td></tr>)}{!visible.length&&<tr><td colSpan="9" className="fp-empty-cell"><ForgeEmpty title="暂无联系人" description="新增联系人后，可按任职状态、职务和维护人持续管理。" action={<button className="fp-button primary" onClick={openCreate}>新增联系人</button>}/></td></tr>}</tbody></table></div><div className="fp-pagination"><span>共 {filtered.length} 条记录</span><span>每页 20 条</span><button className="fp-button small" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>上一页</button><span>{safePage} / {pageCount}</span><button className="fp-button small" disabled={safePage>=pageCount} onClick={()=>setPage(x=>Math.min(pageCount,x+1))}>下一页</button></div></section></div>
 <ForgeDialog open={dialog?.kind==='edit'} title={dialog?.id?'编辑联系人':'新增联系人'} subtitle="客户关系档案 · CRM" error={dialog?.error} busy={busy} confirmLabel={dialog?.id?'保存修改':'保存联系人'} onCancel={()=>!busy&&setDialog(null)} onConfirm={save}><section className="form-section"><div className="form-title">01 任职资料 · * 必填</div><div className="fp-detail-grid"><div className="fp-field"><label>姓名 *</label><input className="fp-input" value={dialog?.name||''} onChange={e=>patch('name',e.target.value)}/></div><div className="fp-field"><label>性别</label><ForgeSelectControl value={dialog?.gender||''} onChange={e=>patch('gender',e.target.value)}><option value="">请选择性别</option><option value="男">男</option><option value="女">女</option></ForgeSelectControl></div><div className="fp-field"><label>所属客户 *</label><ForgeSelectControl value={dialog?.customer_id||''} onChange={e=>patch('customer_id',e.target.value)}><option value="">请选择客户</option>{state.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>部门</label><input className="fp-input" value={dialog?.department||''} onChange={e=>patch('department',e.target.value)}/></div><div className="fp-field"><label>职位</label><input className="fp-input" value={dialog?.job_title||''} onChange={e=>patch('job_title',e.target.value)}/></div><div className="fp-field"><label>决策权重</label><ForgeSelectControl value={dialog?.decision_weight||'价格'} onChange={e=>patch('decision_weight',e.target.value)}>{weights.map(x=><option value={x} key={x}>{x}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>维护人 *</label><ForgeSelectControl value={dialog?.responsible_id||''} onChange={e=>patch('responsible_id',e.target.value)}><option value="">请选择维护人</option>{state.users.map(x=><option key={x.id} value={x.id}>{user(x.id)}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>任职状态</label><ForgeSelectControl value={dialog?.employment_status||'active'} onChange={e=>patch('employment_status',e.target.value)}>{Object.entries(statusText).map(([v,l])=><option key={v} value={v}>{l}</option>)}</ForgeSelectControl></div><div className="fp-field fp-span-2"><label><input type="checkbox" checked={!!dialog?.is_primary} onChange={e=>patch('is_primary',e.target.checked)}/> 设为该客户的主要联系人</label></div></div></section>
 <section className="form-section"><div className="form-title">02 联系方式 · 星标表示主要联系方式</div>{dialog?.channels.map((x,i)=><div className="channel-row" key={i}><div className="fp-field"><label>类型</label><ForgeSelectControl value={x.channel_type} onChange={e=>patchChannel(i,'channel_type',e.target.value)}>{channelOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>标签</label><input className="fp-input" value={x.name} onChange={e=>patchChannel(i,'name',e.target.value)}/></div><div className="fp-field"><label>联系方式</label><input className="fp-input" value={x.value} onChange={e=>patchChannel(i,'value',e.target.value)}/></div><button className={'fp-button small '+(x.is_primary?'channel-primary':'')} onClick={()=>patchChannel(i,'is_primary',true)}>{x.is_primary?'★ 主要':'设为主要'}</button><button className="fp-button small" onClick={()=>setDialog(d=>({...d,channels:d.channels.filter((_,n)=>n!==i)}))}>移除</button></div>)}<button className="fp-button" onClick={()=>setDialog(d=>({...d,channels:[...d.channels,{channel_type:'mobile',name:'工作手机',value:'',is_primary:false}]}))}>添加联系方式</button></section>
 <section className="form-section"><div className="form-title">03 补充说明</div><div className="fp-field"><label>备注</label><textarea className="fp-textarea" value={dialog?.remarks||''} onChange={e=>patch('remarks',e.target.value)}/></div></section></ForgeDialog>
 <ForgeDialog open={dialog?.kind==='delete'} title="确认删除联系人" subtitle={dialog?.row?.name} error={dialog?.error} busy={busy} danger confirmLabel="确认删除" onCancel={()=>!busy&&setDialog(null)} onConfirm={remove}><div className="fp-dialog-impact">删除后将同时移除该联系人的全部联系方式，且无法恢复；所属客户档案不会被删除。</div></ForgeDialog>
 <ForgeDialog open={transferOpen} title="导入 / 导出联系人" subtitle="联系人档案的数据交换" confirmLabel="关闭" onCancel={()=>setTransferOpen(false)} onConfirm={()=>setTransferOpen(false)}><div className="transfer-actions"><button className="fp-button" onClick={()=>location.href='/_console/apps/com.inoforge.forge.sales/forge_contact'}>批量导入 · 前往联系人台账</button><button className="fp-button" disabled={!visible.length} onClick={()=>exportCsv('page')}>导出当前页</button><button className="fp-button" disabled={!filtered.length} onClick={()=>exportCsv('all')}>导出全部筛选结果</button></div><ForgeNotice tone="info">自定义导出与批量任务尚未形成可回读的任务中心，不显示为可点击动作。</ForgeNotice></ForgeDialog>
 </div>}
export default App;${forgeProductUiRuntime}`;

export const SalesContactsPage={name:'page_sales_contacts',label:'联系人管理',description:'以人为中心管理客户联系人，持续跟踪任职变化和全部联系方式',icon:'contact',type:'app' as const,kind:'react' as const,source};
