import { defineAction } from '@objectstack/spec/ui';

const locations = ['record_header', 'record_more'] as const;

export const FundAccountCreateFinancialPeriod = defineAction({
  name: 'fund_account_create_financial_period', label: '创建财务期间', objectName: 'forge_fund_account', icon: 'calendar-plus', locations: [...locations], order: 25, visible: `record.status == 'active'`, refreshAfter: true,
  params: [{ field: 'code', objectOverride: 'forge_financial_period', required: true }, { field: 'name', objectOverride: 'forge_financial_period', required: true }, { field: 'period_start', objectOverride: 'forge_financial_period', required: true }, { field: 'period_end', objectOverride: 'forge_financial_period', required: true }, { field: 'remarks', objectOverride: 'forge_financial_period' }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const accountId=ctx.recordId||(ctx.record&&ctx.record.id),account=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!accountId||!account)throw new Error('资金账户不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(account.status!=='active')throw new Error('仅启用账户可以创建财务期间');const start=String(ctx.input.period_start||''),end=String(ctx.input.period_end||'');if(!start||!end||end<start)throw new Error('期间结束日期不得早于开始日期');if(start<String(account.opening_on||''))throw new Error('期间不得早于账户期初日期');const periods=await ctx.api.object('forge_financial_period').find({where:{account_id:accountId}});if(periods.some(x=>start<=String(x.period_end)&&end>=String(x.period_start)))throw new Error('当前账户已存在重叠财务期间');const now=new Date().toISOString(),created=await ctx.api.object('forge_financial_period').insert({name:ctx.input.name,code:ctx.input.code,account_id:accountId,period_start:start,period_end:end,status:'open',transaction_count:0,incomplete_count:0,responsible_id:account.responsible_id,remarks:ctx.input.remarks||null}),periodId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));if(!periodId)throw new Error('财务期间创建后未返回ID');await ctx.api.object('forge_financial_period_log').insert({name:ctx.input.code+' 创建',event_key:ctx.input.code+'-CREATED',period_id:periodId,action:'created',from_status:null,to_status:'open',comment:ctx.input.remarks||'创建财务期间',occurred_at:now,operator_id:actor});return{id:periodId,account_id:accountId,status:'open'};
` },
});

export const FinancialPeriodLock = defineAction({
  name: 'financial_period_lock', label: '锁定期间', objectName: 'forge_financial_period', icon: 'lock', locations: [...locations], order: 20, visible: `record.status == 'open'`, refreshAfter: true,
  params: [{ name: 'comment', label: '锁定说明', type: 'textarea', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),period=ctx.record,actor=ctx.session&&ctx.session.userId,comment=String(ctx.input.comment||'').trim();if(ctx.recordLoadDenied===true||!id||!period)throw new Error('财务期间不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(period.status!=='open')throw new Error('仅开放期间可以锁定');if(!comment)throw new Error('锁定说明不能为空');const all=await ctx.api.object('forge_bank_transaction').find({where:{account_id:period.account_id}}),lines=all.filter(x=>String(x.transacted_at||'').slice(0,10)>=period.period_start&&String(x.transacted_at||'').slice(0,10)<=period.period_end&&x.status!=='voided'),incomplete=lines.filter(x=>x.status!=='matched');if(incomplete.length)throw new Error('期间仍有未完成勾兑的银行流水，不能锁定');const now=new Date().toISOString();await ctx.api.object('forge_financial_period').update({id,status:'locked',transaction_count:lines.length,incomplete_count:0,locked_by:actor,locked_at:now});await ctx.api.object('forge_financial_period_log').insert({name:period.code+' 锁定',event_key:period.code+'-LOCK-'+now,period_id:id,action:'locked',from_status:'open',to_status:'locked',comment,occurred_at:now,operator_id:actor});return{id,status:'locked',transaction_count:lines.length};
` },
});

export const FinancialPeriodClose = defineAction({
  name: 'financial_period_close', label: '关闭期间', objectName: 'forge_financial_period', icon: 'archive', locations: [...locations], order: 30, visible: `record.status == 'locked'`, refreshAfter: true,
  params: [{ name: 'comment', label: '关闭说明', type: 'textarea', required: true }],
  body: { language: 'js', capabilities: ['api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),period=ctx.record,actor=ctx.session&&ctx.session.userId,comment=String(ctx.input.comment||'').trim();if(ctx.recordLoadDenied===true||!id||!period)throw new Error('财务期间不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(period.status!=='locked')throw new Error('仅锁定期间可以关闭');if(!comment)throw new Error('关闭说明不能为空');const now=new Date().toISOString();await ctx.api.object('forge_financial_period').update({id,status:'closed',closed_by:actor,closed_at:now});await ctx.api.object('forge_financial_period_log').insert({name:period.code+' 关闭',event_key:period.code+'-CLOSE-'+now,period_id:id,action:'closed',from_status:'locked',to_status:'closed',comment,occurred_at:now,operator_id:actor});return{id,status:'closed'};
` },
});

export const FinancialPeriodReopen = defineAction({
  name: 'financial_period_reopen', label: '重新开放', objectName: 'forge_financial_period', icon: 'lock-open', locations: [...locations], order: 40, visible: `record.status == 'locked' || record.status == 'closed'`, refreshAfter: true,
  params: [{ field: 'reopen_reason', objectOverride: 'forge_financial_period', required: true }],
  body: { language: 'js', capabilities: ['api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),period=ctx.record,actor=ctx.session&&ctx.session.userId,reason=String(ctx.input.reopen_reason||'').trim();if(ctx.recordLoadDenied===true||!id||!period)throw new Error('财务期间不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(!['locked','closed'].includes(period.status))throw new Error('仅锁定或关闭期间可以重新开放');if(!reason)throw new Error('重新开放原因不能为空');const now=new Date().toISOString(),from=period.status;await ctx.api.object('forge_financial_period').update({id,status:'open',reopened_by:actor,reopened_at:now,reopen_reason:reason});await ctx.api.object('forge_financial_period_log').insert({name:period.code+' 重新开放',event_key:period.code+'-REOPEN-'+now,period_id:id,action:'reopened',from_status:from,to_status:'open',comment:reason,occurred_at:now,operator_id:actor});return{id,status:'open',from_status:from};
` },
});

export const FundAccountRegisterBankTransaction = defineAction({
  name: 'fund_account_register_bank_transaction', label: '登记银行流水', objectName: 'forge_fund_account', icon: 'landmark', locations: [...locations], order: 30, visible: `record.status == 'active'`, refreshAfter: true,
  description: '登记银行侧证据，不改变账面资金余额。', successMessage: '银行流水已登记',
  params: [{ field: 'code', objectOverride: 'forge_bank_transaction', required: true }, { field: 'transacted_at', objectOverride: 'forge_bank_transaction', required: true }, { field: 'direction', objectOverride: 'forge_bank_transaction', required: true }, { field: 'flow_type', objectOverride: 'forge_bank_transaction', required: true }, { field: 'counterparty_name', objectOverride: 'forge_bank_transaction' }, { field: 'amount', objectOverride: 'forge_bank_transaction', required: true }, { field: 'bank_reference', objectOverride: 'forge_bank_transaction' }, { field: 'remarks', objectOverride: 'forge_bank_transaction' }],
  onSuccess: { navigate: '/_console/apps/forge/page/page_bank_flow?transaction=${result.id}' },
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const accountId=ctx.recordId||(ctx.record&&ctx.record.id),account=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!accountId||!account)throw new Error('资金账户不存在或不可访问');if(!actor)throw new Error('无法识别当前登记人');if(account.status!=='active')throw new Error('仅启用账户可以登记流水');const direction=String(ctx.input.direction||''),amount=Math.round((Number(ctx.input.amount||0)+Number.EPSILON)*10000)/10000,at=String(ctx.input.transacted_at||''),day=at.slice(0,10),ref=String(ctx.input.bank_reference||'').trim();if(!['income','expense'].includes(direction))throw new Error('收支方向无效');if(!(amount>0))throw new Error('流水金额必须大于0');if(!day||day<String(account.opening_on||''))throw new Error('交易时间不得早于账户期初日期');const periods=await ctx.api.object('forge_financial_period').find({where:{account_id:accountId}});if(periods.length&&!periods.some(x=>x.status==='open'&&day>=x.period_start&&day<=x.period_end))throw new Error('交易日期不在开放财务期间内');if(ref){const duplicates=await ctx.api.object('forge_bank_transaction').find({where:{account_id:accountId,bank_reference:ref}});if(duplicates.some(x=>x.status!=='voided'))throw new Error('同一账户已存在相同银行参考号');}const now=new Date().toISOString(),created=await ctx.api.object('forge_bank_transaction').insert({name:ctx.input.code+' '+(direction==='income'?'收入':'支出'),code:ctx.input.code,account_id:accountId,transacted_at:at,direction,flow_type:ctx.input.flow_type||'other',counterparty_name:ctx.input.counterparty_name||null,amount,matched_amount:0,difference_amount:amount,status:'unmatched',source:'manual',source_batch_key:null,source_row_key:null,bank_reference:ref||null,created_by:actor,responsible_id:account.responsible_id,remarks:ctx.input.remarks||null}),transactionId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));if(!transactionId)throw new Error('银行流水创建后未返回ID');await ctx.api.object('forge_bank_transaction_log').insert({name:ctx.input.code+' 登记',event_key:ctx.input.code+'-REGISTER',transaction_id:transactionId,match_id:null,action:'registered',amount,from_status:null,to_status:'unmatched',comment:ctx.input.remarks||'登记银行侧证据',occurred_at:now,operator_id:actor});return{id:transactionId,account_id:accountId,status:'unmatched',book_balance_unchanged:true};
` },
});

export const BankTransactionPrepareMatch = defineAction({
  name: 'bank_transaction_prepare_match', label: '发起勾兑', objectName: 'forge_bank_transaction', icon: 'link', locations: [...locations], order: 20, visible: `record.status == 'unmatched'`, refreshAfter: true,
  params: [{ field: 'code', objectOverride: 'forge_bank_transaction_match', required: true }, { field: 'receipt_id', objectOverride: 'forge_bank_transaction_match' }, { field: 'payment_id', objectOverride: 'forge_bank_transaction_match' }, { field: 'matched_on', objectOverride: 'forge_bank_transaction_match', required: true }, { field: 'remarks', objectOverride: 'forge_bank_transaction_match' }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),tx=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!id||!tx)throw new Error('银行流水不存在或不可访问');if(!actor)throw new Error('无法识别当前勾兑人');if(tx.status!=='unmatched')throw new Error('仅未勾兑流水可以发起勾兑');const receiptId=ctx.input.receipt_id||null,paymentId=ctx.input.payment_id||null;if(tx.direction==='income'&&(!receiptId||paymentId))throw new Error('收入流水必须且只能选择一笔账面收款');if(tx.direction==='expense'&&(!paymentId||receiptId))throw new Error('支出流水必须且只能选择一笔账面付款');const objectName=tx.direction==='income'?'forge_cash_receipt':'forge_cash_payment',bookId=tx.direction==='income'?receiptId:paymentId,book=await ctx.api.object(objectName).findOne({where:{id:bookId}});if(!book||book.account_id!==tx.account_id||book.status==='reversed')throw new Error('账面收付款不存在、已撤销或资金账户不一致');const peers=await ctx.api.object('forge_bank_transaction_match').find({where:tx.direction==='income'?{receipt_id:bookId}:{payment_id:bookId}});if(peers.some(x=>['pending_review','discrepancy','approved'].includes(x.status)))throw new Error('该账面收付款已有有效勾兑');const bankAmount=Math.round((Number(tx.amount||0)+Number.EPSILON)*10000)/10000,bookAmount=Math.round((Number(book.amount||0)+Number.EPSILON)*10000)/10000,difference=Math.round((bankAmount-bookAmount+Number.EPSILON)*10000)/10000,status=Math.abs(difference)<0.0001?'pending_review':'discrepancy',now=new Date().toISOString(),created=await ctx.api.object('forge_bank_transaction_match').insert({name:tx.code+' 勾兑 '+book.code,code:ctx.input.code,transaction_id:id,direction:tx.direction,receipt_id:receiptId,payment_id:paymentId,bank_amount:bankAmount,book_amount:bookAmount,difference_amount:difference,matched_on:ctx.input.matched_on,status,matched_by:actor,responsible_id:tx.responsible_id,remarks:ctx.input.remarks||null}),matchId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));if(!matchId)throw new Error('勾兑记录创建后未返回ID');await ctx.api.object('forge_bank_transaction').update({id,matched_amount:bookAmount,difference_amount:difference,status});await ctx.api.object('forge_bank_transaction_log').insert({name:ctx.input.code+' 发起',event_key:ctx.input.code+'-MATCH',transaction_id:id,match_id:matchId,action:'matched',amount:bookAmount,from_status:'unmatched',to_status:status,comment:ctx.input.remarks||'关联既有账面收付款',occurred_at:now,operator_id:actor});return{id:matchId,transaction_id:id,status,bank_amount:bankAmount,book_amount:bookAmount,difference_amount:difference};
` },
});

export const BankTransactionMatchApprove = defineAction({
  name: 'bank_transaction_match_approve', label: '审核勾兑', objectName: 'forge_bank_transaction_match', icon: 'badge-check', locations: [...locations], order: 20, visible: `record.status == 'pending_review'`, refreshAfter: true,
  params: [{ field: 'review_comment', objectOverride: 'forge_bank_transaction_match', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),match=ctx.record,actor=ctx.session&&ctx.session.userId,comment=String(ctx.input.review_comment||'').trim();if(ctx.recordLoadDenied===true||!id||!match)throw new Error('勾兑记录不存在或不可访问');if(!actor)throw new Error('无法识别当前审核人');if(match.status!=='pending_review'||Math.abs(Number(match.difference_amount||0))>=0.0001)throw new Error('仅无差额的待审核勾兑可以审核');if(!comment)throw new Error('审核意见不能为空');const tx=await ctx.api.object('forge_bank_transaction').findOne({where:{id:match.transaction_id}});if(!tx||tx.status!=='pending_review')throw new Error('关联银行流水状态已变化');const now=new Date().toISOString();await ctx.api.object('forge_bank_transaction_match').update({id,status:'approved',reviewed_by:actor,reviewed_at:now,review_comment:comment});await ctx.api.object('forge_bank_transaction').update({id:tx.id,status:'matched'});await ctx.api.object('forge_bank_transaction_log').insert({name:match.code+' 审核',event_key:match.code+'-APPROVE',transaction_id:tx.id,match_id:id,action:'approved',amount:match.book_amount,from_status:'pending_review',to_status:'matched',comment,occurred_at:now,operator_id:actor});return{id,transaction_id:tx.id,status:'approved',transaction_status:'matched',book_balance_unchanged:true};
` },
});

export const BankTransactionMatchCancel = defineAction({
  name: 'bank_transaction_match_cancel', label: '取消勾兑', objectName: 'forge_bank_transaction_match', icon: 'x', locations: [...locations], order: 30, visible: `record.status == 'pending_review' || record.status == 'discrepancy'`, refreshAfter: true,
  params: [{ field: 'reversal_reason', objectOverride: 'forge_bank_transaction_match', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),match=ctx.record,actor=ctx.session&&ctx.session.userId,reason=String(ctx.input.reversal_reason||'').trim();if(ctx.recordLoadDenied===true||!id||!match)throw new Error('勾兑记录不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(!['pending_review','discrepancy'].includes(match.status))throw new Error('仅待审核或有差异勾兑可以取消');if(!reason)throw new Error('取消原因不能为空');const tx=await ctx.api.object('forge_bank_transaction').findOne({where:{id:match.transaction_id}});if(!tx||!['pending_review','discrepancy'].includes(tx.status))throw new Error('关联银行流水状态已变化');const now=new Date().toISOString();await ctx.api.object('forge_bank_transaction_match').update({id,status:'cancelled',reversed_by:actor,reversed_at:now,reversal_reason:reason});await ctx.api.object('forge_bank_transaction').update({id:tx.id,matched_amount:0,difference_amount:tx.amount,status:'unmatched'});await ctx.api.object('forge_bank_transaction_log').insert({name:match.code+' 取消',event_key:match.code+'-CANCEL',transaction_id:tx.id,match_id:id,action:'cancelled',amount:match.book_amount,from_status:match.status,to_status:'unmatched',comment:reason,occurred_at:now,operator_id:actor});return{id,status:'cancelled',transaction_id:tx.id,transaction_status:'unmatched'};
` },
});

export const BankTransactionMatchReverse = defineAction({
  name: 'bank_transaction_match_reverse', label: '反审核勾兑', objectName: 'forge_bank_transaction_match', icon: 'undo-2', locations: [...locations], order: 40, visible: `record.status == 'approved'`, refreshAfter: true,
  params: [{ field: 'reversal_reason', objectOverride: 'forge_bank_transaction_match', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),match=ctx.record,actor=ctx.session&&ctx.session.userId,reason=String(ctx.input.reversal_reason||'').trim();if(ctx.recordLoadDenied===true||!id||!match)throw new Error('勾兑记录不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(match.status!=='approved')throw new Error('仅已审核勾兑可以反审核');if(!reason)throw new Error('反审核原因不能为空');const tx=await ctx.api.object('forge_bank_transaction').findOne({where:{id:match.transaction_id}});if(!tx||tx.status!=='matched')throw new Error('关联银行流水状态已变化');const day=String(tx.transacted_at||'').slice(0,10),periods=await ctx.api.object('forge_financial_period').find({where:{account_id:tx.account_id}});if(periods.length&&!periods.some(x=>x.status==='open'&&day>=x.period_start&&day<=x.period_end))throw new Error('流水所在财务期间未开放，不能反审核');const now=new Date().toISOString();await ctx.api.object('forge_bank_transaction_match').update({id,status:'reversed',reversed_by:actor,reversed_at:now,reversal_reason:reason});await ctx.api.object('forge_bank_transaction').update({id:tx.id,matched_amount:0,difference_amount:tx.amount,status:'unmatched'});await ctx.api.object('forge_bank_transaction_log').insert({name:match.code+' 反审核',event_key:match.code+'-REVERSE',transaction_id:tx.id,match_id:id,action:'match_reversed',amount:match.book_amount,from_status:'matched',to_status:'unmatched',comment:reason,occurred_at:now,operator_id:actor});return{id,status:'reversed',transaction_id:tx.id,transaction_status:'unmatched',book_balance_unchanged:true};
` },
});

export const BankTransactionVoid = defineAction({
  name: 'bank_transaction_void', label: '作废银行流水', objectName: 'forge_bank_transaction', icon: 'ban', locations: [...locations], order: 50, visible: `record.status == 'unmatched'`, refreshAfter: true,
  params: [{ field: 'void_reason', objectOverride: 'forge_bank_transaction', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),tx=ctx.record,actor=ctx.session&&ctx.session.userId,reason=String(ctx.input.void_reason||'').trim();if(ctx.recordLoadDenied===true||!id||!tx)throw new Error('银行流水不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(tx.status!=='unmatched')throw new Error('仅未勾兑银行流水可以作废');if(!reason)throw new Error('作废原因不能为空');const matches=await ctx.api.object('forge_bank_transaction_match').find({where:{transaction_id:id}});if(matches.some(x=>['pending_review','discrepancy','approved'].includes(x.status)))throw new Error('请先取消或反审核有效勾兑');const day=String(tx.transacted_at||'').slice(0,10),periods=await ctx.api.object('forge_financial_period').find({where:{account_id:tx.account_id}});if(periods.length&&!periods.some(x=>x.status==='open'&&day>=x.period_start&&day<=x.period_end))throw new Error('流水所在财务期间未开放，不能作废');const now=new Date().toISOString();await ctx.api.object('forge_bank_transaction').update({id,status:'voided',voided_by:actor,voided_at:now,void_reason:reason});await ctx.api.object('forge_bank_transaction_log').insert({name:tx.code+' 作废',event_key:tx.code+'-VOID',transaction_id:id,match_id:null,action:'voided',amount:tx.amount,from_status:'unmatched',to_status:'voided',comment:reason,occurred_at:now,operator_id:actor});return{id,status:'voided',book_balance_unchanged:true};
` },
});
