import { defineAction } from '@objectstack/spec';

const locations = ['record_header', 'record_more'] as const;

export const DrawingVersionSubmitReview = defineAction({
  name:'drawing_version_submit_review',label:'提交评审',objectName:'forge_drawing_version',icon:'send',locations:[...locations],visible:`record.status == 'draft'`,refreshAfter:true,
  params:[{name:'discipline',label:'专业',type:'select',required:true,options:[{label:'机械',value:'mechanical'},{label:'电气',value:'electrical'},{label:'工艺',value:'process'},{label:'质量',value:'quality'},{label:'项目',value:'project'},{label:'其他',value:'other'}]},{name:'due_on',label:'截止日期',type:'date',required:true},{name:'participant_ids',label:'参与人',type:'text',required:true}],
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const version=ctx.record,id=ctx.recordId||(version&&version.id);if(ctx.recordLoadDenied===true||!id||!version||version.status!=='draft')throw new Error('仅草稿版本可以提交评审');
if(!version.drawing_id||!version.version||!version.file_name)throw new Error('提交前必须完整填写图号、版本号和主文件');
const duplicate=(await ctx.api.object('forge_drawing_version').find({where:{drawing_id:version.drawing_id,version:version.version}})).filter(x=>x.id!==id);if(duplicate.length)throw new Error('同一图号下版本号不能重复');
const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');if(!ctx.input.discipline||!ctx.input.due_on||!String(ctx.input.participant_ids||'').trim())throw new Error('请选择专业、截止日期并填写参与人');const now=new Date().toISOString();const drawing=await ctx.api.object('forge_drawing').findOne({where:{id:version.drawing_id}});
const reviews=await ctx.api.object('forge_drawing_review').find({where:{version_id:id}});if(reviews.some(x=>['pending','approved'].includes(x.status)))throw new Error('该版本已经存在待处理或已通过评审');
const review=await ctx.api.object('forge_drawing_review').insert({name:version.version+' 图纸评审',code:'DR-'+Date.now(),drawing_id:version.drawing_id,version_id:id,discipline:ctx.input.discipline,due_on:ctx.input.due_on,participant_ids:String(ctx.input.participant_ids).trim(),status:'pending',submitted_at:now});
await ctx.api.object('forge_drawing_version').update({id,status:'pending_review'});if(!drawing||!drawing.current_version_id)await ctx.api.object('forge_drawing').update({id:version.drawing_id,status:'reviewing'});
await ctx.api.object('forge_drawing_operation_log').insert({name:'提交版本评审',event_key:id+':submit:'+Date.now(),drawing_id:version.drawing_id,related_object:'forge_drawing_version',related_id:id,action:'version_submit_review',actor_id:actor,occurred_at:now,from_status:'draft',to_status:'pending_review',comment:version.change_summary||'提交版本评审'});
return {id,review_id:typeof review==='string'?review:review&&review.id,status:'pending_review'};`}
});

export const DrawingReviewDecision = defineAction({
  name:'drawing_review_decision',label:'评审处理',objectName:'forge_drawing_review',icon:'badge-check',locations:[...locations],visible:`record.status == 'pending'`,refreshAfter:true,
  params:[{name:'decision',label:'评审结论',type:'select',required:true,options:[{label:'通过',value:'approve'},{label:'退回',value:'reject'}]},{name:'comment',label:'评审意见',type:'textarea',required:true}],
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const review=ctx.record,id=ctx.recordId||(review&&review.id);if(ctx.recordLoadDenied===true||!id||!review||review.status!=='pending')throw new Error('仅待评审记录可以处理');
if(!['approve','reject'].includes(ctx.input.decision)||!String(ctx.input.comment||'').trim())throw new Error('请选择结论并填写评审意见');
const version=await ctx.api.object('forge_drawing_version').findOne({where:{id:review.version_id}});if(!version||version.status!=='pending_review')throw new Error('评审版本状态已变化');
const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),approved=ctx.input.decision==='approve',next=approved?'reviewed':'draft';
await ctx.api.object('forge_drawing_review').update({id,status:approved?'approved':'rejected',decision_note:String(ctx.input.comment).trim(),completed_at:now});
await ctx.api.object('forge_drawing_version').update({id:version.id,status:next,reviewed_at:approved?now:null});const drawing=await ctx.api.object('forge_drawing').findOne({where:{id:review.drawing_id}});if(!drawing||!drawing.current_version_id)await ctx.api.object('forge_drawing').update({id:review.drawing_id,status:'draft'});
await ctx.api.object('forge_drawing_operation_log').insert({name:approved?'评审通过':'评审退回',event_key:id+':decision:'+Date.now(),drawing_id:review.drawing_id,related_object:'forge_drawing_review',related_id:id,action:approved?'review_approved':'review_rejected',actor_id:actor,occurred_at:now,from_status:'pending',to_status:approved?'approved':'rejected',comment:String(ctx.input.comment).trim()});return {id,status:approved?'approved':'rejected',version_status:next};`}
});

export const DrawingReleaseSubmit = defineAction({
  name:'drawing_release_submit',label:'提交发布审核',objectName:'forge_drawing_release',icon:'send',locations:[...locations],visible:`record.status == 'draft'`,refreshAfter:true,
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const release=ctx.record,id=ctx.recordId||(release&&release.id);if(ctx.recordLoadDenied===true||!id||!release||release.status!=='draft')throw new Error('仅草稿发布单可以提交');
const version=await ctx.api.object('forge_drawing_version').findOne({where:{id:release.version_id}});if(!version||version.drawing_id!==release.drawing_id)throw new Error('发布版本与图号不匹配');if(version.status!=='reviewed')throw new Error('版本必须先评审通过才能提交发布');
const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_release').update({id,status:'pending',submitted_at:now});await ctx.api.object('forge_drawing_version').update({id:version.id,status:'pending_release'});
await ctx.api.object('forge_drawing_operation_log').insert({name:'提交发布审核',event_key:id+':submit:'+Date.now(),drawing_id:release.drawing_id,related_object:'forge_drawing_release',related_id:id,action:'release_submit',actor_id:actor,occurred_at:now,from_status:'draft',to_status:'pending',comment:release.impact_summary||'提交发布审核'});return {id,status:'pending'};`}
});

export const DrawingReleaseApprove = defineAction({
  name:'drawing_release_approve',label:'审核发布',objectName:'forge_drawing_release',icon:'shield-check',locations:[...locations],visible:`record.status == 'pending'`,refreshAfter:true,
  params:[{name:'comment',label:'审核意见',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const release=ctx.record,id=ctx.recordId||(release&&release.id);if(ctx.recordLoadDenied===true||!id||!release||release.status!=='pending')throw new Error('仅待审核发布单可以审核');if(!String(ctx.input.comment||'').trim())throw new Error('审核意见为必填');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();
await ctx.api.object('forge_drawing_release').update({id,status:'approved',approved_at:now});await ctx.api.object('forge_drawing_operation_log').insert({name:'发布审核通过',event_key:id+':approve:'+Date.now(),drawing_id:release.drawing_id,related_object:'forge_drawing_release',related_id:id,action:'release_approved',actor_id:actor,occurred_at:now,from_status:'pending',to_status:'approved',comment:String(ctx.input.comment).trim()});return {id,status:'approved'};`}
});

export const DrawingReleasePublish = defineAction({
  name:'drawing_release_publish',label:'正式发布',objectName:'forge_drawing_release',icon:'rocket',locations:[...locations],visible:`record.status == 'approved'`,refreshAfter:true,
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const release=ctx.record,id=ctx.recordId||(release&&release.id);if(ctx.recordLoadDenied===true||!id||!release||release.status!=='approved')throw new Error('仅已审核发布单可以正式发布');const version=await ctx.api.object('forge_drawing_version').findOne({where:{id:release.version_id}});if(!version||version.status!=='pending_release')throw new Error('待发布版本状态已变化');
const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();const old=(await ctx.api.object('forge_drawing_version').find({where:{drawing_id:release.drawing_id,status:'released'}})).filter(x=>x.id!==version.id);for(const item of old)await ctx.api.object('forge_drawing_version').update({id:item.id,status:'superseded'});
await ctx.api.object('forge_drawing_release').update({id,status:'released',released_at:now});await ctx.api.object('forge_drawing_version').update({id:version.id,status:'released',released_at:now});await ctx.api.object('forge_drawing').update({id:release.drawing_id,status:'released',current_version_id:version.id,current_version:version.version});
if(old.length){const oldIds=old.map(x=>x.id),links=await ctx.api.object('forge_drawing_business_link').find({where:{drawing_id:release.drawing_id,status:'active'}});for(const link of links)if(oldIds.includes(link.version_id)&&['material','bom','project'].includes(link.link_type))await ctx.api.object('forge_drawing_business_link').update({id:link.id,status:'needs_review'});}
await ctx.api.object('forge_drawing_operation_log').insert({name:'图纸正式发布',event_key:id+':publish:'+Date.now(),drawing_id:release.drawing_id,related_object:'forge_drawing_release',related_id:id,action:'released',actor_id:actor,occurred_at:now,from_status:'approved',to_status:'released',comment:'发布版本 '+version.version});return {id,status:'released',drawing_id:release.drawing_id,version_id:version.id};`}
});

export const DrawingReleaseCancel = defineAction({
  name:'drawing_release_cancel',label:'取消发布单',objectName:'forge_drawing_release',icon:'circle-x',locations:[...locations],visible:`record.status == 'draft' || record.status == 'pending' || record.status == 'approved'`,refreshAfter:true,
  params:[{name:'reason',label:'取消原因',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const release=ctx.record,id=ctx.recordId||(release&&release.id),reason=String(ctx.input.reason||'').trim();if(ctx.recordLoadDenied===true||!id||!release||!['draft','pending','approved'].includes(release.status))throw new Error('仅未正式发布的发布单可以取消');if(!reason)throw new Error('取消原因为必填');const version=await ctx.api.object('forge_drawing_version').findOne({where:{id:release.version_id}});if(!version||version.drawing_id!==release.drawing_id)throw new Error('发布版本与图号不匹配');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();if(['pending','approved'].includes(release.status)){if(version.status!=='pending_release')throw new Error('待发布版本状态已变化，不能取消');await ctx.api.object('forge_drawing_version').update({id:version.id,status:'reviewed'});}await ctx.api.object('forge_drawing_release').update({id,status:'cancelled',cancel_reason:reason,cancelled_at:now,cancelled_by:actor});await ctx.api.object('forge_drawing_operation_log').insert({name:'取消图纸发布单',event_key:id+':cancel:'+Date.now(),drawing_id:release.drawing_id,related_object:'forge_drawing_release',related_id:id,action:'release_cancelled',actor_id:actor,occurred_at:now,from_status:release.status,to_status:'cancelled',comment:reason});return{id,status:'cancelled',version_status:['pending','approved'].includes(release.status)?'reviewed':version.status};`}
});

export const DrawingChangeSubmit = defineAction({
  name:'drawing_change_submit',label:'提交变更审批',objectName:'forge_drawing_change',icon:'send',locations:[...locations],visible:`record.status == 'draft'`,refreshAfter:true,
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const change=ctx.record,id=ctx.recordId||(change&&change.id);if(ctx.recordLoadDenied===true||!id||!change||change.status!=='draft')throw new Error('仅草稿变更单可以提交');if(!String(change.reason||'').trim())throw new Error('变更原因为必填');const source=await ctx.api.object('forge_drawing_version').findOne({where:{id:change.source_version_id}});if(!source||source.drawing_id!==change.drawing_id||source.status!=='released')throw new Error('提交变更必须选择该图号当前已发布版本');const drawing=await ctx.api.object('forge_drawing').findOne({where:{id:change.drawing_id}});if(!drawing||drawing.current_version_id!==source.id)throw new Error('原版本不是当前生效版本');
const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_change').update({id,status:'pending',submitted_at:now});const links=(await ctx.api.object('forge_drawing_business_link').find({where:{drawing_id:change.drawing_id}})).filter(x=>['active','needs_review'].includes(x.status));let impactCount=0;for(const link of links){const existing=await ctx.api.object('forge_drawing_change_impact').find({where:{change_id:id,link_id:link.id}});if(existing.length)continue;await ctx.api.object('forge_drawing_change_impact').insert({name:change.code+' · '+(link.target_name||link.target_code||link.link_type),change_id:id,link_id:link.id,drawing_id:change.drawing_id,link_type:link.link_type,target_code:link.target_code||null,target_name:link.target_name||null,frozen_version:link.frozen_version,status:'pending'});impactCount++;}await ctx.api.object('forge_drawing_operation_log').insert({name:'提交图纸变更',event_key:id+':submit:'+Date.now(),drawing_id:change.drawing_id,related_object:'forge_drawing_change',related_id:id,action:'change_submit',actor_id:actor,occurred_at:now,from_status:'draft',to_status:'pending',comment:change.reason+'；影响快照 '+impactCount+' 项'});return {id,status:'pending',impact_count:impactCount};`}
});

export const DrawingChangeApprove = defineAction({
  name:'drawing_change_approve',label:'批准变更',objectName:'forge_drawing_change',icon:'badge-check',locations:[...locations],visible:`record.status == 'pending'`,refreshAfter:true,
  params:[{name:'comment',label:'审批意见',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const change=ctx.record,id=ctx.recordId||(change&&change.id);if(ctx.recordLoadDenied===true||!id||!change||change.status!=='pending')throw new Error('仅待审批变更单可以批准');if(!String(ctx.input.comment||'').trim())throw new Error('审批意见为必填');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_change').update({id,status:'implementing',approved_at:now});await ctx.api.object('forge_drawing_operation_log').insert({name:'批准图纸变更',event_key:id+':approve:'+Date.now(),drawing_id:change.drawing_id,related_object:'forge_drawing_change',related_id:id,action:'change_approved',actor_id:actor,occurred_at:now,from_status:'pending',to_status:'implementing',comment:String(ctx.input.comment).trim()});return {id,status:'implementing'};`}
});

export const DrawingChangeSetTargetVersion = defineAction({
  name:'drawing_change_set_target_version',label:'关联变更后版本',objectName:'forge_drawing_change',icon:'link',locations:[...locations],visible:`record.status == 'implementing'`,refreshAfter:true,
  params:[{name:'target_version_id',label:'变更后版本',type:'text',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const change=ctx.record,id=ctx.recordId||(change&&change.id),targetId=String(ctx.input.target_version_id||'').trim();if(ctx.recordLoadDenied===true||!id||!change||change.status!=='implementing')throw new Error('仅实施中的变更可以关联变更后版本');if(!targetId)throw new Error('请选择变更后版本');const target=await ctx.api.object('forge_drawing_version').findOne({where:{id:targetId}});if(!target||target.drawing_id!==change.drawing_id)throw new Error('变更后版本与图号不匹配');if(target.id===change.source_version_id)throw new Error('变更后版本不能与原生效版本相同');if(!['reviewed','pending_release','released'].includes(target.status))throw new Error('变更后版本至少应已评审通过');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_change').update({id,target_version_id:target.id});await ctx.api.object('forge_drawing_operation_log').insert({name:'关联变更后版本',event_key:id+':target:'+Date.now(),drawing_id:change.drawing_id,related_object:'forge_drawing_change',related_id:id,action:'change_target_linked',actor_id:actor,occurred_at:now,from_status:change.source_version_id,to_status:target.id,comment:'变更后版本 '+target.version});return {id,target_version_id:target.id,target_version:target.version,status:'implementing'};`}
});

export const DrawingChangeComplete = defineAction({
  name:'drawing_change_complete',label:'完成变更',objectName:'forge_drawing_change',icon:'circle-check',locations:[...locations],visible:`record.status == 'implementing'`,refreshAfter:true,
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const change=ctx.record,id=ctx.recordId||(change&&change.id);if(ctx.recordLoadDenied===true||!id||!change||change.status!=='implementing')throw new Error('仅实施中的变更可以完成');if(!change.target_version_id)throw new Error('完成变更前必须关联变更后版本');const target=await ctx.api.object('forge_drawing_version').findOne({where:{id:change.target_version_id}});if(!target||target.drawing_id!==change.drawing_id)throw new Error('变更后版本与图号不匹配');if(!['reviewed','pending_release','released'].includes(target.status))throw new Error('变更后版本至少应已评审通过');const impacts=await ctx.api.object('forge_drawing_change_impact').find({where:{change_id:id}});if(impacts.some(x=>x.status==='pending'))throw new Error('仍有未处置的业务影响项');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_change').update({id,status:'completed',completed_at:now});await ctx.api.object('forge_drawing_operation_log').insert({name:'完成图纸变更',event_key:id+':complete:'+Date.now(),drawing_id:change.drawing_id,related_object:'forge_drawing_change',related_id:id,action:'change_completed',actor_id:actor,occurred_at:now,from_status:'implementing',to_status:'completed',comment:'变更后版本 '+target.version+'；已处置影响 '+impacts.length+' 项'});return {id,status:'completed',impact_count:impacts.length};`}
});

export const DrawingDistributionExecute = defineAction({
  name:'drawing_distribution_execute',label:'执行发放',objectName:'forge_drawing_distribution',icon:'send',locations:[...locations],visible:`record.status == 'draft' || record.status == 'pending'`,refreshAfter:true,
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const dist=ctx.record,id=ctx.recordId||(dist&&dist.id);if(ctx.recordLoadDenied===true||!id||!dist||!['draft','pending'].includes(dist.status))throw new Error('仅草稿或待发放记录可以执行');if(!dist.drawing_id)throw new Error('请选择图号');const drawing=await ctx.api.object('forge_drawing').findOne({where:{id:dist.drawing_id}});if(!drawing||drawing.status!=='released'||!drawing.current_version_id)throw new Error('仅已发布图号可以发放');const versionId=dist.version_id||drawing.current_version_id,version=await ctx.api.object('forge_drawing_version').findOne({where:{id:versionId}});if(!version||version.drawing_id!==drawing.id||version.status!=='released')throw new Error('发放版本必须是当前已发布版本');if(version.id!==drawing.current_version_id)throw new Error('不能发放已替代版本');if(!dist.purpose||!dist.recipient_type||!dist.recipient_name||!dist.method)throw new Error('执行发放前必须填写用途、接收类型、接收对象和发放方式');if(dist.recipient_type==='supplier'&&!drawing.external_share_allowed)throw new Error('该图号未允许外发供应商');if(dist.recipient_type==='customer'&&!drawing.external_share_allowed)throw new Error('该图号未允许外发客户');if(dist.require_receipt&&!String(dist.receipt_requirement||'').trim())throw new Error('要求回执时必须填写回执要求说明');
const recipients=await ctx.api.object('forge_drawing_distribution_recipient').find({where:{distribution_id:id}});if(dist.multi_recipient&&recipients.length<2)throw new Error('多对象发放至少需要两个接收对象');if(!dist.multi_recipient&&recipients.length)throw new Error('单对象发放不能附带多对象接收清单');if(dist.multi_recipient&&recipients.some(x=>['supplier','customer'].includes(x.recipient_type))&&!drawing.external_share_allowed)throw new Error('该图号未允许向外部接收对象发放');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),count=dist.multi_recipient?recipients.length:1,required=dist.require_confirmation?(dist.multi_recipient?(dist.require_all_confirmation?count:1):1):0,confirm=dist.require_confirmation?'pending':'confirmed',receipt=dist.require_receipt?'pending':'not_required';for(const recipient of recipients)await ctx.api.object('forge_drawing_distribution_recipient').update({id:recipient.id,confirmation_status:dist.require_confirmation?'pending':'not_required',receipt_status:dist.require_receipt?'pending':'not_required'});await ctx.api.object('forge_drawing_distribution').update({id,version_id:version.id,status:'sent',confirmation_status:confirm,receipt_status:receipt,recipient_count:count,confirmed_count:dist.require_confirmation?0:count,confirmation_required_count:required,confirmation_satisfied:!dist.require_confirmation,receipt_count:0,sent_at:now});await ctx.api.object('forge_drawing_operation_log').insert({name:'执行图纸发放',event_key:id+':sent:'+Date.now(),drawing_id:drawing.id,related_object:'forge_drawing_distribution',related_id:id,action:'distribution_sent',actor_id:actor,occurred_at:now,from_status:dist.status,to_status:'sent',comment:'发放 '+version.version+' 给 '+(dist.multi_recipient?count+' 个接收对象':dist.recipient_name)});return {id,status:'sent',version_id:version.id,recipient_count:count,confirmation_required_count:required,confirmation_status:confirm,receipt_status:receipt};`}
});

export const DrawingDistributionConfirm = defineAction({
  name:'drawing_distribution_confirm',label:'确认接收',objectName:'forge_drawing_distribution',icon:'check-check',locations:[...locations],visible:`record.status == 'sent' && record.confirmation_status == 'pending'`,refreshAfter:true,
  params:[{name:'receipt_received',label:'同时收到回执',type:'boolean'}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const dist=ctx.record,id=ctx.recordId||(dist&&dist.id);if(ctx.recordLoadDenied===true||!id||!dist||dist.status!=='sent'||dist.confirmation_status!=='pending')throw new Error('当前发放记录无需确认或状态已变化');if(dist.multi_recipient)throw new Error('多对象发放必须逐个接收对象确认');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),receipt=dist.require_receipt&&ctx.input.receipt_received===true?'received':dist.receipt_status;await ctx.api.object('forge_drawing_distribution').update({id,confirmation_status:'confirmed',receipt_status:receipt,recipient_count:1,confirmed_count:1,confirmation_required_count:1,confirmation_satisfied:true,receipt_count:receipt==='received'?1:0,confirmed_at:now});await ctx.api.object('forge_drawing_operation_log').insert({name:'确认图纸接收',event_key:id+':confirm:'+Date.now(),drawing_id:dist.drawing_id,related_object:'forge_drawing_distribution',related_id:id,action:'distribution_confirmed',actor_id:actor,occurred_at:now,from_status:'pending',to_status:'confirmed',comment:receipt==='received'?'已确认并收到回执':'已确认接收'});return {id,confirmation_status:'confirmed',receipt_status:receipt,confirmation_satisfied:true};`}
});

export const DrawingDistributionAddRecipient = defineAction({
  name:'drawing_distribution_add_recipient',label:'添加接收对象',objectName:'forge_drawing_distribution',icon:'user-plus',locations:[...locations],visible:`record.status == 'draft' || record.status == 'pending'`,refreshAfter:true,
  params:[{name:'recipient_type',label:'接收类型',type:'select',required:true,options:[{value:'department',label:'内部部门'},{value:'person',label:'内部人员'},{value:'supplier',label:'供应商'},{value:'customer',label:'客户'}]},{name:'recipient_name',label:'接收对象',type:'text',required:true},{name:'organization',label:'所属单位或部门',type:'text'},{name:'contact',label:'联系方式',type:'text'}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const dist=ctx.record,id=ctx.recordId||(dist&&dist.id),type=ctx.input.recipient_type,name=String(ctx.input.recipient_name||'').trim();if(ctx.recordLoadDenied===true||!id||!dist||!['draft','pending'].includes(dist.status))throw new Error('仅草稿或待发放记录可以维护接收对象');if(!dist.multi_recipient)throw new Error('请先启用多对象接收');if(!['department','person','supplier','customer'].includes(type)||!name)throw new Error('接收类型和接收对象均为必填');const existing=await ctx.api.object('forge_drawing_distribution_recipient').find({where:{distribution_id:id,recipient_type:type,name}});if(existing.length)throw new Error('接收对象已存在');const created=await ctx.api.object('forge_drawing_distribution_recipient').insert({name,code:'DR-'+Date.now(),distribution_id:id,recipient_type:type,organization:String(ctx.input.organization||'').trim()||null,contact:String(ctx.input.contact||'').trim()||null,confirmation_status:'pending',receipt_status:'not_required'}),recipientId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id)),recipients=await ctx.api.object('forge_drawing_distribution_recipient').find({where:{distribution_id:id}});await ctx.api.object('forge_drawing_distribution').update({id,recipient_count:recipients.length});return{id:recipientId,distribution_id:id,recipient_count:recipients.length};`}
});

export const DrawingDistributionRecipientConfirm = defineAction({
  name:'drawing_distribution_recipient_confirm',label:'确认接收',objectName:'forge_drawing_distribution_recipient',icon:'check-check',locations:[...locations],visible:`record.confirmation_status == 'pending'`,refreshAfter:true,
  params:[{name:'receipt_received',label:'同时收到回执',type:'boolean'},{name:'receipt_note',label:'回执说明',type:'textarea'}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const recipient=ctx.record,id=ctx.recordId||(recipient&&recipient.id);if(ctx.recordLoadDenied===true||!id||!recipient||recipient.confirmation_status!=='pending')throw new Error('当前接收对象无需确认或状态已变化');const dist=await ctx.api.object('forge_drawing_distribution').findOne({where:{id:recipient.distribution_id}});if(!dist||dist.status!=='sent'||!dist.multi_recipient||!dist.require_confirmation)throw new Error('关联发放单不能逐项确认');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),receipt=dist.require_receipt&&ctx.input.receipt_received===true?'received':recipient.receipt_status,note=String(ctx.input.receipt_note||'').trim()||null;await ctx.api.object('forge_drawing_distribution_recipient').update({id,confirmation_status:'confirmed',receipt_status:receipt,confirmed_at:now,confirmed_by:actor,receipt_note:note});const recipients=await ctx.api.object('forge_drawing_distribution_recipient').find({where:{distribution_id:dist.id}}),confirmed=recipients.filter(x=>x.id===id||x.confirmation_status==='confirmed').length,received=recipients.filter(x=>(x.id===id?receipt:x.receipt_status)==='received').length,total=recipients.length,complete=confirmed===total,satisfied=confirmed>=Number(dist.confirmation_required_count||1),parentStatus=complete?'confirmed':'partial',parentReceipt=dist.require_receipt&&received===total?'received':dist.require_receipt?'pending':'not_required';await ctx.api.object('forge_drawing_distribution').update({id:dist.id,confirmation_status:parentStatus,confirmed_count:confirmed,confirmation_satisfied:satisfied,receipt_status:parentReceipt,receipt_count:received,confirmed_at:complete?now:null});await ctx.api.object('forge_drawing_operation_log').insert({name:'接收对象确认图纸',event_key:id+':confirm:'+Date.now(),drawing_id:dist.drawing_id,related_object:'forge_drawing_distribution_recipient',related_id:id,action:'distribution_recipient_confirmed',actor_id:actor,occurred_at:now,from_status:'pending',to_status:'confirmed',comment:recipient.name+(receipt==='received'?' 已确认并回执':' 已确认接收')});return{id,distribution_id:dist.id,confirmation_status:parentStatus,confirmed_count:confirmed,recipient_count:total,confirmation_satisfied:satisfied,receipt_status:parentReceipt,receipt_count:received};`}
});

export const DrawingBindBusiness = defineAction({
  name:'drawing_bind_business',label:'关联业务对象',objectName:'forge_drawing',icon:'link',locations:[...locations],visible:`record.status == 'released'`,refreshAfter:true,
  params:[{name:'link_type',label:'关联类型',type:'select',required:true,options:[{value:'material',label:'物料'},{value:'bom',label:'BOM'},{value:'project',label:'项目'},{value:'purchase_order',label:'采购订单'},{value:'assembly_order',label:'组装单'}]},{name:'target_id',label:'业务对象ID',type:'text',required:true},{name:'purpose',label:'使用目的',type:'textarea',required:true}],
  body:{language:'js',capabilities:['api.read','api.write'],source:`
const drawing=ctx.record,id=ctx.recordId||(drawing&&drawing.id);if(ctx.recordLoadDenied===true||!id||!drawing||drawing.status!=='released'||!drawing.current_version_id)throw new Error('仅有当前发布版本的图号可以建立业务关联');const type=ctx.input.link_type,targetId=String(ctx.input.target_id||'').trim(),purpose=String(ctx.input.purpose||'').trim(),objects={material:'forge_material',bom:'forge_bom',project:'forge_project',purchase_order:'forge_purchase_order',assembly_order:'forge_assembly_order'},fields={material:'material_id',bom:'bom_id',project:'project_id',purchase_order:'purchase_order_id',assembly_order:'assembly_order_id'};if(!objects[type]||!targetId||!purpose)throw new Error('关联类型、业务对象和使用目的均为必填');const target=await ctx.api.object(objects[type]).findOne({where:{id:targetId}});if(!target)throw new Error('关联业务对象不存在或不可访问');if(type==='bom'&&target.status!=='active')throw new Error('只能关联已生效BOM');if(type==='purchase_order'&&!['approved','partially_arrived','arrived','completed'].includes(target.status))throw new Error('采购订单必须已审核');if(type==='assembly_order'&&target.status==='draft')throw new Error('组装单下达后才能冻结图纸版本');
const existing=(await ctx.api.object('forge_drawing_business_link').find({where:{drawing_id:id,link_type:type}})).filter(x=>x[fields[type]]===targetId&&['active','needs_review'].includes(x.status));if(existing.length)throw new Error('该业务对象已存在有效或需确认关联');const version=await ctx.api.object('forge_drawing_version').findOne({where:{id:drawing.current_version_id}});if(!version||version.status!=='released')throw new Error('图号当前版本不是已发布状态');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),payload={name:drawing.code+' · '+(target.name||target.code||targetId),code:'DL-'+Date.now(),drawing_id:id,version_id:version.id,frozen_version:version.version,link_type:type,target_code:target.code||null,target_name:target.name||null,purpose,status:'active',frozen_at:now,frozen_by:actor};payload[fields[type]]=targetId;const created=await ctx.api.object('forge_drawing_business_link').insert(payload),linkId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));await ctx.api.object('forge_drawing_operation_log').insert({name:'建立业务关联',event_key:id+':bind:'+Date.now(),drawing_id:id,related_object:'forge_drawing_business_link',related_id:linkId,action:'business_bound',actor_id:actor,occurred_at:now,from_status:null,to_status:'active',comment:type+' '+(target.code||target.name||targetId)+' 冻结 '+version.version});return{id:linkId,drawing_id:id,version_id:version.id,frozen_version:version.version,link_type:type,target_id:targetId,status:'active'};`}
});

export const DrawingBusinessLinkAdoptCurrent = defineAction({
  name:'drawing_business_link_adopt_current',label:'采纳当前版本',objectName:'forge_drawing_business_link',icon:'replace',locations:[...locations],visible:`record.status == 'needs_review'`,refreshAfter:true,
  params:[{name:'reason',label:'采纳说明',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const link=ctx.record,id=ctx.recordId||(link&&link.id);if(ctx.recordLoadDenied===true||!id||!link||link.status!=='needs_review')throw new Error('仅待版本复核关联可以采纳当前版本');if(!['material','bom','project'].includes(link.link_type))throw new Error('业务单据冻结版本不能直接替换');const reason=String(ctx.input.reason||'').trim();if(!reason)throw new Error('采纳说明为必填');const drawing=await ctx.api.object('forge_drawing').findOne({where:{id:link.drawing_id}}),version=drawing&&await ctx.api.object('forge_drawing_version').findOne({where:{id:drawing.current_version_id}});if(!drawing||drawing.status!=='released'||!version||version.status!=='released'||version.id===link.version_id)throw new Error('当前没有可采纳的新发布版本');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString(),payload={name:link.name,code:'DL-'+Date.now(),drawing_id:link.drawing_id,version_id:version.id,frozen_version:version.version,link_type:link.link_type,target_code:link.target_code||null,target_name:link.target_name||null,purpose:link.purpose,status:'active',frozen_at:now,frozen_by:actor,remarks:reason};for(const field of ['material_id','bom_id','project_id','purchase_order_id','assembly_order_id'])if(link[field])payload[field]=link[field];const created=await ctx.api.object('forge_drawing_business_link').insert(payload),newId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));await ctx.api.object('forge_drawing_business_link').update({id,status:'replaced',replaced_by_link_id:newId});await ctx.api.object('forge_drawing_operation_log').insert({name:'业务关联采纳新版本',event_key:id+':adopt:'+Date.now(),drawing_id:link.drawing_id,related_object:'forge_drawing_business_link',related_id:newId,action:'business_version_adopted',actor_id:actor,occurred_at:now,from_status:link.frozen_version,to_status:version.version,comment:reason});return{id:newId,replaced_link_id:id,frozen_version:version.version,status:'active'};`}
});

export const DrawingBusinessLinkObsolete = defineAction({
  name:'drawing_business_link_obsolete',label:'解除关联',objectName:'forge_drawing_business_link',icon:'unlink',locations:[...locations],visible:`record.status == 'active' || record.status == 'needs_review'`,refreshAfter:true,
  params:[{name:'reason',label:'解除原因',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const link=ctx.record,id=ctx.recordId||(link&&link.id),reason=String(ctx.input.reason||'').trim();if(ctx.recordLoadDenied===true||!id||!link||!['active','needs_review'].includes(link.status))throw new Error('当前关联不能解除');if(!reason)throw new Error('解除原因为必填');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_business_link').update({id,status:'obsolete',obsolete_reason:reason});await ctx.api.object('forge_drawing_operation_log').insert({name:'解除业务关联',event_key:id+':obsolete:'+Date.now(),drawing_id:link.drawing_id,related_object:'forge_drawing_business_link',related_id:id,action:'business_unbound',actor_id:actor,occurred_at:now,from_status:link.status,to_status:'obsolete',comment:reason});return{id,status:'obsolete'};`}
});

export const DrawingChangeImpactResolve = defineAction({
  name:'drawing_change_impact_resolve',label:'处置影响',objectName:'forge_drawing_change_impact',icon:'circle-check',locations:[...locations],visible:`record.status == 'pending'`,refreshAfter:true,
  params:[{name:'decision',label:'处置结论',type:'select',required:true,options:[{value:'adopt_new',label:'采纳新版本'},{value:'keep_old',label:'保留旧版本'},{value:'not_affected',label:'确认不受影响'},{value:'mitigated',label:'已采取措施'}]},{name:'assessment',label:'影响评估',type:'textarea',required:true}],body:{language:'js',capabilities:['api.read','api.write'],source:`
const impact=ctx.record,id=ctx.recordId||(impact&&impact.id),decision=ctx.input.decision,assessment=String(ctx.input.assessment||'').trim();if(ctx.recordLoadDenied===true||!id||!impact||impact.status!=='pending')throw new Error('仅待评估影响项可以处置');if(!['adopt_new','keep_old','not_affected','mitigated'].includes(decision)||!assessment)throw new Error('处置结论和影响评估均为必填');const change=await ctx.api.object('forge_drawing_change').findOne({where:{id:impact.change_id}});if(!change||!['pending','approved','implementing'].includes(change.status))throw new Error('关联变更已不能继续处置');const actor=ctx.session&&ctx.session.userId;if(!actor)throw new Error('无法识别当前操作人');const now=new Date().toISOString();await ctx.api.object('forge_drawing_change_impact').update({id,status:decision,assessment,resolved_at:now,resolved_by:actor});await ctx.api.object('forge_drawing_operation_log').insert({name:'处置变更影响',event_key:id+':resolve:'+Date.now(),drawing_id:impact.drawing_id,related_object:'forge_drawing_change_impact',related_id:id,action:'change_impact_resolved',actor_id:actor,occurred_at:now,from_status:'pending',to_status:decision,comment:assessment});return{id,status:decision};`}
});
