import { defineAction } from '@objectstack/spec/ui';

const locations = ['record_header', 'record_more'] as const;

export const OpeningRegisterReceivable = defineAction({
  name: 'opening_register_receivable', label: '录入期初应收', objectName: 'forge_accounting_opening_setup', icon: 'wallet-cards', locations: [...locations], order: 10, refreshAfter: true,
  params: [
    { name: 'code', label: '期初应收编号', type: 'text', required: true }, { field: 'customer_id', objectOverride: 'forge_accounts_receivable', required: true },
    { name: 'due_on', label: '原到期日期', type: 'date', required: true }, { name: 'original_amount', label: '应收原值', type: 'currency', required: true },
    { name: 'collected_amount', label: '期初已收金额', type: 'currency', required: true }, { name: 'historical_contract_no', label: '历史合同编号', type: 'text' },
    { name: 'invoice_marker', label: '历史开票标记', type: 'select', options: [{ value: 'invoiced', label: '已开票' }, { value: 'not_invoiced', label: '未开票' }, { value: 'unknown', label: '不详' }], required: true },
    { name: 'remarks', label: '期初说明', type: 'textarea' },
  ],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),setup=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!id||!setup)throw new Error('期初建账不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');const activation=new Date(String(setup.activation_on)+'T00:00:00Z');activation.setUTCDate(activation.getUTCDate()-1);if(activation.toISOString().slice(0,10)!==setup.document_on)throw new Error('期初单据日期必须是系统启用日前一日');const code=String(ctx.input.code||'').trim(),amount=Math.round((Number(ctx.input.original_amount||0)+Number.EPSILON)*10000)/10000,collected=Math.round((Number(ctx.input.collected_amount||0)+Number.EPSILON)*10000)/10000;if(!code||!ctx.input.customer_id||!ctx.input.due_on)throw new Error('期初应收编号、客户和原到期日不能为空');if(!(amount>0)||collected<0||collected>amount)throw new Error('期初已收金额必须在零到应收原值之间');if((await ctx.api.object('forge_accounts_receivable').find({where:{code}})).length)throw new Error('期初应收编号已存在');const customer=await ctx.api.object('forge_customer').findOne({where:{id:ctx.input.customer_id}});if(!customer)throw new Error('客户不存在');const outstanding=Math.round((amount-collected+Number.EPSILON)*10000)/10000,status=outstanding===0?'settled':(collected>0?'partially_collected':(String(ctx.input.due_on)<String(setup.activation_on)?'overdue':'unpaid'));const made=await ctx.api.object('forge_accounts_receivable').insert({name:code+' '+customer.name+' 期初应收',code,source_type:'opening_balance',invoice_id:null,order_id:null,contract_id:null,customer_id:customer.id,recognized_on:setup.document_on,due_on:ctx.input.due_on,original_amount:amount,collected_amount:collected,offset_amount:0,red_reversed_amount:0,outstanding_amount:outstanding,historical_contract_no:ctx.input.historical_contract_no||null,invoice_marker:ctx.input.invoice_marker||'unknown',status,responsible_id:setup.responsible_id,remarks:ctx.input.remarks||null}),rid=typeof made==='string'?made:made&&(made.id||(made.record&&made.record.id));if(!rid)throw new Error('期初应收创建后未返回ID');const now=new Date().toISOString();await ctx.api.object('forge_accounting_opening_log').insert({name:code+' 期初应收录入',event_key:code+'-CREATE',setup_id:id,offset_id:null,action:'receivable_created',direction:'receivable',source_id:rid,amount,comment:'原到期日 '+ctx.input.due_on,occurred_at:now,operator_id:actor});return{id:rid,setup_id:id,status,outstanding_amount:outstanding};
` },
});

export const OpeningRegisterPayable = defineAction({
  name: 'opening_register_payable', label: '录入期初应付', objectName: 'forge_accounting_opening_setup', icon: 'hand-coins', locations: [...locations], order: 20, refreshAfter: true,
  params: [
    { name: 'code', label: '期初应付编号', type: 'text', required: true }, { field: 'supplier_id', objectOverride: 'forge_accounts_payable', required: true },
    { name: 'due_on', label: '原到期日期', type: 'date', required: true }, { name: 'original_amount', label: '应付原值', type: 'currency', required: true },
    { name: 'paid_amount', label: '期初已付金额', type: 'currency', required: true }, { name: 'historical_contract_no', label: '历史合同编号', type: 'text' },
    { name: 'invoice_marker', label: '历史开票标记', type: 'select', options: [{ value: 'invoiced', label: '已开票' }, { value: 'not_invoiced', label: '未开票' }, { value: 'unknown', label: '不详' }], required: true },
    { name: 'remarks', label: '期初说明', type: 'textarea' },
  ],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),setup=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!id||!setup)throw new Error('期初建账不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');const activation=new Date(String(setup.activation_on)+'T00:00:00Z');activation.setUTCDate(activation.getUTCDate()-1);if(activation.toISOString().slice(0,10)!==setup.document_on)throw new Error('期初单据日期必须是系统启用日前一日');const code=String(ctx.input.code||'').trim(),amount=Math.round((Number(ctx.input.original_amount||0)+Number.EPSILON)*10000)/10000,paid=Math.round((Number(ctx.input.paid_amount||0)+Number.EPSILON)*10000)/10000;if(!code||!ctx.input.supplier_id||!ctx.input.due_on)throw new Error('期初应付编号、供应商和原到期日不能为空');if(!(amount>0)||paid<0||paid>amount)throw new Error('期初已付金额必须在零到应付原值之间');if((await ctx.api.object('forge_accounts_payable').find({where:{code}})).length)throw new Error('期初应付编号已存在');const supplier=await ctx.api.object('forge_supplier').findOne({where:{id:ctx.input.supplier_id}});if(!supplier)throw new Error('供应商不存在');const outstanding=Math.round((amount-paid+Number.EPSILON)*10000)/10000,status=outstanding===0?'settled':(paid>0?'partially_paid':(String(ctx.input.due_on)<String(setup.activation_on)?'overdue':'unpaid'));const made=await ctx.api.object('forge_accounts_payable').insert({name:code+' '+supplier.name+' 期初应付',code,source_type:'opening_balance',inbound_id:null,invoice_id:null,order_id:null,supplier_id:supplier.id,recognized_on:setup.document_on,due_on:ctx.input.due_on,original_amount:amount,paid_amount:paid,offset_amount:0,red_reversed_amount:0,outstanding_amount:outstanding,historical_contract_no:ctx.input.historical_contract_no||null,invoice_marker:ctx.input.invoice_marker||'unknown',status,responsible_id:setup.responsible_id,remarks:ctx.input.remarks||null}),pid=typeof made==='string'?made:made&&(made.id||(made.record&&made.record.id));if(!pid)throw new Error('期初应付创建后未返回ID');const now=new Date().toISOString();await ctx.api.object('forge_accounting_opening_log').insert({name:code+' 期初应付录入',event_key:code+'-CREATE',setup_id:id,offset_id:null,action:'payable_created',direction:'payable',source_id:pid,amount,comment:'原到期日 '+ctx.input.due_on,occurred_at:now,operator_id:actor});return{id:pid,setup_id:id,status,outstanding_amount:outstanding};
` },
});

export const OpeningMarkOnboarding = defineAction({
  name: 'opening_mark_onboarding', label: '确认建账进度', objectName: 'forge_accounting_opening_setup', icon: 'check-check', locations: [...locations], order: 30, refreshAfter: true,
  params: [{ name: 'direction', label: '往来方向', type: 'select', options: [{ value: 'receivable', label: '期初应收' }, { value: 'payable', label: '期初应付' }], required: true }, { name: 'result', label: '处理结果', type: 'select', options: [{ value: 'completed', label: '完成' }, { value: 'skipped', label: '跳过' }], required: true }, { name: 'comment', label: '确认说明', type: 'textarea', required: true }],
  body: { language: 'js', capabilities: ['api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),setup=ctx.record,actor=ctx.session&&ctx.session.userId,direction=ctx.input.direction,result=ctx.input.result,comment=String(ctx.input.comment||'').trim();if(ctx.recordLoadDenied===true||!id||!setup)throw new Error('期初建账不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(!['receivable','payable'].includes(direction)||!['completed','skipped'].includes(result)||!comment)throw new Error('往来方向、处理结果和确认说明不能为空');const now=new Date().toISOString(),patch={id};patch[direction+'_status']=result;patch[direction+'_closed_by']=actor;patch[direction+'_closed_at']=now;await ctx.api.object('forge_accounting_opening_setup').update(patch);await ctx.api.object('forge_accounting_opening_log').insert({name:setup.code+' '+direction+' '+result,event_key:setup.code+'-'+direction+'-'+result+'-'+Date.now(),setup_id:id,offset_id:null,action:result==='completed'?'onboarding_completed':'onboarding_skipped',direction,source_id:id,amount:0,comment,occurred_at:now,operator_id:actor});return{id,direction,status:result};
` },
});

export const ReceivableCreateCounterpartyOffset = defineAction({
  name: 'receivable_create_counterparty_offset', label: '创建往来对冲', objectName: 'forge_accounts_receivable', icon: 'arrow-left-right', locations: [...locations], order: 30, refreshAfter: true,
  visible: `record.status == 'unpaid' || record.status == 'partially_collected' || record.status == 'overdue'`,
  params: [{ name: 'code', label: '对冲单号', type: 'text', required: true }, { field: 'payable_id', objectOverride: 'forge_counterparty_offset', required: true }, { name: 'amount', label: '对冲金额', type: 'currency', required: true }, { name: 'offset_on', label: '对冲日期', type: 'date', required: true }, { name: 'remarks', label: '申请说明', type: 'textarea' }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),ar=ctx.record,actor=ctx.session&&ctx.session.userId,code=String(ctx.input.code||'').trim(),amount=Math.round((Number(ctx.input.amount||0)+Number.EPSILON)*10000)/10000;if(ctx.recordLoadDenied===true||!id||!ar)throw new Error('应收账款不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(!code||!ctx.input.payable_id||!ctx.input.offset_on||!(amount>0))throw new Error('对冲单号、应付账款、日期和金额不能为空');if((await ctx.api.object('forge_counterparty_offset').find({where:{code}})).length)throw new Error('对冲单号已存在');const [ap,customer]=await Promise.all([ctx.api.object('forge_accounts_payable').findOne({where:{id:ctx.input.payable_id}}),ctx.api.object('forge_customer').findOne({where:{id:ar.customer_id}})]);if(!ap||!customer)throw new Error('应付账款或客户不存在');const supplier=await ctx.api.object('forge_supplier').findOne({where:{id:ap.supplier_id}});if(!supplier)throw new Error('供应商不存在');const cc=String(customer.credit_code||'').trim().toUpperCase(),sc=String(supplier.credit_code||'').trim().toUpperCase(),cn=String(customer.name||'').normalize('NFKC').replace(/\s+/g,'').toLowerCase(),sn=String(supplier.name||'').normalize('NFKC').replace(/\s+/g,'').toLowerCase(),basis=cc&&sc&&cc===sc?'credit_code':(cn&&cn===sn?'normalized_name':null);if(!basis)throw new Error('客户与供应商不是同一往来单位，名称或统一社会信用代码必须一致');if(amount>Number(ar.outstanding_amount||0)+0.0001||amount>Number(ap.outstanding_amount||0)+0.0001)throw new Error('对冲金额超过应收或应付余额');const made=await ctx.api.object('forge_counterparty_offset').insert({name:code+' '+customer.name+' 往来对冲',code,receivable_id:id,payable_id:ap.id,customer_id:customer.id,supplier_id:supplier.id,counterparty_name:customer.name,identity_basis:basis,amount,offset_on:ctx.input.offset_on,status:'draft',applicant_id:actor,responsible_id:ar.responsible_id,remarks:ctx.input.remarks||null}),oid=typeof made==='string'?made:made&&(made.id||(made.record&&made.record.id));if(!oid)throw new Error('往来对冲单创建后未返回ID');const now=new Date().toISOString();await ctx.api.object('forge_accounting_opening_log').insert({name:code+' 创建',event_key:code+'-CREATE',setup_id:null,offset_id:oid,action:'offset_created',direction:'offset',source_id:oid,amount,comment:'主体依据 '+basis,occurred_at:now,operator_id:actor});return{id:oid,status:'draft',identity_basis:basis};
` },
});

export const CounterpartyOffsetSubmit = defineAction({
  name: 'counterparty_offset_submit', label: '提交审核', objectName: 'forge_counterparty_offset', icon: 'send', locations: [...locations], order: 10, visible: `record.status == 'draft' || record.status == 'rejected'`, refreshAfter: true,
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),o=ctx.record,actor=ctx.session&&ctx.session.userId;if(ctx.recordLoadDenied===true||!id||!o)throw new Error('往来对冲单不存在或不可访问');if(!actor)throw new Error('无法识别当前操作人');if(!['draft','rejected'].includes(o.status))throw new Error('仅草稿或已驳回对冲单可以提交');const [ar,ap]=await Promise.all([ctx.api.object('forge_accounts_receivable').findOne({where:{id:o.receivable_id}}),ctx.api.object('forge_accounts_payable').findOne({where:{id:o.payable_id}})]);if(!ar||!ap||Number(o.amount)>Number(ar.outstanding_amount||0)+0.0001||Number(o.amount)>Number(ap.outstanding_amount||0)+0.0001)throw new Error('应收或应付余额不足，无法提交');const now=new Date().toISOString();await ctx.api.object('forge_counterparty_offset').update({id,status:'pending_review',submitted_at:now,reviewer_id:null,reviewed_at:null,review_comment:null});await ctx.api.object('forge_accounting_opening_log').insert({name:o.code+' 提交',event_key:o.code+'-SUBMIT-'+Date.now(),setup_id:null,offset_id:id,action:'offset_submitted',direction:'offset',source_id:id,amount:o.amount,comment:'提交财务审核',occurred_at:now,operator_id:actor});return{id,status:'pending_review'};
` },
});

export const CounterpartyOffsetApprove = defineAction({
  name: 'counterparty_offset_approve', label: '审核通过', objectName: 'forge_counterparty_offset', icon: 'badge-check', locations: [...locations], order: 20, visible: `record.status == 'pending_review'`, refreshAfter: true,
  params: [{ name: 'review_comment', label: '审核意见', type: 'textarea', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),o=ctx.record,actor=ctx.session&&ctx.session.userId,comment=String(ctx.input.review_comment||'').trim();if(ctx.recordLoadDenied===true||!id||!o)throw new Error('往来对冲单不存在或不可访问');if(!actor||!comment)throw new Error('审核人和审核意见不能为空');if(o.status!=='pending_review')throw new Error('仅待审核对冲单可以审核');const [ar,ap]=await Promise.all([ctx.api.object('forge_accounts_receivable').findOne({where:{id:o.receivable_id}}),ctx.api.object('forge_accounts_payable').findOne({where:{id:o.payable_id}})]);const amount=Math.round((Number(o.amount||0)+Number.EPSILON)*10000)/10000;if(!ar||!ap||amount>Number(ar.outstanding_amount||0)+0.0001||amount>Number(ap.outstanding_amount||0)+0.0001)throw new Error('应收或应付余额不足，无法审核');const round=v=>Math.round((Number(v)+Number.EPSILON)*10000)/10000,aro=round(Number(ar.outstanding_amount)-amount),apo=round(Number(ap.outstanding_amount)-amount),arOffset=round(Number(ar.offset_amount||0)+amount),apOffset=round(Number(ap.offset_amount||0)+amount),now=new Date().toISOString(),today=now.slice(0,10),arStatus=aro===0?'settled':(Number(ar.collected_amount||0)>0||arOffset>0?'partially_collected':(String(ar.due_on)<today?'overdue':'unpaid')),apStatus=apo===0?'settled':(Number(ap.paid_amount||0)>0||apOffset>0?'partially_paid':(String(ap.due_on||'9999-12-31')<today?'overdue':'unpaid'));await ctx.api.object('forge_accounts_receivable').update({id:ar.id,offset_amount:arOffset,outstanding_amount:aro,status:arStatus});await ctx.api.object('forge_accounts_payable').update({id:ap.id,offset_amount:apOffset,outstanding_amount:apo,status:apStatus});await ctx.api.object('forge_counterparty_offset').update({id,status:'approved',reviewer_id:actor,reviewed_at:now,review_comment:comment,reversed_by:null,reversed_at:null,reversal_reason:null});await ctx.api.object('forge_accounting_opening_log').insert({name:o.code+' 审核通过',event_key:o.code+'-APPROVE-'+Date.now(),setup_id:null,offset_id:id,action:'offset_approved',direction:'offset',source_id:id,amount,comment,occurred_at:now,operator_id:actor});return{id,status:'approved',receivable_outstanding:aro,payable_outstanding:apo};
` },
});

export const CounterpartyOffsetReject = defineAction({
  name: 'counterparty_offset_reject', label: '驳回', objectName: 'forge_counterparty_offset', icon: 'circle-x', locations: [...locations], order: 30, visible: `record.status == 'pending_review'`, refreshAfter: true,
  params: [{ name: 'review_comment', label: '驳回原因', type: 'textarea', required: true }], body: { language: 'js', capabilities: ['api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),o=ctx.record,actor=ctx.session&&ctx.session.userId,comment=String(ctx.input.review_comment||'').trim();if(ctx.recordLoadDenied===true||!id||!o)throw new Error('往来对冲单不存在或不可访问');if(!actor||!comment)throw new Error('审核人和驳回原因不能为空');if(o.status!=='pending_review')throw new Error('仅待审核对冲单可以驳回');const now=new Date().toISOString();await ctx.api.object('forge_counterparty_offset').update({id,status:'rejected',reviewer_id:actor,reviewed_at:now,review_comment:comment});await ctx.api.object('forge_accounting_opening_log').insert({name:o.code+' 驳回',event_key:o.code+'-REJECT-'+Date.now(),setup_id:null,offset_id:id,action:'offset_rejected',direction:'offset',source_id:id,amount:o.amount,comment,occurred_at:now,operator_id:actor});return{id,status:'rejected'};
` },
});

export const CounterpartyOffsetReverse = defineAction({
  name: 'counterparty_offset_reverse', label: '撤回已审核对冲', objectName: 'forge_counterparty_offset', icon: 'rotate-ccw', locations: [...locations], order: 40, visible: `record.status == 'approved'`, refreshAfter: true,
  params: [{ name: 'reversal_reason', label: '撤回原因', type: 'textarea', required: true }], body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),o=ctx.record,actor=ctx.session&&ctx.session.userId,reason=String(ctx.input.reversal_reason||'').trim();if(ctx.recordLoadDenied===true||!id||!o)throw new Error('往来对冲单不存在或不可访问');if(!actor||!reason)throw new Error('操作人和撤回原因不能为空');if(o.status!=='approved')throw new Error('仅已审核对冲单可以撤回');const peers=await ctx.api.object('forge_counterparty_offset').find({where:{receivable_id:o.receivable_id}}),later=peers.filter(x=>x.id!==id&&x.status==='approved'&&String(x.reviewed_at||'')>String(o.reviewed_at||''));if(later.length)throw new Error('请按审核时间从后向前撤回对冲');const [ar,ap]=await Promise.all([ctx.api.object('forge_accounts_receivable').findOne({where:{id:o.receivable_id}}),ctx.api.object('forge_accounts_payable').findOne({where:{id:o.payable_id}})]),amount=Math.round((Number(o.amount||0)+Number.EPSILON)*10000)/10000;if(!ar||!ap||Number(ar.offset_amount||0)<amount||Number(ap.offset_amount||0)<amount)throw new Error('当前往来账已对冲金额不足');const round=v=>Math.round((Number(v)+Number.EPSILON)*10000)/10000,aro=round(Number(ar.outstanding_amount||0)+amount),apo=round(Number(ap.outstanding_amount||0)+amount),arOffset=round(Number(ar.offset_amount||0)-amount),apOffset=round(Number(ap.offset_amount||0)-amount),now=new Date().toISOString(),today=now.slice(0,10),arStatus=aro===0?'settled':(Number(ar.collected_amount||0)>0||arOffset>0?'partially_collected':(String(ar.due_on)<today?'overdue':'unpaid')),apStatus=apo===0?'settled':(Number(ap.paid_amount||0)>0||apOffset>0?'partially_paid':(String(ap.due_on||'9999-12-31')<today?'overdue':'unpaid'));await ctx.api.object('forge_accounts_receivable').update({id:ar.id,offset_amount:arOffset,outstanding_amount:aro,status:arStatus});await ctx.api.object('forge_accounts_payable').update({id:ap.id,offset_amount:apOffset,outstanding_amount:apo,status:apStatus});await ctx.api.object('forge_counterparty_offset').update({id,status:'reversed',reversed_by:actor,reversed_at:now,reversal_reason:reason});await ctx.api.object('forge_accounting_opening_log').insert({name:o.code+' 撤回',event_key:o.code+'-REVERSE-'+Date.now(),setup_id:null,offset_id:id,action:'offset_reversed',direction:'offset',source_id:id,amount,comment:reason,occurred_at:now,operator_id:actor});return{id,status:'reversed',receivable_outstanding:aro,payable_outstanding:apo};
` },
});
