import { defineAction } from '@objectstack/spec';

const locations = ['record_header', 'record_more'] as const;

export const SubcontractReturnCreate = defineAction({
  name: 'subcontract_return_create', label: '创建委外退料单', objectName: 'forge_subcontract_order', icon: 'undo-2',
  locations: [...locations], order: 50, visible: `(record.status == 'approved' || record.status == 'in_progress') && record.supply_mode == 'customer_supplied'`,
  params: [
    { name: 'return_code', label: '退料单号', type: 'text', required: true },
    { name: 'return_on', label: '退料日期', type: 'date', required: true },
    { name: 'handler_id', label: '经办人 ID', type: 'text' },
    { name: 'reason_setting_id', label: '退料原因配置', type: 'text' },
    { name: 'reason', label: '退料原因', type: 'select', required: true, options: [{ value: 'excess_material', label: '余料退回' }, { value: 'engineering_change', label: '工程变更' }, { value: 'usable_scrap', label: '可用废料回收' }, { value: 'wrong_material', label: '错发退回' }, { value: 'other', label: '其他' }] },
    { name: 'lines_json', label: '退料明细 JSON', type: 'textarea', required: true },
    { name: 'remarks', label: '备注', type: 'textarea' },
  ],
  successMessage: '委外退料单草稿已创建',
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),order=ctx.record,actor=ctx.session&&ctx.session.userId;
if(ctx.recordLoadDenied===true||!id||!order)throw new Error('当前委外订单不存在或不可访问');if(!actor)throw new Error('无法识别当前经办人');
if(!['approved','in_progress'].includes(order.status)||order.supply_mode!=='customer_supplied')throw new Error('只有已审核且仍在执行的甲供料订单可以退料');
const code=String(ctx.input.return_code||'').trim(),returnOn=ctx.input.return_on,reason=String(ctx.input.reason||'').trim(),reasonSettingId=String(ctx.input.reason_setting_id||'').trim();if(!code||!returnOn||!reason)throw new Error('退料单号、退料日期和退料原因不能为空');
const reasonSettings=await ctx.api.object('forge_subcontract_business_setting').find({where:{category:'return_reason'}}),activeReasons=reasonSettings.filter(x=>x.enabled===true||x.enabled===1||x.enabled==='1');if(!activeReasons.length)throw new Error('请先在委外配置中启用至少一个退料原因');const reasonLabels={excess_material:'余料退回',engineering_change:'工程变更',usable_scrap:'可用废料回收',wrong_material:'错发退回',other:'其他'},reasonSetting=reasonSettingId?activeReasons.find(x=>x.id===reasonSettingId):activeReasons.find(x=>x.name===reasonLabels[reason]);if(!reasonSetting)throw new Error('退料原因已停用或不存在，请重新选择');
if((await ctx.api.object('forge_subcontract_return').find({where:{code}})).length)throw new Error('退料单号已存在');let requested;try{requested=JSON.parse(String(ctx.input.lines_json||'[]'));}catch(e){throw new Error('退料明细格式不正确');}if(!Array.isArray(requested)||!requested.length)throw new Error('至少需要一行退料明细');
const profile=await ctx.api.object('forge_subcontract_supplier_profile').findOne({where:{id:order.supplier_profile_id}});if(!profile||!profile.default_issue_warehouse_id)throw new Error('委外供应商未配置有效的退料入库仓');
const plans=await ctx.api.object('forge_subcontract_material_plan').find({where:{order_id:id}}),planMap={};for(const plan of plans)planMap[plan.id]=plan;const seen=new Set(),prepared=[];
for(const input of requested){const plan=planMap[input.plan_id],qty=Number(input.quantity||0);if(!plan||seen.has(plan.id))throw new Error('退料计划不存在、重复或不属于当前订单');seen.add(plan.id);if(!(qty>0))throw new Error((plan.item_code||plan.name)+' 退料数量必须大于 0');
 const stocks=await ctx.api.object('forge_subcontract_stock_balance').find({where:{balance_key:order.supplier_id+':'+id+':'+plan.sku_id}});if(stocks.length!==1)throw new Error((plan.item_code||plan.name)+' 委外厂库存余额不存在或重复');const stock=stocks[0];
 const prior=await ctx.api.object('forge_subcontract_return_line').find({where:{plan_id:plan.id}}),committed=prior.filter(x=>['draft','pending_inbound'].includes(x.status)).reduce((s,x)=>s+Number(x.requested_quantity||0),0),available=Math.round((Number(stock.on_hand_quantity||0)-committed+Number.EPSILON)*10000)/10000;if(qty>available)throw new Error((plan.item_code||plan.name)+' 退料数量超过当前在外余量 '+available);
 prepared.push({plan,qty,available,stock});}
const total=prepared.reduce((s,x)=>s+x.qty,0),amount=prepared.reduce((s,x)=>s+x.qty*Number(x.stock.unit_cost||0),0),created=await ctx.api.object('forge_subcontract_return').insert({name:code+' '+(order.name||''),code,order_id:id,supplier_id:order.supplier_id,return_on:returnOn,handler_id:ctx.input.handler_id||actor,warehouse_id:profile.default_issue_warehouse_id,reason_setting_id:reasonSetting.id,reason,line_count:prepared.length,total_quantity:total,total_amount:amount,status:'draft',responsible_id:order.responsible_id||actor,remarks:String(ctx.input.remarks||'').trim()||null}),returnId=typeof created==='string'?created:created&&(created.id||(created.record&&created.record.id));if(!returnId)throw new Error('退料单创建后未返回 ID');
const lineIds=[];for(const item of prepared){const saved=await ctx.api.object('forge_subcontract_return_line').insert({name:item.plan.name,return_id:returnId,order_id:id,plan_id:item.plan.id,sku_id:item.plan.sku_id,warehouse_id:profile.default_issue_warehouse_id,item_code:item.plan.item_code,specification:item.plan.specification||null,unit_name:item.plan.unit_name,available_quantity:item.available,requested_quantity:item.qty,confirmed_quantity:0,batch_number:null,unit_cost:Number(item.stock.unit_cost||0),amount:item.qty*Number(item.stock.unit_cost||0),status:'draft'}),lineId=typeof saved==='string'?saved:saved&&(saved.id||(saved.record&&saved.record.id));lineIds.push(lineId);}
await ctx.api.object('forge_subcontract_return_log').insert({name:code+' 保存草稿',return_id:returnId,action:'created',from_status:'',to_status:'draft',comment:'退料单草稿已保存',occurred_at:new Date().toISOString(),operator_id:actor});return{id:returnId,code,status:'draft',line_ids:lineIds,total_quantity:total,total_amount:amount};
` },
});

export const SubcontractReturnConfirm = defineAction({
  name: 'subcontract_return_confirm', label: '确认退料', objectName: 'forge_subcontract_return', icon: 'package-plus', locations: [...locations], order: 10, visible: `record.status == 'draft'`,
  params: [{ name: 'confirm_note', label: '确认说明', type: 'textarea', required: true }], successMessage: '退料已确认并生成待入库单',
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),record=ctx.record,actor=ctx.session&&ctx.session.userId,note=String(ctx.input.confirm_note||'').trim();if(ctx.recordLoadDenied===true||!id||!record)throw new Error('委外退料单不存在或不可访问');if(!actor)throw new Error('无法识别当前确认人');if(record.status!=='draft')throw new Error('退料单状态已变化，请刷新后重试');if(!note)throw new Error('确认说明不能为空');
const order=await ctx.api.object('forge_subcontract_order').findOne({where:{id:record.order_id}});if(!order||order.supply_mode!=='customer_supplied'||!['approved','in_progress'].includes(order.status))throw new Error('关联订单不再满足退料条件');const lines=await ctx.api.object('forge_subcontract_return_line').find({where:{return_id:id}});if(!lines.length)throw new Error('至少需要一行退料明细');
const prepared=[];for(const line of lines){const stocks=await ctx.api.object('forge_subcontract_stock_balance').find({where:{balance_key:record.supplier_id+':'+record.order_id+':'+line.sku_id}});if(stocks.length!==1)throw new Error((line.item_code||line.name)+' 委外厂库存余额不存在或重复');const stock=stocks[0],qty=Number(line.requested_quantity||0);if(!(qty>0)||qty>Number(stock.on_hand_quantity||0))throw new Error((line.item_code||line.name)+' 退料数量超过当前在外余量');prepared.push({line,stock,qty});}
const now=new Date().toISOString(),made=await ctx.api.object('forge_subcontract_return_inbound').insert({name:record.code+' 退料待入库',code:'RIN-'+record.code,return_id:id,order_id:record.order_id,supplier_id:record.supplier_id,warehouse_id:record.warehouse_id,total_quantity:prepared.reduce((s,x)=>s+x.qty,0),total_amount:prepared.reduce((s,x)=>s+x.qty*Number(x.stock.unit_cost||0),0),status:'pending',created_by:actor,created_at_business:now,remarks:note}),inboundId=typeof made==='string'?made:made&&(made.id||(made.record&&made.record.id));if(!inboundId)throw new Error('退料待入库单创建后未返回 ID');
for(const x of prepared){await ctx.api.object('forge_subcontract_return_inbound_line').insert({name:x.line.name,inbound_id:inboundId,return_line_id:x.line.id,order_id:record.order_id,plan_id:x.line.plan_id,sku_id:x.line.sku_id,warehouse_id:record.warehouse_id,item_code:x.line.item_code,specification:x.line.specification||null,unit_name:x.line.unit_name,quantity:x.qty,batch_number:x.line.batch_number||null,unit_cost:Number(x.stock.unit_cost||0),amount:x.qty*Number(x.stock.unit_cost||0),status:'pending'});await ctx.api.object('forge_subcontract_return_line').update({id:x.line.id,status:'pending_inbound',confirmed_quantity:x.qty});}
await ctx.api.object('forge_subcontract_return').update({id,status:'pending_inbound',inbound_id:inboundId,confirmed_by:actor,confirmed_at:now});await ctx.api.object('forge_subcontract_return_log').insert({name:record.code+' 确认退料',return_id:id,action:'confirmed',from_status:'draft',to_status:'pending_inbound',comment:note,occurred_at:now,operator_id:actor});return{id,status:'pending_inbound',inbound_id:inboundId,total_quantity:Number(record.total_quantity||0)};
` },
});

export const SubcontractReturnInboundConfirm = defineAction({
  name: 'subcontract_return_inbound_confirm', label: '确认退料入库', objectName: 'forge_subcontract_return_inbound', icon: 'warehouse', locations: [...locations], order: 10, visible: `record.status == 'pending'`,
  params: [{ name: 'stock_note', label: '入库说明', type: 'textarea', required: true }], successMessage: '退回物料已入库并更新委外库存',
  body: { language: 'js', capabilities: ['api.read', 'api.write'], source: `
const id=ctx.recordId||(ctx.record&&ctx.record.id),inbound=ctx.record,actor=ctx.session&&ctx.session.userId,note=String(ctx.input.stock_note||'').trim();if(ctx.recordLoadDenied===true||!id||!inbound)throw new Error('委外退料待入库单不存在或不可访问');if(!actor)throw new Error('无法识别当前入库人');if(inbound.status!=='pending')throw new Error('退料入库单状态已变化，请刷新后重试');if(!note)throw new Error('入库说明不能为空');const record=await ctx.api.object('forge_subcontract_return').findOne({where:{id:inbound.return_id}});if(!record||record.status!=='pending_inbound'||record.inbound_id!==id)throw new Error('关联退料单不再等待该入库单');
const lines=await ctx.api.object('forge_subcontract_return_inbound_line').find({where:{inbound_id:id}});if(!lines.length)throw new Error('退料入库单没有明细');const round=v=>Math.round((Number(v)+Number.EPSILON)*10000)/10000,now=new Date().toISOString();let total=0;
for(const line of lines){if(line.status!=='pending')throw new Error((line.item_code||line.name)+' 入库明细状态已变化');const stocks=await ctx.api.object('forge_subcontract_stock_balance').find({where:{balance_key:record.supplier_id+':'+record.order_id+':'+line.sku_id}});if(stocks.length!==1)throw new Error((line.item_code||line.name)+' 委外厂库存余额不存在或重复');const stock=stocks[0],qty=Number(line.quantity||0),before=Number(stock.on_hand_quantity||0);if(qty>before)throw new Error((line.item_code||line.name)+' 当前在外余量不足');const after=round(before-qty),value=round(Math.max(0,Number(stock.inventory_value||0)-qty*Number(stock.unit_cost||0)));
 await ctx.api.object('forge_subcontract_stock_balance').update({id:stock.id,returned_quantity:round(Number(stock.returned_quantity||0)+qty),on_hand_quantity:after,inventory_value:value,last_movement_at:now});await ctx.api.object('forge_subcontract_stock_ledger').insert({name:record.code+' '+line.name+' 余料退回',code:record.code+'-RET-'+String(lines.indexOf(line)+1).padStart(3,'0'),supplier_id:record.supplier_id,order_id:record.order_id,sku_id:line.sku_id,direction:'outbound',movement_type:'material_return',quantity:qty,before_on_hand:before,after_on_hand:after,unit_cost:Number(stock.unit_cost||0),amount:qty*Number(stock.unit_cost||0),occurred_at:now,source_object:'forge_subcontract_return',source_id:record.id,source_line_id:line.return_line_id,responsible_id:actor,remarks:note});await ctx.api.object('forge_subcontract_material_plan').update({id:line.plan_id,returned_quantity:round(Number((await ctx.api.object('forge_subcontract_material_plan').findOne({where:{id:line.plan_id}})).returned_quantity||0)+qty)});await ctx.api.object('forge_subcontract_return_inbound_line').update({id:line.id,status:'stocked'});await ctx.api.object('forge_subcontract_return_line').update({id:line.return_line_id,status:'stocked'});total=round(total+qty);}
await ctx.api.object('forge_subcontract_return_inbound').update({id,status:'stocked',stocked_by:actor,stocked_at:now});await ctx.api.object('forge_subcontract_return').update({id:record.id,status:'stocked',stocked_by:actor,stocked_at:now});await ctx.api.object('forge_subcontract_return_log').insert({name:record.code+' 完成退料入库',return_id:record.id,action:'stocked',from_status:'pending_inbound',to_status:'stocked',comment:note,occurred_at:now,operator_id:actor});return{id,status:'stocked',return_id:record.id,total_quantity:total};
` },
});
