import { defineHook } from '@objectstack/spec/data';
import { salesPricingHelpers } from '../actions/sales-pricing.source.js';

export const SalesApprovedPriceApply = defineHook({
  name: 'sales_approved_price_apply', object: 'forge_sales_price_request', events: ['afterUpdate'], priority: 200,
  condition: "previous.status == 'pending_approval' && record.status == 'approved'",
  async: false, onError: 'abort', timeoutMs: 30000,
  body: { language: 'js', capabilities: ['api.read', 'api.write', 'api.transaction'], timeoutMs: 30000, source: salesPricingHelpers + String.raw`
const previous=ctx.previous,id=text(ctx.input&&ctx.input.id||ctx.result&&ctx.result.id||previous&&previous.id),org=text(ctx.session&&ctx.session.organizationId||ctx.user&&ctx.user.organizationId);
if(!id||!org)throw new Error('无法确认价格申请和组织');
const conflict=message=>{throw new Error('PRICE_CONFLICT:'+message)};
try{await api.transaction(async()=>{const requests=api.object('forge_sales_price_request'),request=await requests.findOne({where:{id,organization_id:org}});if(!request||request.status!=='approved'||request.approval_status!=='approved')throw new Error('尚未形成原生审批通过结果');if(request.effect_status==='applied')return;if(request.effect_status!=='pending')return;
 const lines=await all('forge_sales_price_request_line',{request_id:id,organization_id:org});if(!lines.length||lines.length!==Number(request.item_count))throw new Error('已审批申请明细不完整');if(request.valid_until&&String(request.valid_until).slice(0,10)<today())conflict('申请有效期已结束，请重新申请');
 const targets=[];for(const line of lines){const sku=await api.object('forge_material_sku').findOne({where:{id:line.sku_id,organization_id:org}}),cursor=await api.object('forge_sales_price_cursor').findOne({where:{target_key:line.target_key,organization_id:org}});if(!sku||sku.enabled===false||baselineToken(sku)!==line.baseline_token||!cursor||Number(cursor.revision)!==Number(line.baseline_revision))conflict(line.name+'的价格在审批期间已变化，请重新申请');targets.push({line,sku,cursor})};
 const timestamp=new Date().toISOString();for(const {line,sku,cursor} of targets){const locked=await api.object('forge_sales_price_cursor').update({revision:Number(cursor.revision)+1},{where:{id:cursor.id,organization_id:org,revision:cursor.revision},multi:true});if(locked!==1)conflict(line.name+'已有另一笔价格审批生效，请重新申请');if(request.kind==='adjustment'){const where={id:sku.id,organization_id:org,sale_price:sku.sale_price??null,sale_price_revision:sku.sale_price_revision??null,...(sku.updated_at?{updated_at:sku.updated_at}:{})},changed=await api.object('forge_material_sku').update({sale_price:Number(line.proposed_price),minimum_sale_price:line.minimum_price??null,suggested_sale_price:line.suggested_price??null,sale_price_revision:Number(sku.sale_price_revision||0)+1},{where,multi:true});if(changed!==1)conflict(line.name+'的目录价已被其他操作修改，请重新申请')}
 await api.object('forge_sales_price_history').insert({name:line.name,request_id:id,request_line_id:line.id,request_code:request.code,sku_id:line.sku_id,material_code:line.material_code,specification:line.specification,unit_name:line.unit_name,kind:request.kind,customer_id:request.customer_id||null,customer_name:request.customer_name||'',original_price:line.original_price==null?null:Number(line.original_price),price:Number(line.proposed_price),minimum_price:line.minimum_price??null,suggested_price:line.suggested_price??null,quantity:Number(line.quantity),valid_from:request.kind==='adjustment'?today():request.valid_from,valid_until:request.valid_until||null,applied_at:timestamp,applied_by:request.submitted_by,reason:request.reason,price_revision:Number(cursor.revision)+1,owner_id:request.submitted_by,organization_id:org});}
 const changed=await requests.update({effect_status:'applied',effect_message:'',applied_at:timestamp,revision:Number(request.revision)+1},{where:{id,organization_id:org,status:'approved',effect_status:'pending',revision:request.revision},multi:true});if(changed!==1)conflict('申请执行状态已变化，请核对生效结果');});}
catch(error){const message=String(error&&error.message||error);if(!message.startsWith('PRICE_CONFLICT:'))throw error;await api.object('forge_sales_price_request').update({effect_status:'conflict',effect_message:message.slice(15)},{where:{id,organization_id:org,status:'approved',effect_status:'pending'},multi:true});}
` },
});
