import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
.forge-inventory-ncr .ncr-filter{display:grid;grid-template-columns:minmax(280px,1fr) repeat(4,170px);gap:10px;padding:14px 16px;border-bottom:1px solid var(--fp-line)}.forge-inventory-ncr .fp-table{min-width:1380px}.forge-inventory-ncr .ncr-source{color:var(--fp-muted);font-size:12px;margin-top:3px}.forge-inventory-ncr .ncr-action{display:flex;gap:8px;align-items:center}@media(max-width:1000px){.forge-inventory-ncr .ncr-filter{grid-template-columns:1fr 1fr}}@media(max-width:620px){.forge-inventory-ncr .ncr-filter{grid-template-columns:1fr}}
`;

const source = `
const statusText={draft:'待提交',pending_approval:'审批中',approved:'已通过',rejected:'已驳回',executed:'已执行',cancelled:'已作废',pending:'待处理',completed:'已完成'},dispText={return:'退货',concession:'特采',scrap:'报废',rework:'返工'},levelText={critical:'致命',major:'严重',minor:'轻微'};
function App(){
 const [state,setState]=React.useState({loading:true,error:'',rows:[]}),[query,setQuery]=React.useState(''),[status,setStatus]=React.useState(''),[sourceType,setSourceType]=React.useState(''),[disposition,setDisposition]=React.useState(''),[defect,setDefect]=React.useState(''),[toast,setToast]=React.useState('');
 async function request(path){const response=await fetch('/api/v1'+path,{credentials:'include'}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||payload.message||'读取失败');return payload}async function find(name){return(await request('/data/'+name+'?$top=500')).records||[]}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const [ncrs,inspections,receipts,orders,suppliers,inbounds,purchaseInbounds]=await Promise.all(['forge_subcontract_ncr','forge_purchase_inspection','forge_subcontract_receipt','forge_purchase_order','forge_supplier','forge_subcontract_ncr_inbound','forge_purchase_inbound'].map(find)),supplierMap=Object.fromEntries(suppliers.map(x=>[x.id,x])),receiptMap=Object.fromEntries(receipts.map(x=>[x.id,x])),orderMap=Object.fromEntries(orders.map(x=>[x.id,x])),inboundMap=Object.fromEntries(inbounds.map(x=>[x.id,x])),purchaseInboundByInspection=Object.fromEntries(purchaseInbounds.filter(x=>x.inspection_id).map(x=>[x.inspection_id,x]));const rows=[...ncrs.map(x=>({...x,_kind:'subcontract',_source:'委外回厂',_sourceNo:receiptMap[x.receipt_id]?.code||x.source_no||'—',_supplier:supplierMap[x.supplier_id]?.name||'—',_material:(x.item_code||'—')+' · '+(x.name||x.specification||'—'),_qty:Number(x.defective_quantity||0),_level:levelText[x.defect_level]||'待判定',_defect:x.defect_type||x.defect_description||'回厂验收异常',_disposition:dispText[x.disposition]||'待设置',_status:statusText[x.status]||x.status,_inbound:inboundMap[x.inbound_id]?.code||'—',_href:forgeBase+'/page/page_subcontract_ncr_workspace'})),...inspections.filter(x=>Number(x.rejected_quantity||0)>0).map(x=>({...x,_kind:'purchase',_source:'来料检验',_sourceNo:orderMap[x.order_id]?.code||x.receipt_id||'—',_supplier:supplierMap[x.supplier_id]?.name||'—',_material:(x.item_code||'—')+' · '+(x.name||x.model||x.specification||'—'),_qty:Number(x.rejected_quantity||0),_level:'待判定',_defect:x.inspection_note||'采购检验不合格',_disposition:'待来源处理',_status:x.status==='completed'?'已检验':'待检验',_inbound:purchaseInboundByInspection[x.id]?.code||'—',_href:forgeBase+'/page/page_purchase_inspection_workspace?id='+encodeURIComponent(x.id)}))].sort((a,b)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at)));setState({loading:false,error:'',rows})}catch(error){setState(s=>({...s,loading:false,error:String(error.message||error)}))}}
 React.useEffect(()=>{load()},[]);
 const filtered=state.rows.filter(x=>(!query.trim()||[x.code,x._source,x._sourceNo,x._material,x._supplier,x._defect,x._disposition,x._status].join(' ').toLowerCase().includes(query.trim().toLowerCase()))&&(!status||x.status===status)&&(!sourceType||x._kind===sourceType)&&(!disposition||x.disposition===disposition)&&(!defect||x.defect_level===defect));
 function exportRows(){const values=[['NCR 单号','业务来源','来源单据','物料','供应商','不合格数量','缺陷等级','处置方案','状态','关联入库单'],...filtered.map(x=>[x.code,x._source,x._sourceNo,x._material,x._supplier,x._qty,x._level,x._disposition,x._status,x._inbound])],body=values.map(line=>line.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\\ufeff'+body],{type:'text/csv;charset=utf-8'}));a.download='不合格处理.csv';a.click();URL.revokeObjectURL(a.href);setToast('已导出 '+filtered.length+' 条不合格记录')}
 if(state.loading)return <div className="forge-product forge-inventory-ncr"><style>{${JSON.stringify(css)}}</style><div className="fp-shell"><ForgeLoading label="正在加载不合格处理"/></div></div>;
 return <div className="forge-product forge-inventory-ncr"><style>{${JSON.stringify(css)}}</style><div className="fp-shell"><ForgeHero section="供应链 / 库存管理 / 不合格处理" title="不合格处理" description={'处理来料/在线/客退异常物料，共 '+state.rows.length+' 条记录'} icon="▤" tone="blue" art="blueprint"/><div className="fp-action-row"><button className="fp-button" onClick={exportRows}>导出</button><ForgeListSettings/><button className="fp-icon-button" aria-label="刷新" title="刷新" onClick={load}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 3v6h-6"/></svg></button></div>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<div className="fp-toast" role="status">{toast}</div>}<section className="fp-card"><div className="ncr-filter"><input className="fp-input" aria-label="搜索不合格记录" placeholder="搜索 NCR、来源单据、物料或供应商" value={query} onChange={e=>setQuery(e.target.value)}/><ForgeSelect label="状态" value={status} placeholder="全部状态" options={[{value:'',label:'全部状态'},...Object.entries(statusText).map(([value,label])=>({value,label}))]} onChange={setStatus}/><ForgeSelect label="业务来源" value={sourceType} placeholder="全部来源" options={[{value:'',label:'全部来源'},{value:'purchase',label:'来料检验'},{value:'subcontract',label:'委外回厂'}]} onChange={setSourceType}/><ForgeSelect label="处置" value={disposition} placeholder="全部处置" options={[{value:'',label:'全部处置'},...Object.entries(dispText).map(([value,label])=>({value,label}))]} onChange={setDisposition}/><ForgeSelect label="缺陷" value={defect} placeholder="全部缺陷" options={[{value:'',label:'全部缺陷'},...Object.entries(levelText).map(([value,label])=>({value,label}))]} onChange={setDefect}/></div><div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>NCR 单号</th><th>业务来源 / 来源单</th><th>物料</th><th>供应商</th><th>不合格数量</th><th>缺陷等级</th><th>处置方案</th><th>审批 / 执行状态</th><th>关联入库单</th><th>操作</th></tr></thead><tbody>{filtered.map(x=><tr key={x._kind+'-'+x.id}><td><strong>{x.code}</strong></td><td>{x._source}<div className="ncr-source">{x._sourceNo}</div></td><td>{x._material}</td><td>{x._supplier}</td><td>{x._qty} {x.unit_name||''}</td><td>{x._level}<div className="ncr-source">{x._defect}</div></td><td>{x._disposition}</td><td><ForgeStatus value={x.status} label={x._status}/></td><td>{x._inbound}</td><td><div className="ncr-action"><button className="fp-link-button" onClick={()=>window.location.href=x._href}>{x._kind==='subcontract'&&x.status!=='executed'?'办理':'查看'}</button></div></td></tr>)}{!filtered.length&&<tr><td colSpan="10" className="fp-empty-cell"><ForgeEmpty title="暂无不合格单" description="请调整筛选条件，或从采购检验、委外回厂登记异常。"/></td></tr>}</tbody></table></div><div className="fp-pagination"><span>共 {filtered.length} 条记录</span><span>每页 20 条 · 1 / 1</span></div></section></div></div>}
export default App;
${forgeProductUiRuntime}
`;

export const InventoryNcrPage = { name:'page_inventory_ncr', label:'不合格处理', description:'处理来料、在线与委外回厂异常物料', icon:'triangle-alert', type:'app' as const, kind:'react' as const, source };
