import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const css = forgeProductUiCss + `
div:has(>.forge-purchase-request){max-width:none!important;margin:0!important}
div:has(>.forge-purchase-request)>div.space-y-2{display:none!important}
main:has(.forge-purchase-request)>div{padding:0!important}
.forge-purchase-request .fp-shell{width:min(1480px,100%);max-width:none}
.pr-next{display:flex;align-items:center;gap:7px}
.pr-tabs{display:flex;gap:24px;border-bottom:1px solid var(--fp-line);padding:0 16px}
.pr-filter{display:grid;grid-template-columns:minmax(200px,1fr) 190px minmax(380px,auto) auto;gap:9px 10px;padding:13px 16px;border-bottom:1px solid var(--fp-line)}
.pr-table{min-width:1540px}.pr-table th:first-child,.pr-table td:first-child{position:sticky;left:0;z-index:2;background:#fff}.pr-table th:first-child{z-index:4;background:#f8f9fc}.pr-table th:last-child,.pr-table td:last-child{position:sticky;right:0;z-index:2;background:#fff;box-shadow:-6px 0 10px rgba(16,24,40,.04)}.pr-table th:last-child{z-index:4;background:#f8f9fc}.pr-range{display:flex;align-items:center;gap:6px;height:36px;padding:0 10px;border:1px solid var(--fp-line-strong);border-radius:8px;background:#fff;min-width:250px}.pr-range-label{color:var(--fp-muted);font-size:12px;white-space:nowrap}.pr-range-sep{color:var(--fp-muted)}.pr-range .fp-date-picker{flex:1 1 150px;min-width:150px}.pr-table td:nth-child(2),.pr-table td:nth-child(13),.pr-table td:nth-child(14){max-width:200px;white-space:normal;word-break:break-word}.pr-actions{display:flex;align-items:center;gap:7px;white-space:nowrap}.forge-purchase-request .pr-table td.fp-empty-cell .fp-empty{position:sticky;right:0;width:min(100%,340px);margin:0 auto}
.pr-priority{display:inline-flex;gap:6px}.pr-priority button{height:32px;border:1px solid var(--fp-line-strong);border-radius:7px;background:#fff;padding:0 13px}.pr-priority button.active{border-color:var(--fp-primary);background:var(--fp-primary-soft);color:var(--fp-primary);font-weight:650}
.pr-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px 15px}.pr-wide{grid-column:1/-1}
.pr-entry-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:8px 0}
.pr-paste{padding:12px;border:1px solid var(--fp-line);border-radius:9px;background:var(--fp-soft)}
.pr-line-list{display:grid;gap:9px;margin-top:8px}.pr-line{display:grid;grid-template-columns:minmax(260px,1fr) 100px 120px 90px auto;gap:8px;align-items:end;padding:11px;border:1px solid var(--fp-line);border-radius:9px}.pr-manual-grid{display:grid;grid-template-columns:repeat(5,minmax(105px,1fr));gap:8px}.pr-line-total{padding-bottom:9px;color:var(--fp-muted);font-size:12px}.pr-submit-row{display:flex;justify-content:flex-end;padding-top:12px;border-top:1px solid var(--fp-line)}
.pr-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:13px}.pr-summary>div{padding:11px;border:1px solid var(--fp-line);border-radius:8px}.pr-summary span{display:block;color:var(--fp-muted);font-size:11px}.pr-summary strong{display:block;margin-top:3px}.pr-detail-lines{max-height:280px;overflow:auto}
@media(max-width:1280px){.pr-filter{grid-template-columns:minmax(200px,1fr) 190px}.pr-filter .pr-range{grid-column:1/2;min-width:0}.pr-filter button:last-child{grid-column:2/3;justify-self:end;align-self:center}}@media(max-width:1050px){.pr-filter{grid-template-columns:1fr 1fr}.pr-filter>*:first-child{grid-column:1/-1}.pr-filter .pr-range,.pr-filter button:last-child{grid-column:1/-1;justify-self:stretch}.pr-form{grid-template-columns:1fr}.pr-wide{grid-column:auto}.pr-line{grid-template-columns:1fr 1fr}.pr-line>*:first-child{grid-column:1/-1}.pr-manual-grid{grid-template-columns:1fr 1fr}.pr-summary{grid-template-columns:1fr 1fr}}
@media(max-width:760px){.pr-filter,.pr-line,.pr-manual-grid,.pr-summary{grid-template-columns:1fr}.pr-filter>*:first-child,.pr-line>*:first-child{grid-column:auto}.pr-actions{flex-wrap:wrap}}
`;

const source = `
${forgeProductUiRuntime}
const css=${JSON.stringify(css)};
const statusText={draft:'草稿',pending_approval:'审批中',approved:'已通过',rejected:'已驳回',converted:'已转采购',cancelled:'已取消'};
const priorityText={high:'高',medium:'中',low:'低'},currencyText={cny:'人民币',usd:'美元',eur:'欧元'};
function App(){const adapter=useAdapter();
 const today=new Date(Date.now()+8*60*60*1000).toISOString().slice(0,10);
 const newLine=(entry_mode='library')=>({entry_mode,sku_id:'',name:'',model:'',specification:'',category_name:'',unit_name:'台',quantity:'1',taxed_unit_price:'0',tax_rate:'13'});
 const emptyForm=()=>({id:'',code:'PR-'+Date.now(),name:'',priority:'medium',project_id:'',customer_id:'',responsible_id:'',suggested_supplier_id:'',currency:'cny',request_on:today,expected_arrival_on:'',purchase_reason:'',remarks:'',lines:[],pasteOpen:false,pasteText:''});
 const [state,setState]=React.useState({loading:true,error:'',requests:[],lines:[],projects:[],customers:[],suppliers:[],users:[],skus:[],materials:[],units:[],logs:[]});
 const [view,setView]=React.useState('requests'),[query,setQuery]=React.useState(''),[status,setStatus]=React.useState(''),[start,setStart]=React.useState(''),[end,setEnd]=React.useState(''),[page,setPage]=React.useState(1),[dialog,setDialog]=React.useState(null),[busy,setBusy]=React.useState(false),[toast,setToast]=React.useState('');
 async function request(path,options={}){const r=await ForgeApiResponse(adapter,path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error((typeof p.error==='string'?p.error:p.error?.message)||(Array.isArray(p.fields)&&p.fields.length?p.fields.map(f=>f.message||f.label).filter(Boolean).join('；'):'')||p.message||'请求失败');return p}
 async function find(name){return(await request('/data/'+name+'?$top=500')).records||[]}
 function createdId(p){return p.id||p.record?.id||p.data?.id}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const names=['forge_purchase_request','forge_purchase_request_line','forge_project','forge_customer','forge_supplier','sys_user','forge_material_sku','forge_material','forge_unit','forge_purchase_request_approval_log'],sets=await Promise.all(names.map(find)),d=Object.fromEntries(names.map((n,i)=>[n,sets[i]]));setState({loading:false,error:'',requests:d.forge_purchase_request,lines:d.forge_purchase_request_line,projects:d.forge_project,customers:d.forge_customer,suppliers:d.forge_supplier,users:d.sys_user,skus:d.forge_material_sku,materials:d.forge_material,units:d.forge_unit,logs:d.forge_purchase_request_approval_log})}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}))}}
 React.useEffect(()=>{load()},[]);React.useEffect(()=>{setPage(1)},[view,query,status,start,end]);React.useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
 const by=(rows,id)=>rows.find(x=>x.id===id),materialOf=skuId=>by(state.materials,by(state.skus,skuId)?.material_id),skuText=id=>{const s=by(state.skus,id),m=materialOf(id);return s&&m?m.code+' · '+m.name+' · '+s.name:'—'},unitName=id=>by(state.units,materialOf(id)?.unit_id)?.name||'',money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),qty=v=>Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:4}),person=id=>{const x=by(state.users,id);return x?.display_name||x?.name||x?.username||'—'},nameOf=(rows,id)=>by(rows,id)?.name||'—';
 const requestLines=id=>state.lines.filter(x=>x.request_id===id),requestCount=x=>requestLines(x.id).length,requestQuantity=x=>requestLines(x.id).reduce((sum,line)=>sum+Number(line.quantity||0),0),lineAmount=x=>Number(x.quantity||0)*Number(x.taxed_unit_price||0),requestAmount=x=>requestLines(x.id).reduce((sum,line)=>sum+Number(line.taxed_subtotal||lineAmount(line)),0),withTotals=x=>({...x,line_count:requestCount(x),total_quantity:requestQuantity(x),estimated_taxed_amount:requestAmount(x)});
 const q=query.trim().toLowerCase(),filtered=state.requests.filter(x=>(!status||x.status===status)&&(!start||x.request_on>=start)&&(!end||x.request_on<=end)&&(!q||[x.code,x.name,nameOf(state.projects,x.project_id),nameOf(state.customers,x.customer_id),nameOf(state.suppliers,x.suggested_supplier_id),x.purchase_reason].some(v=>String(v||'').toLowerCase().includes(q)))),filteredLines=state.lines.filter(x=>filtered.some(r=>r.id===x.request_id)),pageSize=20,allRows=view==='requests'?filtered:filteredLines,pageCount=Math.max(1,Math.ceil(allRows.length/pageSize)),safePage=Math.min(page,pageCount),rows=allRows.slice((safePage-1)*pageSize,safePage*pageSize);
 function openNew(paste=false){const f=emptyForm();f.code=forgeDocCode('PR',state.requests.map(x=>x.code),today);f.responsible_id=state.users[0]?.id||'';f.pasteOpen=paste;setDialog({kind:'form',form:f,error:''})}
 function openEdit(row){setDialog({kind:'form',form:{...row,pasteOpen:false,pasteText:'',lines:state.lines.filter(x=>x.request_id===row.id).map(x=>({id:x.id,entry_mode:x.entry_mode||'library',sku_id:x.sku_id||'',name:x.name||'',model:x.model||'',specification:x.specification||'',category_name:x.category_name||'',unit_name:x.unit_name||'',quantity:String(x.quantity),taxed_unit_price:String(x.taxed_unit_price||0),tax_rate:String(x.tax_rate??13)}))},error:''})}
 function setForm(patch){setDialog(d=>({...d,form:{...d.form,...patch},error:''}))}function setLine(index,patch){setForm({lines:dialog.form.lines.map((x,i)=>i===index?{...x,...patch}:x)})}
 function validateForm(){const f=dialog.form;if(!String(f.code||'').trim()||!String(f.name||'').trim()||!f.expected_arrival_on||!f.responsible_id||!String(f.purchase_reason||'').trim())throw new Error('请填写申请编号、标题、期望到货日期、负责人和采购原因');if(!f.lines.length)throw new Error('至少添加一条采购明细');for(const line of f.lines){if(line.entry_mode==='library'&&!line.sku_id)throw new Error('请为物料库明细选择物料');if(line.entry_mode!=='library'&&(!String(line.name||'').trim()||!String(line.model||'').trim()||!String(line.category_name||'').trim()||!String(line.unit_name||'').trim()))throw new Error('手工明细请填写物料名称、型号、物料分类和单位');if(!(Number(line.quantity)>0)||Number(line.taxed_unit_price)<0||Number(line.tax_rate)<0)throw new Error('请填写正数数量、非负价格和税率')}}
 function applyPaste(){const input=String(dialog.form.pasteText||'').split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean),parsed=[];try{for(const [index,row] of input.entries()){const c=row.split(/[\\t,]/).map(x=>x.trim());if(c.length<6)throw new Error('第 '+(index+1)+' 行至少需要名称、型号、规格、分类、单位和数量');parsed.push({...newLine('paste'),name:c[0],model:c[1],specification:c[2],category_name:c[3],unit_name:c[4],quantity:c[5],taxed_unit_price:c[6]||'0',tax_rate:c[7]||'13'})}if(!parsed.length)throw new Error('请粘贴至少一行物料明细');setForm({lines:[...dialog.form.lines,...parsed],pasteOpen:false,pasteText:''});setToast('已添加 '+parsed.length+' 条粘贴明细')}catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}}
 async function saveDraft(submitAfter=false){setBusy(true);try{validateForm();const f=dialog.form,totalQuantity=f.lines.reduce((s,x)=>s+Number(x.quantity),0),totalAmount=f.lines.reduce((s,x)=>s+lineAmount(x),0),body={name:String(f.name).trim(),code:String(f.code).trim(),priority:f.priority,project_id:f.project_id||null,customer_id:f.customer_id||null,responsible_id:f.responsible_id,suggested_supplier_id:f.suggested_supplier_id||null,currency:f.currency,request_on:f.request_on,expected_arrival_on:f.expected_arrival_on,purchase_reason:String(f.purchase_reason).trim(),remarks:String(f.remarks||'').trim()||null,total_quantity:totalQuantity,estimated_taxed_amount:totalAmount,status:'draft'},result=await request('/data/forge_purchase_request'+(f.id?'/'+f.id:''),{method:f.id?'PATCH':'POST',body:JSON.stringify(body)}),id=f.id||createdId(result);if(!id)throw new Error('采购申请保存后未返回记录ID');if(f.id)for(const old of state.lines.filter(x=>x.request_id===id))await request('/data/forge_purchase_request_line/'+old.id,{method:'DELETE'});for(const line of f.lines){const sku=by(state.skus,line.sku_id),material=materialOf(line.sku_id),library=line.entry_mode==='library';await request('/data/forge_purchase_request_line',{method:'POST',body:JSON.stringify({name:library?(material?.name||sku?.name||'采购物料'):String(line.name).trim(),request_id:id,entry_mode:line.entry_mode||'library',sku_id:library?line.sku_id:null,item_code:library?(material?.code||sku?.code||''):'',model:library?(material?.model||''):String(line.model||'').trim(),specification:library?(sku?.name||''):String(line.specification||'').trim(),category_name:library?'':String(line.category_name||'').trim(),unit_name:library?unitName(line.sku_id):String(line.unit_name||'').trim(),quantity:Number(line.quantity),taxed_unit_price:Number(line.taxed_unit_price),tax_rate:Number(line.tax_rate),taxed_subtotal:lineAmount(line),expected_arrival_on:f.expected_arrival_on,suggested_supplier_id:f.suggested_supplier_id||null})})}if(submitAfter)await request('/actions/forge_purchase_request/purchase_request_submit/'+id,{method:'POST',body:JSON.stringify({params:{}})});setDialog(null);setToast(submitAfter?'采购申请已保存并提交审批':(f.id?'采购申请草稿已更新':'采购申请草稿已保存'));await load()}catch(e){setDialog(d=>({...d,error:String(e.message||e)}))}finally{setBusy(false)}}
 function ask(row,action,title,impact,danger=false){setDialog({kind:'confirm',row,action,title,impact,danger,comment:action==='purchase_request_approve'?'同意':'',error:''})}
 async function invoke(){const d=dialog,note=d.comment.trim();if(['purchase_request_approve','purchase_request_reject','purchase_request_cancel'].includes(d.action)&&!note)return setDialog({...d,error:d.action==='purchase_request_cancel'?'请填写取消原因':'请填写审批意见'});setBusy(true);try{const params=d.action==='purchase_request_cancel'?{cancel_reason:note}:{approval_comment:note};await request('/actions/forge_purchase_request/'+d.action+'/'+d.row.id,{method:'POST',body:JSON.stringify({params})});setDialog(null);setToast(d.title+'完成');await load()}catch(e){setDialog(x=>({...x,error:String(e.message||e)}))}finally{setBusy(false)}}
 function actions(row){const current=withTotals(row);return <div className="pr-actions"><button className="fp-icon-button row-action" aria-label="查看详情" title="查看详情" onClick={()=>setDialog({kind:'detail',row:current})}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.6-6 10-6 10 6 10 6-3.6 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button>{['draft','rejected'].includes(row.status)&&<button className="fp-icon-button row-action" aria-label="编辑" title="编辑" onClick={()=>openEdit(row)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/></svg></button>}{['draft','rejected'].includes(row.status)&&<button className="fp-button small primary" onClick={()=>ask(current,'purchase_request_submit','提交采购申请','提交后进入审批中，草稿内容将暂时不可编辑。')}>提交审批</button>}{row.status==='pending_approval'&&<><button className="fp-button small primary" onClick={()=>ask(current,'purchase_request_approve','审批通过采购申请','通过后进入采购待办池，可继续转询价或采购订单。')}>通过</button><button className="fp-button small danger" onClick={()=>ask(current,'purchase_request_reject','驳回采购申请','驳回后退回申请人修改，审批意见将保留。',true)}>驳回</button></>}{['draft','rejected'].includes(row.status)&&<button className="fp-button small danger" onClick={()=>ask(current,'purchase_request_cancel','取消采购申请','取消后申请及明细保留只读，不能恢复或继续提交。',true)}>取消</button>}{row.status==='approved'&&<button className="fp-button small primary" aria-label="进入采购待办" title="进入采购待办" onClick={()=>location.href='/_console/apps/com.inoforge.forge.supply-chain/page_purchase_todo_pool?request='+encodeURIComponent(row.id)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h13"/><path d="M13 6l6 6-6 6"/></svg></button>}</div>}
 function exportRows(){const head=view==='requests'?['申请编号','申请标题','优先级','关联项目','关联客户','负责人','物料数','总数量','预估含税金额','币种','期望到货日期','建议供应商','采购原因','备注','状态','申请日期']:['申请编号','明细来源','物料编码','物料名称','型号','规格','物料分类','数量','单位','预估含税单价','税率','预估含税小计'],body=view==='requests'?filtered.map(x=>[x.code,x.name,priorityText[x.priority],nameOf(state.projects,x.project_id),nameOf(state.customers,x.customer_id),person(x.responsible_id),requestCount(x),requestQuantity(x),requestAmount(x),currencyText[x.currency],x.expected_arrival_on,nameOf(state.suppliers,x.suggested_supplier_id),x.purchase_reason,x.remarks,statusText[x.status],x.request_on]):filteredLines.map(x=>{const r=by(state.requests,x.request_id);return[r?.code,x.entry_mode,x.item_code,x.name,x.model,x.specification,x.category_name,x.quantity,x.unit_name,x.taxed_unit_price,x.tax_rate,x.taxed_subtotal]}),csv=[head,...body].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\\ufeff'+csv],{type:'text/csv'}));a.download=view==='requests'?'采购申请.csv':'采购申请明细.csv';a.click();URL.revokeObjectURL(a.href);setToast('已导出 '+body.length+' 条记录')}
 if(state.loading)return <div className="forge-product forge-purchase-request"><style>{css}</style><ForgeLoading label="加载采购申请"/></div>;
 return <div className="forge-product forge-purchase-request"><style>{css}</style><div className="fp-shell">
    <ForgeHero section="供应链 / 采购管理 / 采购申请" title="采购申请" description="发起采购申请、审批流转、转询价或订单全流程跟踪" icon="▤" tone="blue" art="blueprint" next={{label:"采购待办池",href:'/_console/apps/com.inoforge.forge.supply-chain/page_purchase_todo_pool',title:"下一步操作 · 采购待办池"}}/><div className="fp-action-row"><button className="fp-button" onClick={exportRows}>导出</button><button className="fp-button" onClick={()=>openNew(true)}>批量导入</button><ForgeListSettings/><button className="fp-icon-button" aria-label="刷新" title="刷新" onClick={load}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 3v6h-6"/></svg></button><button className="fp-button primary" onClick={()=>openNew(false)}>新建申请</button></div>
  {state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{toast&&<div className="fp-toast" role="status">{toast}</div>}
  <section className="fp-card"><div className="pr-tabs" role="tablist"><button className={'fp-tab '+(view==='requests'?'active':'')} onClick={()=>setView('requests')}>申请列表</button><button className={'fp-tab '+(view==='lines'?'active':'')} onClick={()=>setView('lines')}>物料明细</button></div><div className="pr-filter"><input className="fp-input" aria-label="搜索采购申请" placeholder="搜索申请编号、标题、项目、客户或供应商" value={query} onChange={e=>setQuery(e.target.value)}/><ForgeSelectControl aria-label="采购申请状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{Object.entries(statusText).map(([v,l])=><option key={v} value={v}>{l}</option>)}</ForgeSelectControl><label className="pr-range"><span className="pr-range-label">申请日期</span><ForgeDateInput aria-label="申请开始日期" value={start} onChange={e=>setStart(e.target.value)}/><span className="pr-range-sep">~</span><ForgeDateInput aria-label="申请结束日期" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="fp-button" onClick={()=>{setQuery('');setStatus('');setStart('');setEnd('')}}>清空筛选</button></div>
  {view==='requests'?<div className="fp-table-wrap"><table className="fp-table pr-table"><thead><tr><th>申请编号</th><th>申请标题</th><th>优先级</th><th>关联项目</th><th>关联客户</th><th>负责人</th><th>物料数</th><th>总数量</th><th>预估含税金额</th><th>币种</th><th>期望到货日期</th><th>建议供应商</th><th>采购原因</th><th>备注</th><th>状态</th><th>申请日期</th><th>操作</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name}</td><td>{priorityText[x.priority]||x.priority}</td><td>{nameOf(state.projects,x.project_id)}</td><td>{nameOf(state.customers,x.customer_id)}</td><td>{person(x.responsible_id)}</td><td>{requestCount(x)}</td><td>{qty(requestQuantity(x))}</td><td>{money(requestAmount(x))}</td><td>{currencyText[x.currency]||x.currency}</td><td>{x.expected_arrival_on}</td><td>{nameOf(state.suppliers,x.suggested_supplier_id)}</td><td>{x.purchase_reason}</td><td>{x.remarks||'—'}</td><td><ForgeStatus value={x.status} label={statusText[x.status]||x.status}/></td><td>{x.request_on}</td><td>{actions(x)}</td></tr>)}{!rows.length&&<tr><td colSpan="17" className="fp-empty-cell"><ForgeEmpty title="暂无采购申请" description="点击“新建申请”发起采购需求。" action={<button className="fp-button primary" onClick={()=>openNew(false)}>新建申请</button>}/></td></tr>}</tbody></table></div>:<div className="fp-table-wrap"><table className="fp-table" style={{minWidth:1280}}><thead><tr><th>申请编号</th><th>明细来源</th><th>物料编码</th><th>物料名称</th><th>型号</th><th>规格</th><th>物料分类</th><th>数量</th><th>单位</th><th>含税单价</th><th>税率</th><th>含税小计</th><th>期望到货日期</th></tr></thead><tbody>{rows.map(x=>{const r=by(state.requests,x.request_id);return <tr key={x.id}><td>{r?.code||'—'}</td><td>{x.entry_mode==='library'?'物料库':x.entry_mode==='paste'?'快速粘贴':'手动录入'}</td><td>{x.item_code||'—'}</td><td>{x.name}</td><td>{x.model||'—'}</td><td>{x.specification||'—'}</td><td>{x.category_name||'—'}</td><td>{qty(x.quantity)}</td><td>{x.unit_name||'—'}</td><td>{money(x.taxed_unit_price)}</td><td>{Number(x.tax_rate||0)}%</td><td>{money(x.taxed_subtotal)}</td><td>{x.expected_arrival_on||r?.expected_arrival_on}</td></tr>})}{!rows.length&&<tr><td colSpan="13" className="fp-empty-cell"><ForgeEmpty title="暂无采购明细" description="采购申请保存后，物料明细会显示在这里。"/></td></tr>}</tbody></table></div>}
  <div className="fp-pagination"><span>共 {allRows.length} 条记录 · 每页 20 条</span><button className="fp-button small" disabled={safePage<=1} onClick={()=>setPage(x=>x-1)}>上一页</button><span>{safePage} / {pageCount}</span><button className="fp-button small" disabled={safePage>=pageCount} onClick={()=>setPage(x=>x+1)}>下一页</button></div></section></div>
  {dialog?.kind==='form'&&<ForgeDialog open title={dialog.form.id?'编辑采购申请草稿':'新建采购申请'} subtitle="直接新建 · 可保存草稿或保存后直接提交审批" error={dialog.error} busy={busy} confirmLabel="保存并提交审批" onCancel={()=>!busy&&setDialog(null)} onConfirm={()=>saveDraft(true)}><div className="pr-form">
   <div className="fp-field"><label>采购申请单号 *</label><input className="fp-input" aria-label="采购申请单号" value={dialog.form.code} onChange={e=>setForm({code:e.target.value})}/></div><div className="fp-field"><label>申请标题 *</label><input className="fp-input" aria-label="采购申请标题" value={dialog.form.name} onChange={e=>setForm({name:e.target.value})}/></div>
   <div className="fp-field pr-wide"><label>优先级</label><div className="pr-priority">{[['high','高'],['medium','中'],['low','低']].map(([v,l])=><button type="button" className={dialog.form.priority===v?'active':''} key={v} onClick={()=>setForm({priority:v})}>{l}</button>)}</div></div>
   <div className="fp-field"><label>关联项目</label><ForgeSelectControl aria-label="采购申请项目" value={dialog.form.project_id} onChange={e=>setForm({project_id:e.target.value})}><option value="">不关联项目</option>{state.projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>关联客户</label><ForgeSelectControl aria-label="采购申请客户" value={dialog.form.customer_id} onChange={e=>setForm({customer_id:e.target.value})}><option value="">不关联客户</option>{state.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div>
   <div className="fp-field"><label>币种 *</label><ForgeSelectControl aria-label="采购申请币种" value={dialog.form.currency} onChange={e=>setForm({currency:e.target.value})}><option value="cny">人民币 (CNY)</option><option value="usd">美元 (USD)</option><option value="eur">欧元 (EUR)</option></ForgeSelectControl></div><div className="fp-field"><label>申请日期</label><ForgeDateInput aria-label="采购申请日期" value={dialog.form.request_on} disabled/></div>
   <div className="fp-field"><label>期望到货日期 *</label><ForgeDateInput aria-label="采购申请期望到货日期" value={dialog.form.expected_arrival_on} min={today} onChange={e=>setForm({expected_arrival_on:e.target.value})}/></div><div className="fp-field"><label>负责人 *</label><ForgeSelectControl aria-label="采购申请负责人" value={dialog.form.responsible_id} onChange={e=>setForm({responsible_id:e.target.value})}><option value="">请选择负责人</option>{state.users.map(x=><option key={x.id} value={x.id}>{person(x.id)}</option>)}</ForgeSelectControl></div>
   <div className="fp-field"><label>建议供应商</label><ForgeSelectControl aria-label="采购申请建议供应商" value={dialog.form.suggested_supplier_id} onChange={e=>setForm({suggested_supplier_id:e.target.value})}><option value="">暂不指定</option>{state.suppliers.filter(x=>x.status==='active').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ForgeSelectControl></div><div className="fp-field pr-wide"><label>采购原因 *</label><textarea className="fp-textarea" aria-label="采购申请原因" value={dialog.form.purchase_reason} onChange={e=>setForm({purchase_reason:e.target.value})}/></div><div className="fp-field pr-wide"><label>备注</label><textarea className="fp-textarea" aria-label="采购申请备注" maxLength="500" value={dialog.form.remarks||''} onChange={e=>setForm({remarks:e.target.value})}/></div>
   <div className="pr-wide"><ForgeNotice tone="info">附件存储尚未接入，因此不展示无结果上传控件；其余申请与明细功能可直接办理。</ForgeNotice></div>
   <div className="fp-field pr-wide"><label>采购明细 *　{dialog.form.lines.length} 项</label><div className="pr-entry-tools"><button type="button" className="fp-button" onClick={()=>setForm({lines:[...dialog.form.lines,newLine('library')]})}>从物料库选择</button><button type="button" className="fp-button" onClick={()=>setForm({lines:[...dialog.form.lines,newLine('manual')]})}>手动添加</button><button type="button" className="fp-button" onClick={()=>setForm({pasteOpen:!dialog.form.pasteOpen})}>快速粘贴</button></div>
   {dialog.form.pasteOpen&&<div className="pr-paste"><div className="fp-field"><label>每行：物料名称、型号、规格、物料分类、单位、数量、含税单价、税率</label><textarea className="fp-textarea" aria-label="快速粘贴采购明细" rows="5" value={dialog.form.pasteText} onChange={e=>setForm({pasteText:e.target.value})} placeholder={'PLC模块\t6ES7-215\t14DI/10DO\t电气元件\t件\t2\t6800\t13'}/></div><button type="button" className="fp-button primary" onClick={applyPaste}>识别并添加</button></div>}
   <div className="pr-line-list">{dialog.form.lines.map((line,index)=><div className="pr-line" key={index}><div>{line.entry_mode==='library'?<div className="fp-field"><label>物料库物料 *</label><ForgeSelectControl aria-label={'采购申请物料 '+(index+1)} value={line.sku_id} onChange={e=>{const sku=by(state.skus,e.target.value);setLine(index,{sku_id:e.target.value,taxed_unit_price:String(sku?.cost_price||0)})}}><option value="">请选择物料</option>{state.skus.filter(x=>x.enabled!==false).map(x=><option key={x.id} value={x.id}>{skuText(x.id)}</option>)}</ForgeSelectControl></div>:<div className="pr-manual-grid"><div className="fp-field"><label>物料名称 *</label><input className="fp-input" aria-label={'手工物料名称 '+(index+1)} value={line.name} onChange={e=>setLine(index,{name:e.target.value})}/></div><div className="fp-field"><label>型号 *</label><input className="fp-input" aria-label={'手工型号 '+(index+1)} value={line.model} onChange={e=>setLine(index,{model:e.target.value})}/></div><div className="fp-field"><label>规格</label><input className="fp-input" aria-label={'手工规格 '+(index+1)} value={line.specification} onChange={e=>setLine(index,{specification:e.target.value})}/></div><div className="fp-field"><label>物料分类 *</label><input className="fp-input" aria-label={'手工物料分类 '+(index+1)} value={line.category_name} onChange={e=>setLine(index,{category_name:e.target.value})}/></div><div className="fp-field"><label>单位 *</label><input className="fp-input" aria-label={'手工单位 '+(index+1)} value={line.unit_name} onChange={e=>setLine(index,{unit_name:e.target.value})}/></div></div>}</div><div className="fp-field"><label>数量 *</label><input className="fp-input" aria-label={'采购数量 '+(index+1)} inputMode="decimal" value={line.quantity} onChange={e=>setLine(index,{quantity:e.target.value})}/></div><div className="fp-field"><label>含税单价</label><input className="fp-input" aria-label={'采购含税单价 '+(index+1)} inputMode="decimal" value={line.taxed_unit_price} onChange={e=>setLine(index,{taxed_unit_price:e.target.value})}/></div><div className="fp-field"><label>税率 %</label><input className="fp-input" aria-label={'采购税率 '+(index+1)} inputMode="decimal" value={line.tax_rate} onChange={e=>setLine(index,{tax_rate:e.target.value})}/></div><div><div className="pr-line-total">小计 {money(lineAmount(line))}</div><button type="button" className="fp-button small danger" onClick={()=>setForm({lines:dialog.form.lines.filter((_,i)=>i!==index)})}>删除</button></div></div>)}{!dialog.form.lines.length&&<ForgeEmpty title="暂无采购明细" description="可从物料库选择、手动添加或快速粘贴。"/>}</div></div>
   <div className="pr-wide pr-submit-row"><button type="button" className="fp-button" disabled={busy} onClick={()=>saveDraft(false)}>仅保存草稿</button></div>
  </div></ForgeDialog>}
  {dialog?.kind==='detail'&&<ForgeDialog open title={dialog.row.name} subtitle={dialog.row.code+' · '+statusText[dialog.row.status]} confirmLabel="关闭" onCancel={()=>setDialog(null)} onConfirm={()=>setDialog(null)}><div className="pr-summary"><div><span>物料数</span><strong>{dialog.row.line_count}</strong></div><div><span>总数量</span><strong>{qty(dialog.row.total_quantity)}</strong></div><div><span>预估含税金额</span><strong>{money(dialog.row.estimated_taxed_amount)}</strong></div><div><span>期望到货</span><strong>{dialog.row.expected_arrival_on}</strong></div></div><div className="fp-table-wrap pr-detail-lines"><table className="fp-table"><thead><tr><th>来源</th><th>物料</th><th>型号 / 规格</th><th>数量</th><th>含税小计</th></tr></thead><tbody>{requestLines(dialog.row.id).map(x=><tr key={x.id}><td>{x.entry_mode==='library'?'物料库':x.entry_mode==='paste'?'快速粘贴':'手动录入'}</td><td>{x.item_code?x.item_code+' · ':''}{x.name}</td><td>{x.model||'—'} / {x.specification||'—'}</td><td>{qty(x.quantity)} {x.unit_name}</td><td>{money(x.taxed_subtotal)}</td></tr>)}</tbody></table></div><h3>审批记录</h3>{state.logs.filter(x=>x.request_id===dialog.row.id).map(x=><div className="fp-list-row" key={x.id}><span>{x.action} · {x.comment||'—'}</span><span>{String(x.occurred_at||'').replace('T',' ').slice(0,19)}</span></div>)}</ForgeDialog>}
  {dialog?.kind==='confirm'&&<ForgeDialog open title={dialog.title} subtitle={dialog.row.code+' · '+dialog.row.name} error={dialog.error} busy={busy} danger={dialog.danger} confirmLabel="确认" onCancel={()=>!busy&&setDialog(null)} onConfirm={invoke}><div className="fp-dialog-impact">{dialog.impact}</div>{['purchase_request_approve','purchase_request_reject','purchase_request_cancel'].includes(dialog.action)&&<div className="fp-field"><label>{dialog.action==='purchase_request_cancel'?'取消原因':'审批意见'} *</label><textarea className="fp-textarea" value={dialog.comment} onChange={e=>setDialog({...dialog,comment:e.target.value,error:''})}/></div>}</ForgeDialog>}
 </div>;
}
export default App;
`;

export const PurchaseRequestPage = {
  name: 'page_purchase_request_pool',
  label: '采购申请',
  description: '发起采购申请、审批流转、转询价或订单全流程跟踪',
  icon: 'file-plus-2',
  type: 'app' as const,
  kind: 'react' as const,
  source,
};
