import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const performanceCss = forgeProductUiCss + `
.sales-performance-bank .sp-shell{max-width:1480px;min-width:0;padding-top:20px}
.sales-performance-bank .fpHero{min-height:106px;padding:18px 22px;margin-bottom:14px;background:linear-gradient(110deg,#49369c,#6655ba)}
.sales-performance-bank .fpHero:before{display:none}.sales-performance-bank .fpHeroBadge{width:44px;height:44px}.sales-performance-bank .fpHeroBadge svg{width:25px;height:25px}.sales-performance-bank .fpHeroArt{opacity:.3}
.sales-performance-bank .sp-header{display:flex;align-items:center;gap:12px;padding:4px;border:1px solid var(--fp-line);border-radius:7px;background:#fff;margin-bottom:14px}
.sales-performance-bank .sp-scopes{display:flex;flex:1;gap:4px;min-width:0;overflow:auto}
.sales-performance-bank .sp-scopes .fp-button{height:28px;flex:0 0 auto;border:0;box-shadow:none;display:flex;align-items:center;gap:6px;font-size:12px}.sales-performance-bank .sp-scopes svg{width:14px;height:14px}
.sales-performance-bank .sp-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:0 0 20px}
.sales-performance-bank .sp-metrics [data-slot="list-summary-item"]{min-height:76px;padding:14px 16px;border-radius:7px;background:#fff;gap:6px}
.sales-performance-bank .sp-metrics dd{font-size:23px;line-height:1.2;font-weight:700}.sales-performance-bank .sp-metrics [data-slot="list-summary-item"]:nth-child(1) dd{color:var(--fp-primary)}.sales-performance-bank .sp-metrics [data-slot="list-summary-item"]:nth-child(2) dd{color:var(--fp-success)}.sales-performance-bank .sp-metrics [data-slot="list-summary-item"]:nth-child(4) dd{color:var(--fp-warning)}
.sales-performance-bank .sp-workspace{min-width:0}.sales-performance-bank .sp-tabs{border-bottom:1px solid var(--fp-line);background:transparent;padding:0;margin:0 0 14px}
.sales-performance-bank .sp-tabs [role="tablist"]{display:flex;flex-wrap:nowrap;gap:14px;overflow:auto}
.sales-performance-bank .sp-tabs [role="tab"]{height:40px;flex:0 0 auto;border:0;border-bottom:2px solid transparent;border-radius:0;background:transparent;padding:0 12px;color:var(--fp-muted);font-size:13px;white-space:nowrap}
.sales-performance-bank .sp-tabs [role="tab"][data-state="active"]{border-bottom-color:var(--fp-primary);color:var(--fp-primary);background:transparent;font-weight:650}
.sales-performance-bank .sp-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:0;margin-bottom:14px}
.sales-performance-bank .sp-search{flex:1 1 220px;min-width:180px}.sales-performance-bank .sp-controls>.fp-picker{flex:0 1 170px;min-width:140px}.sales-performance-bank .sp-controls>.sp-person{flex-basis:200px}
.sales-performance-bank .sp-periods{display:flex;gap:2px;overflow:auto;padding:2px;border:1px solid var(--fp-line);border-radius:6px;background:#fff;max-width:100%}
.sales-performance-bank .sp-periods button{height:27px;flex:0 0 auto;border:0;border-radius:4px;background:transparent;padding:0 9px;font:inherit;font-size:12px;cursor:pointer}
.sales-performance-bank .sp-periods button[aria-pressed=true]{background:var(--fp-primary);color:#fff;font-weight:650}
.sales-performance-bank .sp-bank-owner{display:flex;align-items:center;gap:12px;background:#eef0ff;border-radius:8px;padding:14px;margin-bottom:16px;font-size:14px;color:var(--fp-text)}.sales-performance-bank .sp-bank-avatar{display:grid;place-items:center;flex:0 0 36px;width:36px;height:36px;border-radius:50%;background:var(--fp-primary);color:#fff;font-weight:650}.sales-performance-bank .sp-bank-owner small{display:block;margin-top:3px;color:var(--fp-muted);font-size:12px}
.sales-performance-bank .sp-bank-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-bottom:16px}
.sales-performance-bank .sp-bank-summary article{min-width:0;padding:16px;border:1px solid var(--fp-line);border-radius:8px;background:#fff}.sales-performance-bank .sp-bank-summary span{display:flex;align-items:center;gap:6px;color:var(--fp-muted);font-size:12px}.sales-performance-bank .sp-bank-summary svg{width:14px;height:14px}.sales-performance-bank .sp-bank-summary strong{display:block;margin-top:8px;font-size:23px;line-height:1.2;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.sales-performance-bank .sp-bank-summary article:nth-child(1) strong{color:var(--fp-primary)}.sales-performance-bank .sp-bank-summary article:nth-child(3) strong{color:var(--fp-success)}.sales-performance-bank .sp-bank-summary article:nth-child(4) strong{color:var(--fp-danger)}.sales-performance-bank .sp-bank-summary small{display:block;margin-top:4px;color:var(--fp-muted);font-size:12px}
.sales-performance-bank .sp-table-wrap{max-width:100%;overflow:auto}
.sales-performance-bank .sp-table{min-width:1050px}
.sales-performance-bank .sp-number{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
.sales-performance-bank .sp-row-actions{display:flex;gap:5px;flex-wrap:wrap}
.sales-performance-bank .sp-status-note{margin:10px 12px}
.sales-performance-bank .sp-pagination{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;border-top:1px solid var(--fp-line);color:var(--fp-muted);font-size:12px}
.sales-performance-bank .sp-pagination-actions{display:flex;align-items:center;gap:7px}
.sales-performance-bank .sp-analysis{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:12px;padding:12px}
.sales-performance-bank .sp-chart-card{min-width:0;border:1px solid var(--fp-line);border-radius:8px;background:#fff;padding:12px}
.sales-performance-bank .sp-chart-title{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:10px;font-weight:650}
.sales-performance-bank .sp-chart{display:grid;grid-template-columns:repeat(12,minmax(24px,1fr));align-items:end;gap:7px;height:150px;border-bottom:1px solid var(--fp-line);overflow:auto}
.sales-performance-bank .sp-month{display:flex;height:100%;min-width:24px;flex-direction:column;justify-content:flex-end;align-items:center;gap:5px;color:var(--fp-muted);font-size:10px}
.sales-performance-bank .sp-bar{width:70%;min-height:2px;border-radius:3px 3px 0 0;background:var(--fp-primary)}
.sales-performance-bank .sp-rank{display:grid;gap:7px}
.sales-performance-bank .sp-rank-row{display:grid;grid-template-columns:24px minmax(90px,1fr) auto;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid var(--fp-line)}
.sales-performance-bank .sp-rank-row strong{white-space:nowrap}
.sales-performance-bank .sp-unconfigured{color:var(--fp-muted);font-size:11px;line-height:1.5}
.sales-performance-bank .sp-dialog-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}
.sales-performance-bank .sp-span-2{grid-column:1/-1}
.sales-performance-bank .sp-preview{padding:10px 12px;border:1px solid var(--fp-line);border-radius:7px;background:var(--fp-soft,#f8fafc)}
.sales-performance-bank .sp-preview div{display:flex;justify-content:space-between;gap:12px;padding:3px 0}
.sales-performance-bank .sp-preview span{color:var(--fp-muted)}.sales-performance-bank .sp-bank-trend{padding:16px;border:1px solid var(--fp-line);border-radius:8px;background:#fff;margin-bottom:16px}.sales-performance-bank .sp-bank-trend svg{display:block;width:100%;height:108px}.sales-performance-bank .sp-bank-months{display:grid;grid-template-columns:repeat(12,minmax(26px,1fr));gap:5px;overflow:auto;margin-top:4px;color:var(--fp-muted);font-size:10px;text-align:center}.sales-performance-bank .sp-bank-legend{display:flex;gap:14px;flex-wrap:wrap;margin-top:8px;color:var(--fp-muted);font-size:11px}.sales-performance-bank .sp-bank-legend i{display:inline-block;width:8px;height:8px;margin-right:5px;border-radius:50%}.sales-performance-bank .sp-bank-legend .sp-bank-line-performance{background:#315fcb}.sales-performance-bank .sp-bank-legend .sp-bank-line-orders{background:#16845b}.sales-performance-bank .sp-bank-legend .sp-bank-line-payments{background:#e18a26}.sales-performance-bank .sp-bank-legend .sp-bank-line-gross{background:#7a55c7}.sales-performance-bank .sp-bank-line-performance{stroke:#315fcb}.sales-performance-bank .sp-bank-line-orders{stroke:#16845b}.sales-performance-bank .sp-bank-line-payments{stroke:#e18a26}.sales-performance-bank .sp-bank-line-gross{stroke:#7a55c7}
@media(max-width:900px){.sales-performance-bank .sp-analysis{grid-template-columns:1fr}.sales-performance-bank .sp-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:640px){.sales-performance-bank .sp-metrics{grid-template-columns:1fr}.sales-performance-bank .sp-bank-summary{grid-template-columns:1fr}.sales-performance-bank .sp-header{align-items:center}.sales-performance-bank .sp-scopes{flex-wrap:wrap}.sales-performance-bank .sp-controls>.fp-picker{flex-basis:100%;width:100%}.sales-performance-bank .sp-controls{align-items:stretch}.sales-performance-bank .sp-search,.sales-performance-bank .sp-person{width:100%;flex-basis:100%}.sales-performance-bank .sp-dialog-grid{grid-template-columns:1fr}.sales-performance-bank .sp-span-2{grid-column:auto}}
`;

const source = String.raw`
const css=${JSON.stringify(performanceCss)},tabs=[['bank','我的业绩银行'],['entries','业绩流水'],['rebook','Rebook记录'],['confirm','销售业绩确认'],['analysis','业绩分析']],scopes=[['all','所有'],['mine','我负责的'],['team','下属负责的'],['watched','我关注的']],periods=[['all','全部'],['year','本年'],['q1','Q1'],['q2','Q2'],['q3','Q3'],['q4','Q4'],['month','本月']],statusLabels={pending:'待确认',pending_approval:'待审批',approved_waiting_source:'审批通过待原业绩确认',approved:'已分配',confirmed:'已确认',rebooked:'已分配',rejected:'已驳回',cancelled:'已取消',completed:'已完成',failed:'失败',running:'处理中',queued:'待生成'};
const money=value=>value===null||value===undefined||value===''||!Number.isFinite(Number(value))?'—':'¥'+Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),number=value=>value===null||value===undefined||value===''||!Number.isFinite(Number(value))?'—':Number(value).toLocaleString('zh-CN',{maximumFractionDigits:2}),percent=value=>value===null||value===undefined||value===''||!Number.isFinite(Number(value))?'—':Number(value).toFixed(2)+'%';
function unpack(value){let current=value;for(let i=0;i<6&&current&&typeof current==='object';i++){if(current.result!==undefined){current=current.result;continue}if(current.data?.result!==undefined){current=current.data.result;continue}if(current.data!==undefined){current=current.data;continue}break}return current}
function safeError(error){const message=String(error?.message||error||'请求失败').trim();return message.replace(/\b[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}\b/gi,'相关记录').replace(/\b(?:record|order|entry|job|unit|id)[:/#=\s-]+[A-Za-z0-9_-]{16,}\b/gi,'相关记录').slice(0,200)||'请求失败'}
function requestKey(prefix){return prefix+'-'+(typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2))}
function bankTrendPath(rows,key){const max=Math.max(1,...rows.map(row=>row[key]).filter(value=>value!==null&&value!==undefined&&Number.isFinite(Number(value))).map(value=>Math.abs(Number(value))));let path='',drawing=false;rows.forEach((row,index)=>{const value=row[key];if(value===null||value===undefined||!Number.isFinite(Number(value))){drawing=false;return}const x=12+index*(656/Math.max(1,rows.length-1)),y=52-Number(value)/max*40;path+=(drawing?' L':'M')+x.toFixed(1)+','+y.toFixed(1);drawing=true});return path}
function PerformanceIcon({kind='bank'}){const common={viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.7,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true};return <svg {...common}>{kind==='bank'?<><path d="M3 9l9-6 9 6H3M5 10v8m7-8v8m7-8v8M3 21h18"/></>:kind==='in'?<><path d="M5 5v14h14M7 16l5-5 4 3 5-7"/></>:kind==='out'?<><path d="M5 19V5h14M7 8l5 5 4-3 5 7"/></>:kind==='people'?<><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v2"/></>:<><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M4 9h16M16 13h4"/></>}</svg>}
function App(){const adapter=useAdapter();const initialTab=new URLSearchParams(window.location.search).get('tab');const [state,setState]=React.useState({loading:true,error:'',data:null,userId:'',permissions:[],businessDate:''}),[scope,setScope]=React.useState('all'),[tab,setTab]=React.useState(['bank','entries','rebook','confirm','analysis'].includes(initialTab)?initialTab:'bank'),[period,setPeriod]=React.useState('year'),[year,setYear]=React.useState(new Date().getFullYear()),[personId,setPersonId]=React.useState(''),[search,setSearch]=React.useState(''),[page,setPage]=React.useState(1),[confirmStatus,setConfirmStatus]=React.useState('pending'),[confirmationCustomerId,setConfirmationCustomerId]=React.useState(''),[confirmationStartOn,setConfirmationStartOn]=React.useState(''),[confirmationEndOn,setConfirmationEndOn]=React.useState(''),[analysisMetric,setAnalysisMetric]=React.useState('performance'),[rankSort,setRankSort]=React.useState('performance'),[dialog,setDialog]=React.useState(null),[exportJobsOpen,setExportJobsOpen]=React.useState(false),[busy,setBusy]=React.useState(false),[notice,setNotice]=React.useState(''),[noticeTone,setNoticeTone]=React.useState('success');
 const invoke=async(object,action,params={})=>unpack(await ForgeApiRequest(adapter,'/actions/'+encodeURIComponent(object)+'/'+encodeURIComponent(action),{method:'POST',body:JSON.stringify({params})}));
 const auth=async()=>{const [session,permissionPayload]=await Promise.all([ForgeApiRequest(adapter,'/auth/get-session'),ForgeApiRequest(adapter,'/auth/me/permissions').catch(()=>({}))]),permissions=unpack(permissionPayload)||{},identity=unpack(session)||{};return{userId:String(identity.user?.id||identity.session?.user?.id||identity.session?.userId||identity.userId||''),systemPermissions:permissions.systemPermissions||permissions.system_permissions||permissions.data?.systemPermissions||[]}};
 async function load(){setState(s=>({...s,loading:true,error:'',data:null}));try{const identity=state.userId?{userId:state.userId,systemPermissions:state.permissions}:await auth(),businessDate=state.businessDate||await ForgeOrganizationBusinessDate(adapter),requestYear=state.businessDate?year:Number(businessDate.slice(0,4)),query=await invoke('forge_sales_performance_entry','sales_performance_workspace_query',{scope,tab,period,year:requestYear,business_date:businessDate,sales_person_id:personId,search,sort_by:rankSort,confirm_status:confirmStatus,page,page_size:tab==='rebook'?20:10,confirmation_customer_id:tab==='confirm'?confirmationCustomerId:'',confirmation_start_on:tab==='confirm'?confirmationStartOn:'',confirmation_end_on:tab==='confirm'?confirmationEndOn:''});if(!query||!Array.isArray(query.rows))throw new Error('业绩工作区返回的数据不完整');if(!state.businessDate)setYear(requestYear);setState({loading:false,error:'',data:query,userId:identity.userId,permissions:identity.systemPermissions||[],businessDate})}catch(error){const status=Number(error?.status||0),message=status===401?'登录已失效，请重新登录后查看销售业绩。':status===403?'当前账号无权读取所选范围的销售业绩。':'销售业绩读取失败，无法确认当前范围记录，请重试。';setState(s=>({...s,loading:false,error:message,data:null}))}}
 React.useEffect(()=>{const url=new URL(window.location.href);url.searchParams.set('tab',tab);window.history.replaceState({},'',url.toString())},[tab]);React.useEffect(()=>{void load();},[scope,tab,period,year,personId,search,confirmStatus,page,analysisMetric,rankSort]);
 const data=state.data||{},rows=Array.isArray(data.rows)?data.rows:[],people=Array.isArray(data.people)?data.people:[],exportJobs=Array.isArray(data.export_jobs)?data.export_jobs:[],summary=data.summary||{},analytics=data.analytics||{},bankTrend=Array.isArray(analytics.trend)?analytics.trend:[],customerOptions=Array.isArray(data.customer_options)?data.customer_options:[],businessYear=Number(String(state.businessDate||'').slice(0,4))||year,yearOptions=[...new Set([businessYear,businessYear-1,year])].sort((a,b)=>b-a),canConfirm=state.permissions.includes('sales_performance_confirm')&&state.permissions.includes('forge_sales_gross_profit_read'),canRebook=state.permissions.includes('sales_performance_rebook'),canExport=state.permissions.includes('sales_performance_read')&&canRebook;
 function setFilter(fn){setPage(1);fn()}
 function openApprovalCenter(){ForgeNavigate(forgeBase+'/system/approvals')}
 async function openConfirmation(row){if(!canConfirm)return setNotice('当前账号没有业绩确认办理或权威毛利读取权限');setBusy(true);setNotice('');try{const report=await invoke('forge_revenue_recognition','sales_gross_profit_report_query',{period:'year',dimension:'order',order_id:row.order_id,business_date:state.businessDate,page:1,page_size:100,export_all:false});const metrics=report?.metrics||{},complete=report?.single_order_scope===true&&Number(metrics.revenue_unmatched_count||0)===0&&Number(metrics.cost_unmatched_count||0)===0&&Number.isFinite(Number(metrics.sales_revenue))&&Number.isFinite(Number(metrics.sales_cost))&&Number.isFinite(Number(metrics.gross_profit))&&Boolean(report.financial_source_signature);setDialog({kind:'confirm',row,report,complete,remarks:'',error:''})}catch(error){setDialog({kind:'confirm',row,report:null,complete:false,remarks:'',error:safeError(error)})}finally{setBusy(false)}}
 async function submitConfirmation(){if(!dialog?.complete||busy)return;setBusy(true);setDialog(d=>({...d,error:''}));try{const result=await invoke('forge_sales_order','sales_performance_confirmation_submit',{order_id:dialog.row.order_id,business_date:state.businessDate,request_key:requestKey('performance-confirm'),remarks:dialog.remarks.trim()});setDialog(null);setNoticeTone('success');setNotice(result?.status==='pending_approval'?'业绩确认已提交原生财务审批':'业绩确认已提交');await load()}catch(error){setDialog(d=>({...d,error:safeError(error)}))}finally{setBusy(false)}}
 async function openRebook(row){if(!canRebook)return setNotice('当前账号没有Rebook办理权限');if(row.status!=='pending'||row.entry_type!=='original_confirm'||Number(row.performance_amount)<=0||row.approval_status==='approved')return;setBusy(true);setNotice('');try{const options=await invoke('forge_sales_performance_entry','sales_performance_rebook_options_query',{source_entry_id:row.id}),targets=Array.isArray(options?.targets)?options.targets:[],dialogReasons=Array.isArray(options?.reasons)?options.reasons:[];setDialog({kind:'rebook',row,target_person_id:'',ratio:'25',reason_id:String(dialogReasons[0]?.id||''),remarks:'',targets,reasons:dialogReasons,error:targets.length?'':'当前原生业务单元没有可选的其他有效成员'})}catch(error){setNoticeTone('error');setNotice(safeError(error))}finally{setBusy(false)}}
 async function submitRebook(){if(!dialog?.target_person_id||!dialog?.reason_id)return setDialog(d=>({...d,error:d?.error||'请选择转入员工和分配原因'}));const ratio=Number(dialog.ratio);if(!(ratio>=1&&ratio<=100))return setDialog(d=>({...d,error:'分配比例须在 1 至 100 之间'}));setBusy(true);setDialog(d=>({...d,error:''}));try{const result=await invoke('forge_sales_performance_entry','sales_performance_rebook_submit',{source_entry_id:dialog.row.id,target_person_id:dialog.target_person_id,ratio,reason_id:dialog.reason_id,request_key:requestKey('performance-rebook'),remarks:dialog.remarks.trim()});setDialog(null);setNoticeTone('success');setNotice(result?.status==='pending_approval'?'Rebook申请已提交原生财务审批':'Rebook申请已提交');await load()}catch(error){setDialog(d=>({...d,error:safeError(error)}))}finally{setBusy(false)}}
 async function exportRebooks(){if(!canExport||busy)return;setBusy(true);setNotice('');try{const job=await invoke('forge_sales_performance_rebook','sales_performance_rebook_export_create',{request_key:requestKey('performance-export'),scope,period,year,business_date:state.businessDate,sales_person_id:personId,search});if(!job?.id)throw new Error('导出任务未返回可读取的结果');setExportJobsOpen(true);setNoticeTone('success');setNotice('Rebook导出已生成，共 '+Number(job.row_count||0)+' 条');await load()}catch(error){setNoticeTone('error');setNotice(safeError(error))}finally{setBusy(false)}}
 async function downloadExportJob(job){if(!job?.id||busy)return;setBusy(true);setNotice('');try{const result=await invoke('forge_sales_performance_export_job','sales_performance_export_job_download',{job_id:job.id});if(!result?.result_content)throw new Error('导出文件内容为空');const blob=new Blob([String(result.result_content)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=String(result.result_name||job.result_name||'销售业绩-Rebook.csv');link.click();setTimeout(()=>URL.revokeObjectURL(url),500);setNoticeTone('success');setNotice('已下载 '+link.download)}catch(error){setNoticeTone('error');setNotice(safeError(error))}finally{setBusy(false)}}
 const title=tab==='bank'?'我的业绩银行':tab==='entries'?'业绩流水':tab==='rebook'?'Rebook记录':tab==='confirm'?'销售业绩确认':'业绩分析',formatRowStatus=row=>{const label=statusLabels[row.status]||String(row.status||'—');if(row.entry_confirmation_status==='pending_approval'&&row.approval_status==='approved')return '审批通过，毛利待入账';if(row.entry_confirmation_status==='pending_approval')return '待审批';return row.approval_status==='approved'&&row.status==='pending_approval'?'审批通过，毛利待入账':label};
 const table=(columns,emptyTitle,emptyDescription)=> <>{rows.length?<ForgeTableViewport className="sp-table-wrap"><ForgeRecordTable schema={{type:'data-table',className:'sp-table',data:rows,columns,searchable:false,sortable:false,exportable:false,selectable:false,reorderableColumns:false,manualPagination:true,page,pageSize:Number(data.page_size||10),pageSizeOptions:[Number(data.page_size||10)],rowCount:Number(data.total||0),onPageChange:setPage}}/></ForgeTableViewport>:state.error?<ForgeEmpty title="业绩数据读取失败，无法确认记录" description="当前条件的记录不可用，请重试。" action={<ForgeButton className="fp-button" onClick={()=>load()}>重试</ForgeButton>}/>:!state.loading?<ForgeEmpty title={emptyTitle} description={emptyDescription}/>:null}</>;
 return <div className="forge-product sales-performance-bank"><style>{css}</style><main className="fp-shell sp-shell"><ForgeHero section="销售业务 / 业绩银行" title="业绩银行" icon={<PerformanceIcon/>} tone="violet" art="gauge"/>
  {state.error&&<ForgeNotice tone="error" onClose={()=>load()}>{state.error} · <ForgeButton className="fp-link" onClick={()=>load()}>重试</ForgeButton></ForgeNotice>}{notice&&<ForgeNotice tone={noticeTone} onClose={()=>setNotice('')}>{notice}</ForgeNotice>}
  <div className="sp-header"><nav className="sp-scopes" aria-label="业绩范围">{scopes.map(([value,label])=><ForgeButton key={value} className={'fp-button '+(scope===value?'primary':'')} aria-pressed={scope===value} onClick={()=>setFilter(()=>setScope(value))}><PerformanceIcon kind="people"/>{label}</ForgeButton>)}</nav><ForgeButton className="fp-icon-button" aria-label="刷新业绩" title="刷新" onClick={()=>load()}><span aria-hidden="true">↻</span></ForgeButton></div>
  <ListSummary className="sp-metrics" aria-label="业绩总览" items={[{id:'net',label:'累计确认业绩',value:money(summary.net_performance)},{id:'gross',label:'累计毛利',value:money(summary.gross_profit)},{id:'count',label:'业绩笔数',value:number(summary.performance_count)},{id:'pending',label:'待审批',value:number(summary.pending_approval)}]}/>
  <section className="sp-workspace"><StatusTabs className="sp-tabs" aria-label="业绩模块" panelId="sales-performance-panel" value={tab} onValueChange={value=>setFilter(()=>{setTab(value);setPage(1)})} items={tabs.map(([value,label])=>({value,label}))}/><div id="sales-performance-panel" role="tabpanel" aria-label={title}>
   <div className="sp-controls"><input className="fp-input sp-search" aria-label="搜索业绩" placeholder="搜索销售订单、客户或业绩人" value={search} onChange={event=>setFilter(()=>setSearch(event.target.value))}/><ForgeSelectControl className="sp-person" aria-label="业绩人" value={personId} onChange={event=>setFilter(()=>setPersonId(event.target.value))}><option value="">全部业绩人</option>{people.map(person=><option key={person.id} value={person.id}>{person.name||'员工信息不可读取'}</option>)}</ForgeSelectControl>{tab==='confirm'&&<><ForgeSelectControl className="sp-person" aria-label="确认客户" value={confirmationCustomerId} onChange={event=>setFilter(()=>setConfirmationCustomerId(event.target.value))}><option value="">全部客户</option>{customerOptions.map(customer=><option key={customer.id} value={customer.id}>{customer.name||'客户信息不可读取'}</option>)}</ForgeSelectControl><ForgeDateRange label="日期范围" onChange={range=>{(event=>setFilter(()=>setConfirmationStartOn(event.target.value)))({target:{value:range[0]},currentTarget:{value:range[0]}});(event=>setFilter(()=>setConfirmationEndOn(event.target.value)))({target:{value:range[1]},currentTarget:{value:range[1]}})}}><ForgeDateInput aria-label="确认开始日期" value={confirmationStartOn} onChange={event=>setFilter(()=>setConfirmationStartOn(event.target.value))}/><ForgeDateInput aria-label="确认结束日期" value={confirmationEndOn} onChange={event=>setFilter(()=>setConfirmationEndOn(event.target.value))}/></ForgeDateRange></>}<ForgeSelectControl aria-label="业绩年度" value={String(year)} onChange={event=>setFilter(()=>setYear(Number(event.target.value)))}>{yearOptions.map(option=><option key={option} value={String(option)}>{option}年</option>)}</ForgeSelectControl><div className="sp-periods" role="group" aria-label="统计期间">{periods.map(([value,label])=><ForgeButton key={value} type="button" aria-pressed={period===value} onClick={()=>setFilter(()=>setPeriod(value))}>{label}</ForgeButton>)}</div></div>
   {tab==='bank'&&<><div className="sp-bank-owner"><span className="sp-bank-avatar" aria-hidden="true">{(people.find(person=>person.id===personId)?.name||'全').slice(0,1)}</span><div><strong>{personId?(people.find(person=>person.id===personId)?.name||'所选业绩人')+'的业绩银行':scope==='mine'?'我的业绩银行':scope==='team'?'下属的业绩银行':scope==='watched'?'我关注的业绩银行':'全部业绩人的业绩银行'}</strong><small>{periods.find(item=>item[0]===period)?.[1]} · {year}年</small></div></div><div className="sp-bank-summary" aria-label="银行明细汇总">{[['业绩净额',summary.net_performance,'wallet'],['原始确认',summary.original_confirmed,'bank'],['业绩分入',summary.rebook_in,'in'],['业绩分出',summary.rebook_out,'out']].map(([label,value,kind])=><article key={label}><span><PerformanceIcon kind={kind}/>{label}</span><strong>{money(value)}</strong>{label==='业绩净额'&&<small>共 {number(summary.performance_count)} 笔业绩</small>}</article>)}</div>{summary.gross_profit_available===false&&<div className="sp-status-note"><ForgeNotice>毛利来源不完整或存在Rebook分配，当前范围的累计毛利显示为 —。</ForgeNotice></div>}<section className="sp-bank-trend" aria-label="12个月业绩趋势"><div className="sp-chart-title"><span>12个月趋势</span><span>{businessYear}年</span></div><svg viewBox="0 0 680 104" role="img" aria-label="业绩、订单、回款和毛利月度趋势"><line x1="10" y1="52" x2="670" y2="52" stroke="#dfe4ec" strokeWidth="1"/><path d={bankTrendPath(bankTrend,'performance')} fill="none" className="sp-bank-line-performance" strokeWidth="2"/><path d={bankTrendPath(bankTrend,'order_amount')} fill="none" className="sp-bank-line-orders" strokeWidth="2"/><path d={bankTrendPath(bankTrend,'payment_amount')} fill="none" className="sp-bank-line-payments" strokeWidth="2"/><path d={bankTrendPath(bankTrend,'gross_profit')} fill="none" className="sp-bank-line-gross" strokeWidth="2"/></svg><div className="sp-bank-months">{bankTrend.map(row=><span key={row.period}>{String(row.period||'').slice(5)}月</span>)}</div><div className="sp-bank-legend"><span><i className="sp-bank-line-performance"/>业绩额</span><span><i className="sp-bank-line-orders"/>订单额</span><span><i className="sp-bank-line-payments"/>回款额</span><span><i className="sp-bank-line-gross"/>毛利</span></div>{bankTrend.some(row=>row.gross_profit===null||row.gross_profit===undefined)&&<div className="sp-unconfigured">毛利仅显示已完整核对的月份；来源不完整或有Rebook时留空。</div>}</section>{table([
    {accessorKey:'amount_direction',header:'方向',width:80,cell:value=>value==='decrease'?'减少':'增加'},
    {accessorKey:'order_code_snapshot',header:'销售订单',width:165},
    {accessorKey:'customer_name_snapshot',header:'客户',width:180},
    {accessorKey:'sales_person_name_snapshot',header:'业绩人',width:135},
    {accessorKey:'order_amount',header:'订单额',width:125,cell:value=><span className="sp-number">{money(value)}</span>},
    {accessorKey:'gross_profit_rate',header:'毛利率',width:105,cell:value=><span className="sp-number">{percent(value)}</span>},
    {accessorKey:'performance_amount',header:'业绩金额',width:135,cell:value=><span className="sp-number">{money(value)}</span>},
    {accessorKey:'performance_ratio',header:'计收比例',width:105,cell:value=><span className="sp-number">{percent(value)}</span>},
    {accessorKey:'confirmed_at',header:'时间',width:135,cell:(value,row)=>row.business_date||'—'},
    {accessorKey:'status',header:'状态',width:130,cell:(_value,row)=>formatRowStatus(row)},
    {accessorKey:'actions',header:'操作',width:158,sortable:false,cell:(_value,row)=><div className="sp-row-actions">{row.entry_confirmation_status==='pending_approval'&&row.approval_status==='pending'&&<ForgeButton className="fp-button small" onClick={openApprovalCenter}>进入审批中心</ForgeButton>}{row.status==='pending'&&row.entry_type==='original_confirm'&&Number(row.performance_amount)>0&&<ForgeButton className="fp-button small" disabled={!canRebook||row.approval_status==='approved'||row.approval_status==='pending'} onClick={()=>openRebook(row)}>Rebook</ForgeButton>}{row.status==='pending_approval'&&<ForgeButton className="fp-button small" onClick={openApprovalCenter}>进入审批中心</ForgeButton>}<ForgeButton className="fp-button small" onClick={()=>setDialog({kind:'detail',row})}>查看</ForgeButton></div>},
   ],'暂无业绩记录','已确认的业绩与待确认原始业绩会在这里展示。')}</>}
   {tab==='entries'&&table([
    {accessorKey:'confirmed_at',header:'确认时间',width:135,cell:(value,row)=>row.business_date||'—'},
    {accessorKey:'order_code_snapshot',header:'销售订单',width:165},
    {accessorKey:'entry_type',header:'流水类型',width:120,cell:value=>value==='original_confirm'?'原始确认':value==='rebook_in'?'业绩分入':value==='rebook_out'?'业绩分出':value==='return_adjustment'?'退货冲减':'业绩流水'},
    {accessorKey:'sales_person_name_snapshot',header:'业绩人',width:135},
    {accessorKey:'amount_direction',header:'方向',width:80,cell:value=>value==='decrease'?'减少':'增加'},
    {accessorKey:'performance_amount',header:'业绩金额',width:135,cell:value=><span className="sp-number">{money(value)}</span>},
    {accessorKey:'gross_profit',header:'毛利',width:120,cell:value=><span className="sp-number">{money(value)}</span>},
    {accessorKey:'status',header:'状态',width:125,cell:(_value,row)=>formatRowStatus(row)},
   ],'暂无业绩流水','原始确认和Rebook会以分开的流水记录留痕。')}
   {tab==='rebook'&&<><div className="sp-controls"><ForgeButton className="fp-button" disabled={!canExport||busy} onClick={exportRebooks}>导出</ForgeButton><ForgeButton className="fp-button" onClick={()=>{setExportJobsOpen(true);void load()}}>导出任务</ForgeButton></div>{table([
    {accessorKey:'source_order_code',header:'来源业绩',width:165},
    {accessorKey:'source_person_id',header:'转出人',width:135,cell:value=>people.find(person=>person.id===value)?.name||'员工信息不可读取'},
    {accessorKey:'target_person_id',header:'转入人',width:135,cell:value=>people.find(person=>person.id===value)?.name||'员工信息不可读取'},
    {accessorKey:'ratio',header:'比例',width:95,cell:value=><span className="sp-number">{percent(value)}</span>},
    {accessorKey:'amount',header:'金额',width:125,cell:value=><span className="sp-number">{money(value)}</span>},
    {accessorKey:'reason_name_snapshot',header:'原因',width:175},
    {accessorKey:'submitted_at',header:'提交时间',width:135,cell:value=>String(value||'—').slice(0,10)},
    {accessorKey:'status',header:'状态',width:155,cell:(_value,row)=>formatRowStatus(row)},
    {accessorKey:'actions',header:'操作',width:158,sortable:false,cell:(_value,row)=><div className="sp-row-actions">{row.status==='pending_approval'&&<ForgeButton className="fp-button small" onClick={openApprovalCenter}>进入审批中心</ForgeButton>}<ForgeButton className="fp-button small" onClick={()=>setDialog({kind:'detail',row})}>查看</ForgeButton></div>},
   ],'暂无 Rebook 记录','从符合条件的待确认原始业绩发起 Rebook 申请。')}<div className="sp-status-note"><ForgeNotice>审批通过后，原业绩未确认时会保留为“审批通过待原业绩确认”，不会提前计入银行净额。</ForgeNotice></div></>}
   {tab==='confirm'&&<StatusTabs className="sp-status-tabs" aria-label="业绩确认状态" panelId="sales-performance-confirm-results" value={confirmStatus} onValueChange={value=>setFilter(()=>setConfirmStatus(value))} items={[{value:'pending',label:'待确认'},{value:'confirmed',label:'已确认'}]}/>}
   {tab==='confirm'&&<div id="sales-performance-confirm-results" role="tabpanel" aria-label={confirmStatus==='pending'?'待确认订单':'已确认业绩'}>
    {confirmStatus==='pending'?table([
     {accessorKey:'order_code',header:'销售订单',width:165},{accessorKey:'customer_name',header:'客户',width:170},{accessorKey:'sales_person_name',header:'业绩人',width:135},
     {accessorKey:'order_amount',header:'订单额',width:125,cell:value=><span className="sp-number">{money(value)}</span>},
     {accessorKey:'source_recognized_amount',header:'批准收入来源',width:145,cell:value=><span className="sp-number">{money(value)}</span>},
     {accessorKey:'completed_on',header:'订单完成日期',width:130,cell:value=>value||'—'},
     {accessorKey:'status',header:'状态',width:115,cell:value=>value==='rejected'?'上次驳回':value==='pending_approval'?'待审批':'待确认'},
     {accessorKey:'actions',header:'操作',width:120,sortable:false,cell:(_value,row)=><ForgeButton className="fp-button small primary" disabled={!canConfirm||busy||row.unresolved?.length>0} onClick={()=>openConfirmation(row)}>{row.status==='rejected'?'重新提交':'确认业绩'}</ForgeButton>},
    ],'没有符合条件的待确认销售订单','已完成且有已批准收入确认来源的订单会出现在这里。'):table([
     {accessorKey:'order_code',header:'销售订单',width:165},{accessorKey:'customer_name',header:'客户',width:170},{accessorKey:'sales_person_name',header:'业绩人',width:135},
     {accessorKey:'order_amount',header:'订单额',width:125,cell:value=><span className="sp-number">{money(value)}</span>},{accessorKey:'performance_amount',header:'业绩额',width:125,cell:value=><span className="sp-number">{money(value)}</span>},
     {accessorKey:'gross_profit_rate',header:'毛利率',width:105,cell:value=><span className="sp-number">{percent(value)}</span>},{accessorKey:'confirmed_at',header:'确认日期',width:135,cell:(_value,row)=>row.business_date||'—'},
     {accessorKey:'status',header:'状态',width:110,cell:(_value,row)=>formatRowStatus(row)},
    ],'暂无已确认业绩','原生审批通过并完成来源校验后，业绩会出现在这里。')}
    {!canConfirm&&confirmStatus==='pending'&&<div className="sp-status-note"><ForgeNotice tone="warning">当前账号没有业绩确认办理和权威毛利读取能力。</ForgeNotice></div>}
   </div>}
   {tab==='analysis'&&<div className="sp-analysis"><section className="sp-chart-card"><div className="sp-chart-title"><span>月度趋势</span><ForgeSelectControl aria-label="趋势指标" value={analysisMetric} onChange={event=>setAnalysisMetric(event.target.value)}><option value="performance">业绩额</option><option value="order_amount">订单额</option><option value="payment_amount">回款额</option><option value="gross_profit">毛利</option><option value="completion_rate">完成率</option></ForgeSelectControl></div>{analysisMetric==='completion_rate'&&<div className="sp-unconfigured">业绩年度目标字段尚未配置；合同额或回款目标不等同于业绩目标，完成率暂不计算。</div>}<div className="sp-chart" role="img" aria-label="月度业绩趋势">{(analytics.trend||[]).map(month=>{const value=analysisMetric==='performance'?month.performance:month[analysisMetric],values=(analytics.trend||[]).map(item=>Number(item[analysisMetric]||0)),peak=Math.max(...values,1),height=value===null||value===undefined?2:Math.max(2,Number(value)/peak*130);return <div className="sp-month" key={month.period} title={month.period+' '+(value==null?'—':money(value))}><div className="sp-bar" style={{height:height+'px',opacity:value==null?.35:1}}></div><span>{String(month.period||'').slice(5)}</span></div>})}</div><p className="sp-unconfigured">按已确认业绩、订单金额和已审核收款核销统计；缺少完整来源时毛利显示为 —。</p></section><section className="sp-chart-card"><div className="sp-chart-title"><span>销售综合排名</span><ForgeSelectControl aria-label="排名依据" value={rankSort} onChange={event=>setRankSort(event.target.value)}><option value="performance">按业绩</option><option value="completion_rate">按完成率</option><option value="payment">按回款</option></ForgeSelectControl></div>{analytics.target_configuration&&<div className="sp-unconfigured">业绩目标未配置，目标完成率显示为 —。</div>}<div className="sp-rank">{(analytics.ranking||[]).slice(0,10).map((row,index)=><div className="sp-rank-row" key={row.sales_person_id}><span>{index+1}</span><span>{row.sales_person_name}<small>{row.team_name||'未映射原生业务单元'}</small></span><strong>{money(row.performance_amount)}<small>订单 {money(row.order_amount)} · 回款 {money(row.payment_amount)}</small></strong></div>)}{!analytics.ranking?.length&&<ForgeEmpty title="暂无已确认业绩" description="审批通过的业绩会进入分析排名。"/>}</div><div className="sp-unconfigured">毛利仅在收入税基、成本来源和Rebook影响均可核对时显示。完成率因业绩目标未配置显示为 —。</div></section><section className="sp-chart-card sp-span-2"><div className="sp-chart-title">团队完成率概览</div>{(analytics.teams||[]).length?<div className="sp-rank">{analytics.teams.map(team=><div className="sp-rank-row" key={team.business_unit_id||team.team_name}><span>{team.team_name||'—'}</span><strong>{money(team.performance_amount)}<small>订单 {money(team.order_amount)} · 回款 {money(team.payment_amount)} · 目标完成率 —</small></strong></div>)}</div>:<ForgeEmpty title="暂无团队业绩" description="所选范围没有可汇总的已确认业绩。"/>}</section></div>}
  </div></section>{state.loading&&<div className="sp-status-note"><ForgeLoading label="正在加载销售业绩"/></div>}
 </main>
 {dialog?.kind==='confirm'&&<CompositeDialog open title="确认销售业绩" description={dialog?.row?.order_code||'销售订单'} busy={busy} onOpenChange={open=>{if(!open&&!busy)setDialog(null)}} footer={({requestClose})=><div className="sp-dialog-actions"><ForgeButton type="button" className="fp-button" disabled={busy} onClick={requestClose}>取消</ForgeButton><ForgeButton type="button" className="fp-button primary" disabled={busy||!dialog?.complete} onClick={submitConfirmation}>{busy?'提交中…':'提交原生审批'}</ForgeButton></div>}>{dialog.error&&<ForgeNotice tone="error">{dialog.error}</ForgeNotice>}<div className="sp-dialog-grid"><div className="sp-preview sp-span-2">{dialog?.report?<><div><span>不含税收入</span><strong>{money(dialog.report.metrics?.sales_revenue)}</strong></div><div><span>已核对成本</span><strong>{money(dialog.report.metrics?.sales_cost)}</strong></div><div><span>毛利</span><strong>{money(dialog.report.metrics?.gross_profit)}</strong></div><div><span>计收比例</span><strong>100%</strong></div><div><span>审批前状态</span><strong>{dialog.complete?'可提交':'收入税基或成本未完整核对'}</strong></div></>:<ForgeLoading label="核对订单收入与成本来源"/>}</div><div className="fp-field sp-span-2"><label>备注</label><textarea className="fp-textarea" aria-label="业绩确认备注" value={dialog?.remarks||''} onChange={event=>setDialog(d=>({...d,remarks:event.target.value,error:''}))}/></div></div></CompositeDialog>}
 {dialog?.kind==='rebook'&&<CompositeDialog open title="申请 Rebook" description={dialog?.row?.order_code_snapshot||'来源业绩'} busy={busy} confirmOnDiscard={Boolean(dialog.target_person_id||dialog.ratio!=='25'||dialog.reason_id||dialog.remarks)} onOpenChange={open=>{if(!open&&!busy)setDialog(null)}} footer={({requestClose})=><div className="sp-dialog-actions"><ForgeButton type="button" className="fp-button" disabled={busy} onClick={requestClose}>取消</ForgeButton><ForgeButton type="button" className="fp-button primary" disabled={busy||!canRebook||!dialog?.targets?.length||!dialog?.reasons?.length} onClick={submitRebook}>{busy?'提交中…':'提交原生审批'}</ForgeButton></div>}>{dialog.error&&<ForgeNotice tone="error">{dialog.error}</ForgeNotice>}<div className="sp-dialog-grid"><div className="fp-field"><label>转入员工 *</label><ForgeSelectControl aria-label="转入员工" value={dialog?.target_person_id||''} onChange={event=>setDialog(d=>({...d,target_person_id:event.target.value,error:''}))}><option value="">请选择同一原生业务单元员工</option>{dialog?.targets?.map(person=><option key={person.id} value={person.id}>{person.name||'员工信息不可读取'}</option>)}</ForgeSelectControl></div><div className="fp-field"><label>分配比例 (%) *</label><input className="fp-input" aria-label="分配比例" inputMode="decimal" min="1" max="100" value={dialog?.ratio||''} onChange={event=>setDialog(d=>({...d,ratio:event.target.value,error:''}))}/></div><div className="fp-field sp-span-2"><label>分配原因 *</label><ForgeSelectControl aria-label="分配原因" value={dialog?.reason_id||''} onChange={event=>setDialog(d=>({...d,reason_id:event.target.value,error:''}))}><option value="">请选择本组织启用的分配原因</option>{(dialog?.reasons||[]).map(reason=><option key={reason.id} value={reason.id}>{reason.name}</option>)}</ForgeSelectControl></div><div className="sp-preview sp-span-2"><div><span>来源业绩金额</span><strong>{money(dialog?.row?.performance_amount)}</strong></div><div><span>申请转记金额</span><strong>{money(Number(dialog?.row?.performance_amount||0)*Number(dialog?.ratio||0)/100)}</strong></div></div><div className="fp-field sp-span-2"><label>备注</label><textarea className="fp-textarea" aria-label="Rebook备注" value={dialog?.remarks||''} onChange={event=>setDialog(d=>({...d,remarks:event.target.value,error:''}))}/></div></div></CompositeDialog>}
 {dialog?.kind==='detail'&&<CompositeDialog open title={dialog.row?.source_order_code?'Rebook记录':'业绩流水'} description={dialog.row?.source_order_code||dialog.row?.order_code_snapshot||''} onOpenChange={open=>{if(!open)setDialog(null)}} footer={({requestClose})=><div className="sp-dialog-actions">{(dialog.row?.status==='pending_approval'||dialog.row?.entry_confirmation_status==='pending_approval'&&dialog.row?.approval_status==='pending')&&<ForgeButton type="button" className="fp-button primary" onClick={openApprovalCenter}>进入审批中心</ForgeButton>}<ForgeButton type="button" className="fp-button" onClick={requestClose}>关闭</ForgeButton></div>}><dl className="sp-detail-grid">{(dialog.row?.source_order_code?[["来源订单",dialog.row.source_order_code],["客户",dialog.row.customer_name_snapshot],["转出人",people.find(person=>person.id===dialog.row.source_person_id)?.name||'员工信息不可读取'],["转入人",people.find(person=>person.id===dialog.row.target_person_id)?.name||'员工信息不可读取'],["分配比例",percent(dialog.row.ratio)],["金额",money(dialog.row.amount)],["原因",dialog.row.reason_name_snapshot],["状态",statusLabels[dialog.row.status]||'—'],["提交时间",dialog.row.submitted_at]]:[["销售订单",dialog.row?.order_code_snapshot],["客户",dialog.row?.customer_name_snapshot],["业绩人",dialog.row?.sales_person_name_snapshot],["流水类型",dialog.row?.entry_type==='original_confirm'?'原始确认':dialog.row?.entry_type==='rebook_in'?'业绩分入':dialog.row?.entry_type==='rebook_out'?'业绩分出':'业绩流水'],["方向",dialog.row?.amount_direction==='decrease'?'减少':'增加'],["业绩金额",money(dialog.row?.performance_amount)],["毛利",money(dialog.row?.gross_profit)],["状态",formatRowStatus(dialog.row||{})],["确认时间",dialog.row?.confirmed_at]]).map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value===null||value===undefined||value===''?'—':String(value)}</dd></React.Fragment>)}</dl></CompositeDialog>}
 {exportJobsOpen&&<CompositeDialog open title="Rebook 导出任务" onOpenChange={open=>{if(!open)setExportJobsOpen(false)}} footer={({requestClose})=><div className="sp-dialog-actions"><ForgeButton type="button" className="fp-button" onClick={()=>{void load()}}>刷新任务</ForgeButton><ForgeButton type="button" className="fp-button" onClick={requestClose}>关闭</ForgeButton></div>}>{state.error&&<ForgeNotice tone="error">{state.error}</ForgeNotice>}{state.loading?<ForgeLoading label="读取导出任务"/>:state.error?<ForgeEmpty title="导出任务读取失败，无法确认记录" description="当前任务数据不可用，请重试。" action={<ForgeButton className="fp-button" onClick={()=>load()}>重试</ForgeButton>}/>:exportJobs.length?<ForgeTableViewport className="sp-table-wrap"><ForgeRecordTable schema={{type:'data-table',className:'sp-table',columns:[{accessorKey:'name',header:'任务',width:230},{accessorKey:'status',header:'状态',width:100,cell:value=>statusLabels[value]||value},{accessorKey:'progress',header:'进度',width:90,cell:value=>number(value)+'%'},{accessorKey:'row_count',header:'导出行数',width:100,cell:value=>number(value)},{accessorKey:'result_name',header:'结果文件',width:220},{accessorKey:'submitted_at',header:'提交时间',width:150,cell:value=>String(value||'—').slice(0,16)},{accessorKey:'actions',header:'操作',width:100,sortable:false,cell:(_value,row)=><ForgeButton type="button" className="fp-button small" disabled={busy||row.status!=='completed'} onClick={()=>downloadExportJob(row)}>下载</ForgeButton>}],data:exportJobs,searchable:false,sortable:false,exportable:false,selectable:false,reorderableColumns:false,pagination:false}}/></ForgeTableViewport>:<ForgeEmpty title="暂无导出任务" description="生成 Rebook 导出后，任务结果会显示在这里。"/>}</CompositeDialog>}
 </div>;
}
export default App;
${forgeProductUiRuntime}
`;

export const SalesPerformanceBankPage = {
  name: 'page_sales_performance_bank', label: '业绩银行', description: '销售业绩确认、Rebook分配与分析',
  icon: 'landmark', type: 'app' as const, template: 'react-source' as const, kind: 'react' as const, source,
};
