import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const portalCss = `
.forge-sc-portal .sp-hero{padding:22px 24px;border-radius:14px;background:linear-gradient(120deg,#3843a8,#237fc5);color:#fff;margin-bottom:14px}.forge-sc-portal .sp-hero h1{margin:0 0 6px;font-size:25px}.forge-sc-portal .sp-hero p{margin:0;color:#e6efff}.forge-sc-portal .sp-rolebar{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.forge-sc-portal .sp-role{border:1px solid var(--fp-line-strong);border-radius:999px;background:#fff;padding:7px 13px;color:var(--fp-muted)}.forge-sc-portal .sp-role.active{border-color:var(--fp-primary);background:var(--fp-primary-soft);color:var(--fp-primary);font-weight:650}.forge-sc-portal .sp-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:11px;margin-bottom:14px}.forge-sc-portal .sp-kpi{padding:15px}.forge-sc-portal .sp-kpi span{display:block;color:var(--fp-muted);font-size:12px}.forge-sc-portal .sp-kpi strong{display:block;font-size:22px;margin:5px 0}.forge-sc-portal .sp-layout{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,1.9fr);gap:14px}.forge-sc-portal .sp-section{padding:18px}.forge-sc-portal .sp-section h2{font-size:15px;margin:0 0 13px}.forge-sc-portal .sp-task{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid var(--fp-line)}.forge-sc-portal .sp-task:last-child{border-bottom:0}.forge-sc-portal .sp-task small{display:block;color:var(--fp-muted);margin-top:3px}.forge-sc-portal .sp-links{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.forge-sc-portal .sp-link{display:block;border:1px solid var(--fp-line);border-radius:10px;padding:12px;color:var(--fp-text);text-decoration:none;background:#fff}.forge-sc-portal .sp-link:hover{border-color:#abc3f8;background:var(--fp-primary-soft)}.forge-sc-portal .sp-link strong,.forge-sc-portal .sp-link small{display:block}.forge-sc-portal .sp-link small{color:var(--fp-muted);margin-top:4px}.forge-sc-portal .sp-badge{display:inline-flex;border-radius:999px;padding:3px 8px;background:#fff4e5;color:#9a5b00;font-size:11px}.forge-sc-portal .sp-flow{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.forge-sc-portal .sp-step{padding:12px;border:1px solid var(--fp-line);border-radius:9px;background:#fff}.forge-sc-portal .sp-step span{display:block;color:var(--fp-primary);font-size:11px;font-weight:700}.forge-sc-portal .sp-step strong{display:block;margin:5px 0;font-size:13px}.forge-sc-portal .sp-step small{color:var(--fp-muted)}@media(max-width:1050px){.forge-sc-portal .sp-kpis{grid-template-columns:repeat(3,1fr)}.forge-sc-portal .sp-layout{grid-template-columns:1fr}.forge-sc-portal .sp-flow{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.forge-sc-portal .sp-kpis,.forge-sc-portal .sp-links,.forge-sc-portal .sp-flow{grid-template-columns:1fr 1fr}}
`;

const portalSource = `
const {useEffect,useState}=React;
const css=${JSON.stringify(forgeProductUiCss + portalCss)};
${forgeProductUiRuntime}
const pages={orders:'page_subcontract_orders',issues:'page_subcontract_issue_workspace',receipts:'page_subcontract_receipt_workspace',returns:'page_subcontract_returns',reconciliation:'page_subcontract_reconciliation',suppliers:'page_subcontract_suppliers',stock:'page_subcontract_stock',trace:'page_subcontract_trace',undelivered:'page_subcontract_undelivered',receiptReport:'page_subcontract_receipts_report',statement:'page_subcontract_statement_report'};
const href=key=>forgePageHref(pages[key]);
function App(){const adapter=useAdapter();
 const [state,setState]=useState({loading:true,error:'',data:{}}),[role,setRole]=useState('委外业务员');
 async function request(name){if(adapter?.find){const p=await adapter.find(name,{limit:300});return p?.records||p?.data?.records||p?.data||[]}const r=await fetch('/api/v1/data/'+name+'?$top=300',{credentials:'include'}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error((typeof p.error==='string'?p.error:p.error?.message)||(Array.isArray(p.fields)&&p.fields.length?p.fields.map(f=>f.message||f.label).filter(Boolean).join('；'):'')||p.message||'请求失败');return p.records||[]}
 async function load(){setState(s=>({...s,loading:true,error:''}));try{const names=['forge_subcontract_order','forge_subcontract_issue','forge_subcontract_receipt','forge_subcontract_ncr','forge_subcontract_stock_balance'],pairs=await Promise.all(names.map(async n=>[n,await request(n)]));setState({loading:false,error:'',data:Object.fromEntries(pairs)})}catch(e){setState({loading:false,error:String(e.message||e),data:{}})}}
 useEffect(()=>{load()},[]);
 if(state.loading)return <div className="forge-product forge-sc-portal"><style>{css}</style><div className="fp-shell"><ForgeLoading label="正在加载委外工作台"/></div></div>;
 const d=state.data,orders=d.forge_subcontract_order||[],issues=d.forge_subcontract_issue||[],receipts=d.forge_subcontract_receipt||[],ncrs=d.forge_subcontract_ncr||[],stocks=d.forge_subcontract_stock_balance||[],today=new Date().toISOString().slice(0,10);
 const kpis=[['进行中订单',orders.filter(x=>['approved','in_progress'].includes(x.status)).length,'审核后到对账前'],['待发料',orders.filter(x=>x.supply_mode==='customer_supplied'&&['approved','in_progress'].includes(x.status)&&Number(x.issued_quantity)<Number(x.issue_planned_quantity)).length,'甲供料 · 剩余可发'],['待回厂',orders.filter(x=>['approved','in_progress'].includes(x.status)&&Number(x.received_quantity)<Number(x.total_quantity)).length,'供应商加工中'],['待对账',orders.filter(x=>x.status==='completed'&&Number(x.reconciled_amount)<Number(x.processing_amount)).length,'对账能力待交付'],['逾期订单',orders.filter(x=>['approved','in_progress'].includes(x.status)&&x.expected_delivery_on&&x.expected_delivery_on<today).length,'超过期望交期']];
 const roleTasks={
  '委外业务员':[['待审核订单',orders.filter(x=>x.status==='pending_approval').length,'核对供应商、交期、价格与供料方式','orders'],['异常待协调',ncrs.filter(x=>x.status!=='executed').length,'确认责任与后续处置','receipts'],['待对账订单',kpis[3][1],'核对回厂加工费和负向来源','reconciliation']],
  '仓库人员':[['待执行发料',issues.filter(x=>x.status==='ready_to_issue').length,'把锁定库存转成实际出库','issues'],['待供应商签收',issues.filter(x=>x.status==='issued').length,'登记交接结果','issues'],['在外库存记录',stocks.filter(x=>Number(x.on_hand_quantity)>0).length,'核对发料、倒冲与退料','stock']],
  '质检 / 收货':[['待确认入库',receipts.filter(x=>x.status==='pending_inbound').length,'复核良品数量与材料耗用','receipts'],['不良待处置',ncrs.filter(x=>x.status!=='executed').length,'从来源回厂单处理不良','receipts'],['已完成回厂',receipts.filter(x=>x.status==='stocked').length,'查看入库和订单累计','receipts']],
  '财务人员':[['待赔偿来源',ncrs.filter(x=>x.status==='executed'&&Number(x.loss_amount)>0).length,'财务赔偿能力待交付','reconciliation'],['待对账订单',kpis[3][1],'按供应商汇总加工费与扣款','reconciliation'],['已对账订单',orders.filter(x=>x.status==='reconciled').length,'追溯关联应付','statement']]
 };
 const links=[['委外订单','建单、审核与三条履约进度','orders'],['委外发料','审核、出库与供应商签收','issues'],['委外回厂','验收、良品入库与不良去向','receipts'],['委外退料','余料回收','returns'],['委外对账','加工费、赔偿与应付','reconciliation'],['委外供应商','工艺能力与结算准备','suppliers'],['委外库存','供应商侧库存子账','stock'],['批次追溯','材料与成品双向追溯','trace'],['委外未交','剩余交付与超期','undelivered'],['委外进货','回厂、良率与加工费','receiptReport'],['委外对账单','净应付与关联应付','statement']];
 return <div className="forge-product forge-sc-portal"><style>{css}</style><div className="fp-shell"><section className="sp-hero"><h1>委外业务全景</h1><p>订单 → 发料 → 签收 → 回厂验收 → 入库 / 不良处置 → 对账结算</p></section>{state.error&&<ForgeNotice tone="error" onClose={load}>{state.error}</ForgeNotice>}<div className="sp-rolebar" aria-label="岗位视角">{Object.keys(roleTasks).map(x=><button className={'sp-role '+(role===x?'active':'')} aria-pressed={role===x} key={x} onClick={()=>setRole(x)}>{x}</button>)}</div><div className="sp-kpis">{kpis.map(x=><div className="fp-card sp-kpi" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="sp-layout"><section className="fp-card sp-section"><h2>我的待办 · {role}</h2>{roleTasks[role].map(x=><div className="sp-task" key={x[0]}><div><strong>{x[0]} · {x[1]}</strong><small>{x[2]}</small></div><a className="fp-button small" href={href(x[3])}>查看</a></div>)}</section><section className="fp-card sp-section"><h2>业务入口</h2><div className="sp-links">{links.map(x=><a className="sp-link" href={href(x[2])} key={x[0]}><strong>{x[0]}</strong><small>{x[1]}</small>{['returns','reconciliation','trace','undelivered','receiptReport','statement'].includes(x[2])&&<span className="sp-badge">待交付能力</span>}</a>)}</div></section></div></div></div>
}
export default App;`;

const guideSource = `
const {useState}=React;
const css=${JSON.stringify(forgeProductUiCss + portalCss)};
${forgeProductUiRuntime}
function App(){const adapter=useAdapter();const [role,setRole]=useState('委外业务员');const roles={
'委外业务员':[['01','准备供应商','确认已启用、加工能力、联系人和结算条件'],['02','创建并审核订单','选择甲供料或包工包料，录入加工件、交期与价格'],['03','协调执行','跟踪发料、回厂、异常和逾期'],['04','发起对账','核对加工费、赔偿、扣款和净应付']],
'仓库人员':[['01','核对待发','只处理已审核甲供料订单和剩余计划'],['02','执行出库','把库存锁定转为原仓出库和委外仓入库'],['03','登记签收','确认交接，签收不等于生产开工'],['04','余料回收','退料不得超过供应商侧在外余量']],
'质检 / 收货':[['01','登记回厂','回厂量不得超过订单未交数量'],['02','判定结果','合格与不良之和必须等于本次回厂'],['03','确认入库','良品入正式库存，甲供料按实际耗用倒冲'],['04','处理不良','从来源回厂进入受控处置并保存责任']],
'财务人员':[['01','核对结算条件','从订单确认供应商和付款条件'],['02','承接赔偿','审批不良或超耗形成的负向来源'],['03','供应商对账','归集回厂加工费和赔偿扣款'],['04','生成应付','已审核对账幂等生成一条可追溯应付']]
};return <div className="forge-product forge-sc-portal"><style>{css}</style><div className="fp-shell"><section className="sp-hero"><h1>委外管理上手指南</h1><p>按岗位理解准备条件、办理顺序、硬门槛和结果去向</p></section><div className="sp-rolebar">{Object.keys(roles).map(x=><button className={'sp-role '+(role===x?'active':'')} key={x} onClick={()=>setRole(x)}>{x}</button>)}</div><section className="fp-card sp-section"><h2>{role} · 任务路径</h2><div className="sp-flow">{roles[role].map(x=><div className="sp-step" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div></section><ForgeNotice tone="warning">退料、赔偿、对账、应付和批次追溯仍在恢复计划中。当前页面明确保留边界，不把说明文字当成可用能力。</ForgeNotice></div></div>}
export default App;`;

const statusSource = (title: string, observed: string, available: string, missing: string) => `
const css=${JSON.stringify(forgeProductUiCss + portalCss)};
${forgeProductUiRuntime}
function App(){const adapter=useAdapter();return <div className="forge-product forge-sc-portal"><style>{css}</style><div className="fp-shell"><div className="fp-list-context"><div><h1 style={{margin:'0 0 6px',fontSize:24}}>${title}</h1><p style={{margin:0,color:'var(--fp-muted)'}}>${observed}</p></div><span className="sp-badge">待交付能力</span></div><section className="fp-card sp-section"><h2>当前可用基础</h2><p>${available}</p></section><section className="fp-card sp-section"><h2>达到可用仍缺</h2><p>${missing}</p></section><ForgeNotice tone="warning">此页用于明确恢复状态，没有写入动作，也不表示该业务已经完成。</ForgeNotice></div></div>};export default App;`;

const page = (name: string, label: string, description: string, source: string, icon: string) => ({
  name, label, description, icon, type: 'app' as const, kind: 'react' as const, source,
});

export const SubcontractDashboardPage = page('page_subcontract_dashboard', '委外看板', '岗位待办、阶段指标和连续业务入口', portalSource, 'layout-dashboard');
export const SubcontractGuidePage = page('page_subcontract_guide', '委外管理上手指南', '按岗位说明委外准备、办理顺序和硬门槛', guideSource, 'circle-help');
export const SubcontractReturnsPage = page('page_subcontract_returns', '委外退料', '余料退回与入库状态', statusSource('委外退料','以供应商侧在外余量为上限，退料完成后回到本仓。','现有委外库存余额已保存累计已发、倒冲耗用、累计退料和在外余量。','退料主单、明细、待入库、正式入库、双方流水、重复执行与反审核。'), 'undo-2');
export const SubcontractReconciliationPage = page('page_subcontract_reconciliation', '委外对账', '供应商对账、赔偿抵扣和应付衔接', statusSource('委外对账','按供应商归集已完成回厂加工费和已审批赔偿，审核后生成应付。','现有订单和回厂记录保存加工费及累计对账金额字段。','赔偿负项、待对账池、来源防重、审核锁定、幂等应付和财务冲销边界。'), 'file-check-2');
export const SubcontractStockPage = page('page_subcontract_stock', '委外库存', '供应商侧材料库存子账', statusSource('委外库存','在外余量 = 累计已发 - 倒冲耗用 - 累计退料。','发料签收和回厂倒冲已写入委外库存余额与流水。','产品化的供应商/订单/物料视图、账龄、超期筛选、退料跳转和独立对账。'), 'warehouse');
export const SubcontractTracePage = page('page_subcontract_trace', '批次追溯', '材料批次与成品批次双向追溯', statusSource('委外批次追溯','正向从材料批次找到使用它的成品，反向从成品批次找到耗用材料。','发料明细、回厂明细和库存流水已有批次及来源字段。','稳定批次关系、跨单据追溯图、召回清单、反向校验和导出。'), 'scan-search');
export const SubcontractUndeliveredPage = page('page_subcontract_undelivered', '委外未交', '剩余交付和超期明细', statusSource('委外未交明细表','按订单、供应商、加工件、工艺和交期呈现剩余交付。','订单及加工件已有订购量、良品、不良品和期望交期。','统一作废口径、按行计算未交、超期筛选、金额口径、跳转和导出。'), 'clock-alert');
export const SubcontractReceiptsReportPage = page('page_subcontract_receipts_report', '委外进货', '回厂、良率和加工费明细', statusSource('委外进货明细表','按回厂批次分析数量、良品、不良、良率、加工费、仓库和批次。','现有回厂主单与明细已保存验收数量、良率、加工费、仓库和批次。','报表口径、日期范围、供应商筛选、作废排除、来源跳转和导出。'), 'chart-no-axes-column');
export const SubcontractStatementReportPage = page('page_subcontract_statement_report', '委外对账单', '加工费、扣款、应付和来源明细', statusSource('委外对账单（报表）','按供应商和账期展示加工费、补料、扣款、净应付及关联应付。','订单和回厂的加工费来源已经存在。','对账主单、赔偿与补料来源、净应付、关联应付、状态筛选和导出。'), 'receipt-text');
