import { forgeProductUiCss, forgeProductUiRuntime } from './product-ui.js';

const source = `
const {useEffect,useMemo,useState}=React;
const css=${JSON.stringify(forgeProductUiCss + '.st-page{min-height:100%;background:#f4f6f8;color:#222831}.st-page .head{padding:18px 22px;background:#fff;border-bottom:1px solid #e1e5ea}.st-page .head h1{margin:0 0 5px;font-size:22px}.st-page .head p{margin:0;color:#76808d;font-size:12px}.st-page .body{padding:18px 22px 40px;max-width:1480px;margin:auto}.st-page .modes{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.st-page .mode{border:1px solid #d6dce3;background:#fff;border-radius:5px;padding:10px 14px;text-align:left}.st-page .mode.active{border-color:#1769e0;background:#edf4ff;color:#1769e0}.st-page .mode strong,.st-page .mode span{display:block}.st-page .mode span{font-size:12px;color:#76808d;margin-top:3px}.st-page .form{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.st-page .form input{min-width:340px}.st-page .card{background:#fff;border:1px solid #dfe4e9;border-radius:7px;padding:15px;margin-bottom:14px}.st-page .summary{background:#f8fbff;border:1px solid #d9e8ff;color:#4a637d;padding:10px 12px;font-size:12px;margin-bottom:14px;border-radius:5px}.st-page .toast{position:fixed;right:26px;bottom:26px;background:#162033;color:#fff;padding:10px 14px;border-radius:6px;box-shadow:0 8px 30px rgba(0,0,0,.18);z-index:20}.st-page .table{overflow:auto;border:1px solid #e1e5ea;border-radius:5px}.st-page table{width:100%;border-collapse:collapse;font-size:12px;min-width:980px}.st-page th,.st-page td{padding:9px 10px;border-bottom:1px solid #edf0f3;text-align:left;vertical-align:top}.st-page th{background:#f7f8fa;color:#68727f;font-weight:500}.st-page .muted{color:#76808d;font-size:12px}.st-page .empty{padding:30px;text-align:center;color:#76808d}.st-page .link{color:#1769e0;background:none;border:0;padding:0;cursor:pointer}.st-page .footer{display:flex;justify-content:space-between;gap:12px;padding-top:10px;color:#76808d;font-size:12px}@media(max-width:620px){.st-page .body{padding:10px}.st-page .form input{min-width:0;width:100%}}')};
${forgeProductUiRuntime}
function App(){const adapter=useAdapter();
 const [state,setState]=useState({loading:true,error:'',issues:[],issueLines:[],orders:[],receipts:[],receiptLines:[],consumptions:[],plans:[],suppliers:[],ledgers:[]}),[mode,setMode]=useState('forward'),[input,setInput]=useState(''),[query,setQuery]=useState(''),[toast,setToast]=useState('');
 async function request(path){const r=await ForgeApiResponse(adapter,path,{credentials:'include',headers:{...(adapter?.getAuthHeaders?.()||{})}}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error((typeof p.error==='string'?p.error:p.error?.message)||(Array.isArray(p.fields)&&p.fields.length?p.fields.map(f=>f.message||f.label).filter(Boolean).join('；'):'')||p.message||'请求失败');return p}
 async function find(name){if(adapter?.find){const p=await adapter.find(name,{limit:1000});return p?.records||p?.data?.records||p?.data||[]}return(await request('/data/'+name+'?$top=1000')).records||[]}
 async function load(){try{const names=['forge_subcontract_issue','forge_subcontract_issue_line','forge_subcontract_order','forge_subcontract_receipt','forge_subcontract_receipt_line','forge_subcontract_receipt_consumption','forge_subcontract_material_plan','forge_supplier','forge_subcontract_stock_ledger'],rows=await Promise.all(names.map(find));setState({loading:false,error:'',issues:rows[0],issueLines:rows[1],orders:rows[2],receipts:rows[3],receiptLines:rows[4],consumptions:rows[5],plans:rows[6],suppliers:rows[7],ledgers:rows[8]})}catch(e){setState(s=>({...s,loading:false,error:String(e.message||e)}))}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)},[toast]);
 const maps={orders:Object.fromEntries(state.orders.map(x=>[x.id,x])),suppliers:Object.fromEntries(state.suppliers.map(x=>[x.id,x])),receipts:Object.fromEntries(state.receipts.map(x=>[x.id,x])),plans:Object.fromEntries(state.plans.map(x=>[x.id,x]))};
 const results=useMemo(()=>{if(!query.trim())return[];const needle=query.trim().toLowerCase(),rows=[];if(mode==='forward'){state.issueLines.filter(x=>String(x.batch_number||'').toLowerCase()===needle).forEach(line=>{const order=maps.orders[line.order_id],supplier=maps.suppliers[order?.supplier_id];state.receiptLines.filter(x=>x.order_id===line.order_id).forEach(receiptLine=>{const receipt=maps.receipts[receiptLine.receipt_id];rows.push({materialBatch:line.batch_number,material:line.name||line.item_code,materialQty:line.issue_quantity,order:order?.code||line.order_id,supplier:supplier?.name||'—',finishedBatch:receiptLine.batch_number||'未登记',receipt:receipt?.code||'—',finished:receiptLine.name,finishedQty:receiptLine.received_quantity,occurred:receipt?.receipt_on||'—'})})});}else state.receiptLines.filter(x=>String(x.batch_number||'').toLowerCase()===needle).forEach(line=>{const order=maps.orders[line.order_id],supplier=maps.suppliers[order?.supplier_id],receipt=maps.receipts[line.receipt_id],consumptions=state.consumptions.filter(x=>x.receipt_line_id===line.id);consumptions.forEach(item=>{const plan=maps.plans[item.plan_id],issueLines=state.issueLines.filter(x=>x.order_id===line.order_id&&(!plan||x.sku_id===plan.sku_id)),batched=issueLines.filter(x=>x.batch_number),chosen=batched.length?batched:[{}];chosen.forEach(issue=>rows.push({materialBatch:issue.batch_number||'未登记',material:issue.name||plan?.name||'—',materialQty:item.actual_quantity,order:order?.code||line.order_id,supplier:supplier?.name||'—',finishedBatch:line.batch_number,receipt:receipt?.code||'—',finished:line.name,finishedQty:line.received_quantity,occurred:receipt?.receipt_on||'—'}))})});return rows},[query,mode,state,maps]);
 function trace(){setQuery(input.trim())}
 function exportCsv(){const rows=[['方向','材料批次','材料','材料数量','委外订单','供应商','成品批次','回厂单','成品','成品数量','日期'],...results.map(x=>[mode==='forward'?'正向':'反向',x.materialBatch,x.material,x.materialQty,x.order,x.supplier,x.finishedBatch,x.receipt,x.finished,x.finishedQty,x.occurred])],csv='\\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='委外批次追溯-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(a.href);setToast('已导出 '+results.length+' 条批次追溯结果')}
 if(state.loading)return <div className="forge-product st-page"><style>{css}</style><div className="body">正在加载委外批次追溯…</div></div>;
 if(state.error)return <div className="forge-product st-page"><style>{css}</style><div className="body"><div className="card">{state.error}</div></div></div>;
 return <div className="forge-product st-page"><style>{css}</style><ForgeHero section="生产 / 委外管理 / 委外批次追溯" title="委外批次追溯" description="基于回厂倒冲记录的材料↔成品批次关联；出现质量问题时用它定位波及范围" icon="▤" tone="violet" art="flow"/><div className="body"><div className="modes"><button className={'mode '+(mode==='forward'?'active':'')} aria-pressed={mode==='forward'} onClick={()=>{setMode('forward');setInput('');setQuery('')}}><strong>正向追溯</strong><span>召回用 · 材料批次 → 用了它的成品</span></button><button className={'mode '+(mode==='reverse'?'active':'')} aria-pressed={mode==='reverse'} onClick={()=>{setMode('reverse');setInput('');setQuery('')}}><strong>反向追溯</strong><span>成品批号 → 它用了哪些材料</span></button></div><div className="form"><input className="fp-input" aria-label={mode==='forward'?'输入材料批次号':'输入成品批号'} placeholder={mode==='forward'?'输入材料批次号':'输入成品批号'} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&trace()}/><button className="fp-button primary" disabled={!input.trim()} onClick={trace}>追溯</button><button className="fp-button" disabled={!results.length} onClick={exportCsv}>导出</button></div>{!query&&<section className="card"><div className="empty">输入批次号开始追溯</div></section>}{query&&results.length===0&&<section className="card"><div className="empty">未找到与该批次号匹配的批次关联</div></section>}{query&&results.length>0&&<section className="card"><div className="summary">已找到 {results.length} 条批次关联，可用于质量召回和来源核查。</div><div className="table"><table><thead><tr><th>材料批次</th><th>材料</th><th>数量</th><th>委外订单</th><th>供应商</th><th>成品批次</th><th>回厂单</th><th>成品</th><th>成品数量</th><th>日期</th></tr></thead><tbody>{results.map((x,i)=><tr key={i}><td>{x.materialBatch}</td><td>{x.material}</td><td>{x.materialQty??'—'}</td><td><button className="link" onClick={()=>window.location.href='/_console/apps/com.inoforge.forge.production/page_subcontract_workspace?order_id='+encodeURIComponent(state.orders.find(o=>o.code===x.order)?.id||'')}>{x.order}</button></td><td>{x.supplier}</td><td>{x.finishedBatch}</td><td>{x.receipt}</td><td>{x.finished}</td><td>{x.finishedQty??'—'}</td><td>{x.occurred}</td></tr>)}</tbody></table></div><div className="footer"><span>共 {results.length} 条追溯结果</span><span>结果可导出，用于质量召回和来源核查。</span></div></section>}{toast&&<div className="toast" role="status">{toast}</div>}</div></div>;
}
export default App;
`;

export const SubcontractTracePage = { name: 'page_subcontract_trace', label: '批次追溯', description: '材料批次与委外回厂成品批次的正向和反向追溯', icon: 'search-check', type: 'app' as const, kind: 'react' as const, source };
