import { defineFlow } from '@objectstack/spec/automation';

export const SalesContractApprovalFlow = defineFlow({
  name: 'sales_contract_approval',
  label: '销售合同复核',
  description: '合同提交后按岗位找到复核员工，审批完成后更新合同并通知发起人。',
  type: 'record_change',
  status: 'active',
  runAs: 'system',
  successMessage: '合同复核已完成',
  errorMessage: '合同复核未能继续，请检查复核岗位配置',
  nodes: [
    {
      id: 'start',
      type: 'start',
      label: '合同已提交',
      config: {
        objectName: 'forge_sales_contract',
        triggerType: 'record-after-update',
        condition: "record.status == 'pending_approval' && previous.status == 'draft'",
      },
      position: { x: 80, y: 160 },
    },
    {
      id: 'contract_review',
      type: 'approval',
      label: '合同复核',
      config: {
        approvers: [{ type: 'position', value: 'contract_reviewer' }],
        behavior: 'first_response',
        lockRecord: true,
        onEmptyApprovers: 'fail',
        maxRevisions: 3,
      },
      position: { x: 320, y: 160 },
    },
    {
      id: 'activate_contract',
      type: 'update_record',
      label: '合同生效',
      config: {
        objectName: 'forge_sales_contract',
        filter: { id: '{record.id}' },
        fields: { status: 'active' },
      },
      position: { x: 600, y: 80 },
    },
    {
      id: 'notify_approved',
      type: 'notify',
      label: '通知发起人合同已通过',
      config: {
        recipients: ['{record.created_by}'],
        title: '合同 {record.code} 已复核通过',
        message: '合同已进入执行中，可以继续创建销售订单。',
        topic: 'sales.contract.approved',
        severity: 'info',
        sourceObject: 'forge_sales_contract',
        sourceId: '{record.id}',
        actionUrl: '/_console/apps/forge/forge_sales_contract/record/{record.id}',
      },
      position: { x: 850, y: 80 },
    },
    {
      id: 'wait_revision',
      type: 'approval_revise',
      label: '等待发起人修改',
      config: {},
      position: { x: 600, y: 260 },
    },
    {
      id: 'reject_contract',
      type: 'update_record',
      label: '终止合同审批',
      config: {
        objectName: 'forge_sales_contract',
        filter: { id: '{record.id}' },
        fields: { status: 'rejected' },
      },
      position: { x: 600, y: 260 },
    },
    {
      id: 'notify_rejected',
      type: 'notify',
      label: '通知发起人合同审批已终止',
      config: {
        recipients: ['{record.created_by}'],
        title: '合同 {record.code} 审批未通过',
        message: '本次审批已终止。请查看审批意见后重新发起。',
        topic: 'sales.contract.rejected',
        severity: 'warning',
        sourceObject: 'forge_sales_contract',
        sourceId: '{record.id}',
        actionUrl: '/_console/apps/forge/forge_sales_contract/record/{record.id}',
      },
      position: { x: 850, y: 260 },
    },
    { id: 'approved_end', type: 'end', label: '复核通过', position: { x: 1100, y: 80 } },
    { id: 'rejected_end', type: 'end', label: '复核未通过', position: { x: 1100, y: 260 } },
  ],
  edges: [
    { id: 'submitted_to_review', source: 'start', target: 'contract_review' },
    { id: 'review_approved', source: 'contract_review', target: 'activate_contract', label: 'approve' },
    { id: 'approved_to_notification', source: 'activate_contract', target: 'notify_approved' },
    { id: 'approved_to_end', source: 'notify_approved', target: 'approved_end' },
    { id: 'review_revision', source: 'contract_review', target: 'wait_revision', label: 'revise' },
    { id: 'revision_resubmitted', source: 'wait_revision', target: 'contract_review', type: 'back', label: 'resubmit' },
    { id: 'review_rejected', source: 'contract_review', target: 'reject_contract', label: 'reject' },
    { id: 'rejected_to_notification', source: 'reject_contract', target: 'notify_rejected' },
    { id: 'rejected_to_end', source: 'notify_rejected', target: 'rejected_end' },
  ],
});
