import { defineAction } from '@objectstack/spec';

const identity = String.raw`
const api=ctx.api,input=ctx.input||{},actor=String(ctx.user&&ctx.user.id||ctx.session&&ctx.session.userId||'').trim(),org=String(ctx.user&&ctx.user.organizationId||ctx.session&&ctx.session.organizationId||'').trim();
if(!actor||!org)throw new Error('无法确认当前员工和组织');
const text=v=>typeof v==='string'?v.trim():'',number=(v,label)=>{if(v===null||v===undefined||v===''||!['number','string'].includes(typeof v)||!Number.isFinite(Number(v)))throw new Error(label+'必须填写有效数字');return Number(v)},round=v=>Math.round((v+Number.EPSILON)*10000)/10000;
const rowId=value=>typeof value==='string'?value:value&&(value.id||value.record&&value.record.id);
const all=async(object,where)=>{const result=[];for(let offset=0;offset<10000;offset+=200){const batch=await api.object(object).find({where,offset,limit:200,orderBy:[{field:'id',order:'asc'}]});result.push(...batch);if(batch.length<200)return result}throw new Error('记录较多，请缩小范围后重试')};
const member=await api.object('sys_member').findOne({where:{organization_id:org,user_id:actor}});if(!member)throw new Error('当前员工不属于本组织');
const owned=row=>row&&String(row.organization_id||'')===org&&[row.owner_id,row.responsible_id,row.created_by].some(value=>String(value||'')===actor);
const reviewer=async(positionName,preferred)=>{const positions=await all('sys_position',{organization_id:org,name:positionName}),keys=new Set(positions.filter(row=>row.active!==false&&row.active!==0&&row.active!=='false').flatMap(row=>[String(row.id),String(row.name)])),assignments=await all('sys_user_position',{organization_id:org}),now=Date.now(),ids=[...new Set(assignments.filter(row=>keys.has(String(row.position))&&(!row.valid_from||Date.parse(row.valid_from)<=now)&&(!row.valid_until||now<Date.parse(row.valid_until))).map(row=>String(row.user_id)).filter(id=>id&&id!==actor))],members=await all('sys_member',{organization_id:org}),memberIds=new Set(members.map(row=>String(row.user_id))),users=ids.length?await all('sys_user',{id:{$in:ids}}):[],eligible=users.filter(row=>memberIds.has(String(row.id))&&(!(row.banned===true||row.banned===1||row.banned==='true')||Number.isFinite(Date.parse(row.ban_expires))&&Date.parse(row.ban_expires)<=now)).map(row=>String(row.id));if(preferred&&eligible.includes(String(preferred)))return String(preferred);if(eligible.length!==1)throw new Error(eligible.length?'有多名有效复核人，请先明确本单复核人':'未找到有效的独立复核人');return eligible[0]};
`;

export const SalesDiscountDraftSave = defineAction({
  name: 'sales_discount_draft_save', label: '保存销售优惠草稿', objectName: 'forge_sales_discount_request', locations: [], requiredPermissions: ['sales_order_operator'],
  params: [{ name: 'request_key', label: '保存请求标识', type: 'text', required: true }, { name: 'request_id', label: '优惠申请', type: 'text' }, { name: 'expected_revision', label: '草稿版本', type: 'number' }, { name: 'order_id', label: '销售订单', type: 'text', required: true }, { name: 'discount_type', label: '优惠方式', type: 'text', required: true }, { name: 'discount_value', label: '申请数值', type: 'number', required: true }, { name: 'reason', label: '申请原因', type: 'textarea', required: true }],
  body: { language: 'js', capabilities: ['api.read', 'api.write', 'api.transaction'], source: identity + String.raw`
const key=text(input.request_key),id=text(input.request_id),orderId=text(input.order_id),kind=text(input.discount_type),value=number(input.discount_value,'优惠数值'),reason=text(input.reason),signature=JSON.stringify({id,orderId,kind,value,reason,revision:id?number(input.expected_revision,'草稿版本'):0});
if(!key||key.length>128||!orderId||!reason||reason.length>2000||!['amount','percentage'].includes(kind)||value<=0||kind==='percentage'&&value>100)throw new Error('请填写订单、有效优惠数值和申请原因');
return await api.transaction(async()=>{const requests=api.object('forge_sales_discount_request'),prior=await requests.findOne({where:{organization_id:org,$or:[{request_key:key},{save_receipts:{$contains:JSON.stringify(key)}}]}});if(prior){if(!owned(prior)||((JSON.parse(prior.save_receipts||'{}')[key]||prior.request_key===key&&prior.request_signature)!==signature))throw new Error('同一保存请求不能更换申请内容');return{id:prior.id,code:prior.code,status:prior.status,revision:prior.revision,replayed:true}}
 const order=await api.object('forge_sales_order').findOne({where:{id:orderId,organization_id:org}});if(!owned(order)||['cancelled','completed'].includes(String(order.status)))throw new Error('只能为本人可办理且未关闭的订单申请优惠');const base=number(order.total_amount,'订单金额'),discount=round(kind==='percentage'?base*value/100:value);if(base<=0||discount<=0||discount>base)throw new Error('优惠金额必须大于零且不能超过订单金额');const customer=order.customer_id?await api.object('forge_customer').findOne({where:{id:order.customer_id,organization_id:org}}):null;
 const data={name:String(order.code||order.name)+' 优惠申请',order_id:order.id,order_code:String(order.code||order.name),customer_id:order.customer_id||null,customer_name:String(customer&&customer.name||''),discount_type:kind,discount_value:value,original_amount:base,discount_amount:discount,proposed_amount:round(base-discount),reason,request_key:key,request_signature:signature};let recordId=id;
 if(id){const current=await requests.findOne({where:{id,organization_id:org}});if(!owned(current)||current.status!=='draft'||Number(current.revision)!==Number(input.expected_revision))throw new Error('草稿已变化或不能修改，请重新打开');const count=await requests.update({...data,request_key:current.request_key,request_signature:current.request_signature,save_receipts:JSON.stringify({...JSON.parse(current.save_receipts||'{}'),[key]:signature}),revision:Number(current.revision)+1},{multi:true,where:{id,organization_id:org,status:'draft',revision:Number(current.revision)}});if(count!==1)throw new Error('另一操作正在更新草稿，请重新打开')}else{recordId=rowId(await requests.insert({...data,organization_id:org,owner_id:actor,responsible_id:actor,submitted_by:actor,status:'draft',save_receipts:JSON.stringify({[key]:signature}),revision:0}))}
 const saved=await requests.findOne({where:{id:recordId,organization_id:org}});if(!saved)throw new Error('未能读回优惠草稿，请核对保存结果');return{id:saved.id,code:saved.code,status:saved.status,revision:saved.revision,replayed:false};});
` },
});

export const SalesAdditionalFeeDraftSave = defineAction({
  name: 'sales_additional_fee_draft_save', label: '保存销售附加费用草稿', objectName: 'forge_sales_additional_fee', locations: [], requiredPermissions: ['sales_contract_operator'],
  params: [{ name: 'request_key', label: '保存请求标识', type: 'text', required: true }, { name: 'fee_id', label: '费用单', type: 'text' }, { name: 'expected_revision', label: '草稿版本', type: 'number' }, { name: 'source_type', label: '来源类型', type: 'text', required: true }, { name: 'source_id', label: '来源单据', type: 'text', required: true }, { name: 'bearing_type', label: '承担类型', type: 'text', required: true }, { name: 'lines_json', label: '费用明细', type: 'textarea', required: true }, { name: 'occurred_on', label: '发生日期', type: 'text', required: true }, { name: 'settlement_type', label: '结算层级', type: 'text', required: true }, { name: 'expected_settlement_on', label: '预计结算日期', type: 'text' }, { name: 'remarks', label: '说明', type: 'textarea' }],
  body: { language: 'js', capabilities: ['api.read', 'api.write', 'api.transaction'], source: identity + String.raw`
const feeId=text(input.fee_id),expectedRevision=feeId?number(input.expected_revision,'草稿版本'):0,key=text(input.request_key),sourceType=text(input.source_type),sourceId=text(input.source_id),bearing=text(input.bearing_type),settlement=text(input.settlement_type),date=text(input.occurred_on),expected=text(input.expected_settlement_on),note=text(input.remarks);let lines;try{lines=JSON.parse(String(input.lines_json||''))}catch{throw new Error('费用明细格式无效')}
const validDate=value=>{const instant=new Date(value+'T00:00:00Z');return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(instant.getTime())&&instant.toISOString().slice(0,10)===value};if(!key||key.length>128||!['sales_order','sales_contract','sales_shipment','manual'].includes(sourceType)||!sourceId||!['customer','company'].includes(bearing)||!['order','project'].includes(settlement)||!validDate(date)||expected&&!validDate(expected)||!Array.isArray(lines)||!lines.length)throw new Error('请填写来源单据、承担类型、费用明细和有效日期');
const normalized=lines.map((line,index)=>{const name=text(line.name),category=text(line.category),untaxed=number(line.untaxed_amount,'第'+(index+1)+'行不含税金额'),rate=number(line.tax_rate,'第'+(index+1)+'行税率');if(!name||name.length>255||category.length>255||untaxed<=0||rate<0||rate>100)throw new Error('费用名称、正数金额或税率无效');const tax=round(untaxed*rate/100);return{name,category,untaxed_amount:round(untaxed),tax_rate:rate,tax_amount:tax,total_amount:round(untaxed+tax),line_number:index+1,remarks:text(line.remarks)}}),signature=JSON.stringify({feeId,expectedRevision,sourceType,sourceId,bearing,settlement,date,expected,note,lines:normalized});
return await api.transaction(async()=>{const fees=api.object('forge_sales_additional_fee'),prior=await fees.findOne({where:{organization_id:org,$or:[{request_key:key},{save_receipts:{$contains:JSON.stringify(key)}}]}});if(prior){if(!owned(prior)||((JSON.parse(prior.save_receipts||'{}')[key]||prior.request_key===key&&prior.request_signature)!==signature))throw new Error('同一保存请求不能更换费用内容');return{id:prior.id,code:prior.code,status:prior.document_status,revision:prior.revision,replayed:true}}
 const object=sourceType==='sales_order'?'forge_sales_order':sourceType==='sales_contract'?'forge_sales_contract':sourceType==='sales_shipment'?'forge_sales_shipment':'forge_customer',source=await api.object(object).findOne({where:{id:sourceId,organization_id:org}});if(!source)throw new Error('来源单据不可读取或不属于本组织');if(['cancelled','voided','terminated'].includes(String(source.status)))throw new Error('来源单据已关闭');const orderId=sourceType==='sales_order'?source.id:sourceType==='sales_shipment'?source.order_id:null,order=orderId?await api.object('forge_sales_order').findOne({where:{id:orderId,organization_id:org}}):null,customerId=sourceType==='manual'?source.id:source.customer_id||order&&order.customer_id;if(!customerId)throw new Error('来源单据缺少客户归属');const customer=await api.object('forge_customer').findOne({where:{id:customerId,organization_id:org}});if(!customer)throw new Error('来源客户不可读取');const links=sourceType==='manual'?[]:await api.object('forge_project_sales_link').find({where:{organization_id:org,...(orderId?{order_id:orderId}:{contract_id:source.id})},limit:2});if(links.length>1)throw new Error('来源单据关联多个项目，请先明确费用归属');const project=links[0]?await api.object('forge_project').findOne({where:{id:links[0].project_id,organization_id:org}}):null;if(settlement==='project'&&!project)throw new Error('项目结算需要来源单据已有正式项目关联');
 const prefix='AF-'+date.replaceAll('-','')+'-',previous=await fees.find({where:{organization_id:org,code:{$startsWith:prefix}},orderBy:[{field:'code',order:'desc'}],limit:1}),sequence=previous.length?Number(String(previous[0].code).slice(prefix.length))+1:1;if(!Number.isSafeInteger(sequence)||sequence<1)throw new Error('费用编号暂不可生成，请重试');let code=prefix+String(sequence).padStart(4,'0');const current=feeId?await fees.findOne({where:{id:feeId,organization_id:org}}):null;if(feeId&&(!owned(current)||current.document_status!=='draft'||Number(current.revision)!==expectedRevision))throw new Error('费用草稿已变化或不能修改，请重新打开');if(current)code=current.code;const untaxed=round(normalized.reduce((sum,line)=>sum+line.untaxed_amount,0)),tax=round(normalized.reduce((sum,line)=>sum+line.tax_amount,0)),total=round(normalized.reduce((sum,line)=>sum+line.total_amount,0));
 const receipts={...JSON.parse(current&&current.save_receipts||'{}'),[key]:signature};const data={name:normalized.map(line=>line.name).join('、').slice(0,255),code,request_key:current?current.request_key:key,request_signature:current?current.request_signature:signature,save_receipts:JSON.stringify(receipts),source_type:sourceType,order_id:orderId,contract_id:sourceType==='sales_contract'?source.id:order&&order.contract_id||null,shipment_id:sourceType==='sales_shipment'?source.id:null,customer_id:customerId,project_id:project&&project.id||null,project_name:project&&project.name||'',responsible_id:source.responsible_id||order&&order.responsible_id||actor,owner_id:actor,organization_id:org,bearing_type:bearing,fee_item:normalized.map(line=>line.name).join('、').slice(0,255),occurred_on:date,untaxed_amount:untaxed,tax_amount:tax,total_amount:total,settlement_type:settlement,expected_settlement_on:expected||null,remarks:note,document_status:'draft',finance_status:'pending',revision:feeId?expectedRevision+1:0};let id=feeId;if(feeId){const changed=await fees.update(data,{multi:true,where:{id:feeId,organization_id:org,document_status:'draft',revision:expectedRevision}});if(changed!==1)throw new Error('另一操作正在更新费用草稿');await api.object('forge_sales_additional_fee_line').delete({multi:true,where:{fee_id:feeId,organization_id:org}})}else{id=rowId(await fees.insert(data))}if(!id)throw new Error('保存未返回费用单引用，请核对保存结果');for(const line of normalized)await api.object('forge_sales_additional_fee_line').insert({...line,fee_id:id,owner_id:actor,organization_id:org});return{id,code,status:'draft',revision:feeId?expectedRevision+1:0,total_amount:total,replayed:false};});
` },
});

const submission = (object: string, statusField: string, target: string, role: string) => identity + `
const id=String(ctx.recordId||ctx.record&&ctx.record.id||'').trim(),revision=number(input.expected_revision,'草稿版本');if(!id||ctx.recordLoadDenied===true)throw new Error('申请记录不可读取');
return await api.transaction(async()=>{const records=api.object('${object}'),current=await records.findOne({where:{id,organization_id:org}});if(!owned(current))throw new Error('当前员工不能提交此记录');if(current.${statusField}==='pending_approval')return{id:current.id,code:current.code,status:current.${statusField},revision:current.revision,replayed:true};if(current.${statusField}!=='draft'||Number(current.revision)!==revision)throw new Error('草稿已变化或已经提交，请重新打开');
 let preferred='';if(current.order_id){const order=await api.object('forge_sales_order').findOne({where:{id:current.order_id,organization_id:org}});if(!order||order.status==='cancelled')throw new Error('来源订单不可读取或已取消');${object==='forge_sales_discount_request'?"if(order.status==='completed')throw new Error('订单已完成，不能提交新的优惠申请');if(number(order.total_amount,'订单金额')!==number(current.original_amount,'冻结订单金额'))throw new Error('订单金额已变化，请重新保存优惠草稿');preferred=String(order.review_owner_id||'');":''}}
 const reviewOwner=await reviewer('${role}',preferred);const count=await records.update({${statusField}:'pending_approval',approval_status:null,review_owner_id:reviewOwner,submitted_by:actor,submitted_at:new Date().toISOString(),revision:revision+1},{multi:true,where:{id,organization_id:org,${statusField}:'draft',revision}});if(count!==1)throw new Error('另一操作已提交此记录，请核对最新结果');return{id:current.id,code:current.code,status:'pending_approval',revision:revision+1,approval:'native',effect:'${target}',replayed:false};});
`;
export const SalesDiscountSubmit = defineAction({ name: 'sales_discount_submit', label: '提交销售优惠审批', objectName: 'forge_sales_discount_request', requiredPermissions: ['sales_order_operator'], locations: [], params: [{ name: 'expected_revision', label: '草稿版本', type: 'number', required: true }], body: { language: 'js', capabilities: ['api.read','api.write','api.transaction'], source: submission('forge_sales_discount_request','status','manual_order_adjustment','sales_order_reviewer') } });
export const SalesAdditionalFeeSubmit = defineAction({ name: 'sales_additional_fee_submit', label: '提交销售费用审批', objectName: 'forge_sales_additional_fee', requiredPermissions: ['sales_contract_operator'], locations: [], params: [{ name: 'expected_revision', label: '草稿版本', type: 'number', required: true }], body: { language: 'js', capabilities: ['api.read','api.write','api.transaction'], source: submission('forge_sales_additional_fee','document_status','finance_handoff','finance_reviewer') } });
