import { defineAction } from '@objectstack/spec';
import { salesPricingIdentity } from './sales-pricing.source.js';

const body = (source: string) => ({ language: 'js' as const, capabilities: ['api.read' as const, 'api.write' as const, 'api.transaction' as const], timeoutMs: 30000, source: salesPricingIdentity + source });

export const SalesPriceGroupSave = defineAction({
  name: 'sales_price_group_save', label: '保存销售价格组', objectName: 'forge_sales_price_group', locations: [], requiredPermissions: ['forge_sales_settings_manage'],
  params: [{ name: 'request_key', label: '保存请求', type: 'text', required: true }, { name: 'group_id', label: '价格组', type: 'text' }, { name: 'expected_revision', label: '记录版本', type: 'number' }, { name: 'name', label: '名称', type: 'text', required: true }, { name: 'description', label: '描述', type: 'textarea' }, { name: 'status', label: '状态', type: 'text' }],
  body: body(String.raw`
const key=text(input.request_key),id=text(input.group_id),name=text(input.name),description=text(input.description),status=text(input.status)||'active',revision=id?Number(input.expected_revision):0,signature=JSON.stringify({operation:'group',id,name,description,status,revision});if(!name||name.length>255||description.length>2000||!['active','inactive'].includes(status)||!Number.isSafeInteger(revision)||revision<0)throw new Error('请填写有效的价格组名称和描述');
return await api.transaction(async()=>{const prior=await receipt(key,signature);if(prior)return prior;const groups=api.object('forge_sales_price_group');let savedId=id;if(id){const group=await groups.findOne({where:{id,organization_id:org}});if(!group||Number(group.revision)!==revision)throw new Error('价格组已变化，请重新打开');const changed=await groups.update({name,description,status,revision:revision+1},{where:{id,organization_id:org,revision},multi:true});if(changed!==1)throw new Error('价格组已被其他人修改')}else{savedId=rowId(await groups.insert({name,description,status,revision:0,owner_id:actor,organization_id:org}))}if(!savedId)throw new Error('保存结果不完整，请重新读取价格组');return await saveReceipt(key,signature,{id:savedId,revision:id?revision+1:0,name,status},'保存价格组');});
`),
});

export const SalesPriceGroupAssign = defineAction({
  name: 'sales_price_group_assign', label: '分配销售价格组物料', objectName: 'forge_sales_price_group', locations: [], requiredPermissions: ['forge_sales_settings_manage'],
  params: [{ name: 'request_key', label: '请求标识', type: 'text', required: true }, { name: 'group_id', label: '目标价格组', type: 'text' }, { name: 'sku_ids_json', label: '物料规格', type: 'textarea', required: true }],
  body: body(String.raw`
const key=text(input.request_key),groupId=text(input.group_id);let ids;try{ids=JSON.parse(String(input.sku_ids_json||''))}catch{throw new Error('物料选择无效')}if(!Array.isArray(ids)||!ids.length||ids.length>200||ids.some(id=>!text(id)))throw new Error('请选择 1 至 200 项物料');ids=[...new Set(ids.map(text))].sort();const signature=JSON.stringify({operation:'assign',groupId,ids});
return await api.transaction(async()=>{const prior=await receipt(key,signature);if(prior)return prior;const group=groupId?await api.object('forge_sales_price_group').findOne({where:{id:groupId,organization_id:org}}):null;if(groupId&&(!group||group.status!=='active'))throw new Error('目标价格组已停用或不可读取');for(const id of ids){const sku=await api.object('forge_material_sku').findOne({where:{id,organization_id:org}});if(!sku||sku.enabled===false)throw new Error('物料规格已停用或不可读取');const members=api.object('forge_sales_price_group_member'),current=await members.findOne({where:{sku_id:id,organization_id:org}});if(current&&current.group_id===groupId)continue;if(current)await members.delete({where:{id:current.id,organization_id:org}});if(groupId){const material=await api.object('forge_material').findOne({where:{id:sku.material_id,organization_id:org}});await members.insert({name:material&&material.name||sku.name,material_code:material&&material.code||sku.code,group_id:groupId,sku_id:id,owner_id:actor,organization_id:org})}}return await saveReceipt(key,signature,{group_id:groupId,count:ids.length},'分配价格组物料');});
`),
});

export const SalesPriceDraftSave = defineAction({
  name: 'sales_price_draft_save', label: '保存销售价格申请', objectName: 'forge_sales_price_request', locations: [], requiredPermissions: ['sales_order_operator'],
  params: [{ name: 'request_key', label: '保存请求', type: 'text', required: true }, { name: 'request_id', label: '价格申请', type: 'text' }, { name: 'expected_revision', label: '草稿版本', type: 'number' }, { name: 'draft_json', label: '完整申请', type: 'textarea', required: true }],
  body: body(String.raw`
const key=text(input.request_key),id=text(input.request_id),revision=id?Number(input.expected_revision):0,draft=normalizeDraft(String(input.draft_json||'')),signature=JSON.stringify({operation:'draft',id,revision,draft});if(!Number.isSafeInteger(revision)||revision<0)throw new Error('草稿版本无效');
return await api.transaction(async()=>{const prior=await receipt(key,signature);if(prior)return prior;const requests=api.object('forge_sales_price_request'),current=id?await requests.findOne({where:{id,organization_id:org}}):null;if(id&&(!owned(current)||current.status!=='draft'||Number(current.revision)!==revision))throw new Error('申请已变化或不可修改');
 const customer=draft.customer_id?await api.object('forge_customer').findOne({where:{id:draft.customer_id,organization_id:org}}):null;if(draft.customer_id&&!customer)throw new Error('所选客户不可读取');const contact=draft.contact_id?await api.object('forge_contact').findOne({where:{id:draft.contact_id,organization_id:org}}):null;if(draft.contact_id&&(!contact||contact.customer_id!==draft.customer_id))throw new Error('联系人不属于所选客户');const quote=draft.quotation_id?await api.object('forge_quotation').findOne({where:{id:draft.quotation_id,organization_id:org}}):null;if(draft.quotation_id&&(!quote||quote.customer_id!==draft.customer_id||![quote.owner_id,quote.responsible_id,quote.created_by].includes(actor)))throw new Error('来源报价须为本人可办理的该客户报价');
 const attachmentIds=draft.attachment_ids===undefined?(Array.isArray(current&&current.attachment_ids)?current.attachment_ids.map(file=>typeof file==='string'?file:String(file.id||'')):[]):draft.attachment_ids;
 for(const fileId of attachmentIds){const file=await api.object('sys_file').findOne({where:{id:fileId,organization_id:org}}),linked=!!(id&&file&&file.ref_object==='forge_sales_price_request'&&String(file.ref_id)===id&&file.ref_field==='attachment_ids');if(!file||file.status!=='committed'||!linked&&(file.owner_id!==actor||file.ref_object!=null||file.ref_id!=null||file.ref_field!=null))throw new Error('辅助材料尚未上传完成或不属于本申请');if(!/\.(pdf|docx?|xlsx?|pptx?|png|jpe?g|gif|webp)$/i.test(String(file.name||''))||!Number.isFinite(Number(file.size))||Number(file.size)<=0||Number(file.size)>20*1024*1024)throw new Error('辅助材料须为不超过20MB的PDF、Office文档或图片');}
 const lines=[];let originalTotal=0;for(const line of draft.lines){const sku=await api.object('forge_material_sku').findOne({where:{id:line.sku_id,organization_id:org}});if(!sku||sku.enabled===false)throw new Error('所选物料已停用或不可读取');const material=await api.object('forge_material').findOne({where:{id:sku.material_id,organization_id:org}});if(!material)throw new Error('所选物料主记录不可读取');const unit=material.unit_id?await api.object('forge_unit').findOne({where:{id:material.unit_id,organization_id:org}}):null,target=targetKey(draft.kind,draft.customer_id,line.sku_id),cursors=api.object('forge_sales_price_cursor');let cursor=await cursors.findOne({where:{target_key:target,organization_id:org}});if(!cursor){const cursorId=rowId(await cursors.insert({name:material.name,target_key:target,revision:0,owner_id:actor,organization_id:org}));cursor={id:cursorId,revision:0}}const baseline=draft.kind==='adjustment'?{price:sku.sale_price==null?null:Number(sku.sale_price)}:await currentPrice(org,sku,draft.customer_id,draft.valid_from);if(baseline===null||baseline.price!==null&&(!Number.isFinite(baseline.price)||baseline.price<0))throw new Error(material.name+'的正常售价尚未配置');const originalAmount=baseline.price===null?null:round(baseline.price*Number(line.quantity));originalTotal=originalTotal===null||originalAmount===null?null:round(originalTotal+originalAmount);if(draft.kind==='adjustment'&&Number(line.minimum_price??sku.minimum_sale_price??0)>Number(line.proposed_price))throw new Error(material.name+'的目录价不能低于最低售价');lines.push({...line,name:material.name,material_code:material.code||sku.code,specification:sku.name||material.model,unit_name:unit&&unit.name||material.unit_name||'',quantity:Number(line.quantity),proposed_price:Number(line.proposed_price),proposed_amount:Number(line.proposed_amount),minimum_price:line.minimum_price===null?sku.minimum_sale_price??null:Number(line.minimum_price),suggested_price:line.suggested_price===null?sku.suggested_sale_price??null:Number(line.suggested_price),original_price:baseline.price,original_amount:originalAmount,original_minimum_price:sku.minimum_sale_price??null,original_suggested_price:sku.suggested_sale_price??null,baseline_token:baselineToken(sku),baseline_revision:Number(cursor.revision),target_key:target});}
 const labels={adjustment:'目录调价',special:'特价申请',agreement:'框架协议价'},data={name:(customer?customer.name+' ':'')+labels[draft.kind],kind:draft.kind,customer_id:customer&&customer.id||null,customer_name:customer&&customer.name||'',contact_id:contact&&contact.id||null,contact_name:contact&&contact.name||'',quotation_id:quote&&quote.id||null,quotation_code:quote&&quote.code||'',valid_from:draft.valid_from||null,valid_until:draft.valid_until||null,long_term:draft.long_term,priority:draft.priority,reason:draft.reason,attachment_ids:attachmentIds,review_owner_id:draft.review_owner_id||null,item_count:lines.length,original_total:originalTotal,proposed_total:Number(draft.proposed_total),revision:id?revision+1:0};let savedId=id;if(id){const changed=await requests.update(data,{where:{id,organization_id:org,status:'draft',revision},multi:true});if(changed!==1)throw new Error('另一操作已更新草稿');await api.object('forge_sales_price_request_line').delete({where:{request_id:id,organization_id:org},multi:true})}else{savedId=rowId(await requests.insert({...data,status:'draft',effect_status:'pending',submitted_by:actor,owner_id:actor,organization_id:org}))}if(!savedId)throw new Error('保存结果不完整，请重新读取申请');for(const line of lines)await api.object('forge_sales_price_request_line').insert({...line,request_id:savedId,owner_id:actor,organization_id:org});const saved=await requests.findOne({where:{id:savedId,organization_id:org}});for(const fileId of attachmentIds){const held=await api.object('sys_file').findOne({where:{id:fileId,organization_id:org}});if(!held||held.ref_object!=='forge_sales_price_request'||String(held.ref_id)!==String(savedId)||held.ref_field!=='attachment_ids')throw new Error('辅助材料归属尚未确认，已取消保存');}return await saveReceipt(key,signature,{id:savedId,code:saved.code,status:saved.status,revision:saved.revision},'保存价格申请');});
`),
});

export const SalesPriceSubmit = defineAction({
  name: 'sales_price_submit', label: '提交销售价格审批', objectName: 'forge_sales_price_request', locations: [], requiredPermissions: ['sales_order_operator'],
  params: [{ name: 'expected_revision', label: '草稿版本', type: 'number', required: true }],
  body: body(String.raw`
const id=text(ctx.recordId||ctx.record&&ctx.record.id),revision=Number(input.expected_revision);if(!id||ctx.recordLoadDenied===true||!Number.isSafeInteger(revision)||revision<0)throw new Error('申请不可读取或版本无效');
return await api.transaction(async()=>{const requests=api.object('forge_sales_price_request'),current=await requests.findOne({where:{id,organization_id:org}});if(!owned(current))throw new Error('只能提交本人价格申请');if(current.status==='pending_approval'&&Number(current.revision)===revision+1)return{id,code:current.code,status:current.status,revision:current.revision};if(current.status!=='draft'||Number(current.revision)!==revision)throw new Error('草稿已变化，请重新打开');if(current.kind!=='agreement'&&!text(current.reason))throw new Error('提交审批须填写原因');if(current.valid_until&&String(current.valid_until).slice(0,10)<today())throw new Error('申请有效期已结束');const lines=await all('forge_sales_price_request_line',{request_id:id,organization_id:org});if(!lines.length||lines.length!==Number(current.item_count))throw new Error('申请明细不完整');for(const line of lines){const sku=await api.object('forge_material_sku').findOne({where:{id:line.sku_id,organization_id:org}}),cursor=await api.object('forge_sales_price_cursor').findOne({where:{target_key:line.target_key,organization_id:org}});if(!sku||sku.enabled===false||baselineToken(sku)!==line.baseline_token||!cursor||Number(cursor.revision)!==Number(line.baseline_revision))throw new Error(line.name+'的价格已变化，请重新保存草稿')};const reviewer=await chooseReviewer(text(current.review_owner_id)),changed=await requests.update({status:'pending_approval',approval_status:null,review_owner_id:reviewer,submitted_at:new Date().toISOString(),revision:revision+1},{where:{id,organization_id:org,status:'draft',revision},multi:true});if(changed!==1)throw new Error('另一操作已提交申请');return{id,code:current.code,status:'pending_approval',revision:revision+1,approval:'native'};});
`),
});

export const SalesPriceTerminate = defineAction({
  name: 'sales_price_terminate', label: '终止客户价格', objectName: 'forge_sales_price_request', locations: [], requiredPermissions: ['sales_order_reviewer'],
  params: [{ name: 'expected_revision', label: '记录版本', type: 'number', required: true }],
  body: body(String.raw`
const id=text(ctx.recordId||ctx.record&&ctx.record.id),revision=Number(input.expected_revision);if(!id||ctx.recordLoadDenied===true||!Number.isSafeInteger(revision))throw new Error('价格记录不可读取');return await api.transaction(async()=>{const requests=api.object('forge_sales_price_request'),current=await requests.findOne({where:{id,organization_id:org}});if(!current||current.kind==='adjustment'||current.status!=='approved'||current.effect_status!=='applied'||Number(current.revision)!==revision)throw new Error('只能终止已生效的客户价格');const lines=await all('forge_sales_price_request_line',{request_id:id,organization_id:org});for(const line of lines){const cursor=await api.object('forge_sales_price_cursor').findOne({where:{target_key:line.target_key,organization_id:org}});if(!cursor)throw new Error('客户价格状态不完整');const locked=await api.object('forge_sales_price_cursor').update({revision:Number(cursor.revision)+1},{where:{id:cursor.id,organization_id:org,revision:cursor.revision},multi:true});if(locked!==1)throw new Error('客户价格正在变化，请重新读取')}const changed=await requests.update({status:'terminated',revision:revision+1},{where:{id,organization_id:org,status:'approved',revision},multi:true});if(changed!==1)throw new Error('价格状态已变化');return{id,code:current.code,status:'terminated',revision:revision+1};});
`),
});

export const SalesPriceResolve = defineAction({
  name: 'sales_price_resolve', label: '读取客户有效销售价格', objectName: 'forge_sales_price_request', locations: [], requiredPermissions: ['sales_order_operator'],
  params: [{ name: 'customer_id', label: '客户', type: 'text', required: true }, { name: 'sku_id', label: '物料规格', type: 'text', required: true }, { name: 'date', label: '业务日期', type: 'text' }],
  body: { language: 'js', capabilities: ['api.read'], timeoutMs: 30000, source: salesPricingIdentity + String.raw`
const customerId=text(input.customer_id),skuId=text(input.sku_id),date=text(input.date)||today();if(!customerId||!skuId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!await api.object('forge_customer').findOne({where:{id:customerId,organization_id:org}}))throw new Error('客户、物料或业务日期无效');const sku=await api.object('forge_material_sku').findOne({where:{id:skuId,organization_id:org}});if(!sku||sku.enabled===false)throw new Error('物料规格不可读取');const result=await currentPrice(org,sku,customerId,date);if(!result)throw new Error('物料尚未配置销售价格');return{...result,date};
` },
});

export const SalesPriceReviewers = defineAction({
  name: 'sales_price_reviewers', label: '读取价格审批人', objectName: 'forge_sales_price_request', locations: [], requiredPermissions: ['sales_order_operator'],
  body: { language: 'js', capabilities: ['api.read'], timeoutMs: 30000, source: salesPricingIdentity + String.raw`
return {reviewers:(await eligibleReviewers()).map(user=>({id:user.id,name:user.display_name||user.name||user.username||'审批人'}))};
` },
});

